# Eksperimenter med lånekassens dokumenter med NB sBERT 
De har mye parallelldata

In [1]:
from pathlib import Path
import pandas as pd
from hemmelig import data_path

p = Path(data_path)

filer = [e for e in p.iterdir() if "lanekassen" in e.name]

dfs = []
for e in filer:
    with e.open("rb") as f:
        dfs.append(pd.read_json(e, lines=True))


df = pd.concat(dfs)
df

,doc_hash,lang,url,domain,date,mimetype,fulltext
0,b5fc6f81d5709f0051da1964c3900e7ca8df65f7,nno,http://lanekassen.no/globalassets/brosjyrer-fe...,lanekassen.no,2022-12-19 01:53:28+00:00,pdf,[Er du flyktning? Du blir rekna som flyktning ...
1,1fbe096fdfdd9916be1313006ac5cf44ac650231,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 01:57:14+00:00,pdf,"[, , Du kan bruke dette skjemaet dersom du tar..."
2,582aaf9a510b3bde21b5b3e13ffc3453d6ca8174,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 01:57:21+00:00,pdf,"[, , Det er viktig at du les informasjonen på ..."
3,32e23cf05e4db850a9e2f622c2edd0482572677e,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 02:00:45+00:00,pdf,[Nynorsk Skjema for lærlinglønn Kor stort bort...
4,4ea46648c7ce59fe0c39b45779ed6402d8b41369,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 02:01:01+00:00,pdf,[Nynorsk Skjema I – artikkelnr. 9001550 – nyno...
...,...,...,...,...,...,...,...
72,e29a43da7165d92d937c56416d50f563201ab5fa,nob,http://lanekassen.no/siteassets/skjemaer-og-fi...,lanekassen.no,2022-12-19 02:50:18+00:00,pdf,"[, , 01.01.2020 Storebrand Bank ASA 70 % Bolig..."
73,c120ee7f582c758ae392b8f90795a7c664c39e90,nob,http://lanekassen.no/siteassets/skjemaer-og-fi...,lanekassen.no,2022-12-19 02:50:23+00:00,pdf,"[, , 06.11.2019 Storebrand Bank ASA 70 % Bolig..."
74,553101a9b0a9fac935cf31e5dd59555d23ecbefe,nob,https://statistikk.lanekassen.no/globalassets/...,lanekassen.no,2022-12-19 03:10:41+00:00,pdf,"[, , Flyktningstipendet Mottakere av flyktning..."
75,1f14c7bcc564613f79be7a8cae1a946e27cfd755,nob,https://statistikk.lanekassen.no/globalassets/...,lanekassen.no,2022-12-19 03:10:44+00:00,pdf,"[, , Tall og fakta om Lånekassens kunder og or..."
76,ad84c32284570d5883b5c12276961d0a74ec1649,nob,https://statistikk.lanekassen.no/globalassets/...,lanekassen.no,2022-12-19 03:10:46+00:00,pdf,[Bruk av studiestøtte blant studenter med innv...

In [2]:
nynorske = df[df.lang == "nno"]
nynorske.index = range(len(nynorske))

bokmålske = df[df.lang == "nob"]
bokmålske.index = range(len(bokmålske))

len(nynorske), len(bokmålske)

(256, 310)

Lim sammen avsnittene i hvert dokument

In [3]:
nynorsk_texts_joined = nynorske.fulltext.apply(lambda x: "\n".join(x))
bokmål_texts_joined = bokmålske.fulltext.apply(lambda x: "\n".join(x))

Last inn fasit

In [4]:
hash_to_i_nn = {e.doc_hash: e.Index for e in nynorske.itertuples()}
hash_to_i_bm = {e.doc_hash: e.Index for e in bokmålske.itertuples()}

fasit = pd.read_csv("lanekassen_fasit.csv")
fasit_set = set(zip(fasit.nynorsk_doc_hash, fasit.bokmål_doc_hash))

def compare_matches_to_fasit(matches):
    nn_i, bm_i = zip(*[(i, match["corpus_id"]) for i, match in matches])
    hash_matches = set(zip(nynorske.iloc[list(nn_i)].doc_hash, bokmålske.iloc[list(bm_i)].doc_hash))

    hits = fasit_set.intersection(hash_matches)
    misses = fasit_set - hash_matches
    
    hits_indices = [(hash_to_i_nn[nn_doc_hash], hash_to_i_bm[bm_doc_hash]) for nn_doc_hash, bm_doc_hash in hits]
    misses_indices = [(hash_to_i_nn[nn_doc_hash], hash_to_i_bm[bm_doc_hash]) for nn_doc_hash, bm_doc_hash in misses]
    
    return (hits_indices, misses_indices)

Last inn modellen

In [5]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('NbAiLab/nb-sbert-base', device="cuda")

# Tell hvor mange dokumenter og avsnitt som er for lange for modellen

In [6]:
max_len = model.max_seq_length
tokenizer = model.tokenizer

nynorsk_documents_token_sequence_lengths = [len(tokenizer.tokenize(text)) for text in nynorsk_texts_joined]

under_max_len = 0
over_max_len = 0
zero_len = 0
for token_len in nynorsk_documents_token_sequence_lengths:
    if token_len:
        if token_len > max_len:
            over_max_len += 1
        else:
            under_max_len += 1
    else:
        zero_len += 1

assert zero_len == 0

print(f"""
Av de {len(nynorsk_documents_token_sequence_lengths)} nynorske dokumentene er:
    {under_max_len} under NB sBERT sin makslengde 
    {over_max_len}  over NB sBERT sin makslengde 
Altså er {round(under_max_len/len(nynorsk_documents_token_sequence_lengths)*100, 2)}% av dokumentene under makslengden 
""")

bokmål_documents_token_sequence_lengths = [len(tokenizer.tokenize(text)) for text in bokmål_texts_joined]

under_max_len = 0
over_max_len = 0
zero_len = 0
for token_len in bokmål_documents_token_sequence_lengths:
    if token_len:
        if token_len > max_len:
            over_max_len += 1
        else:
            under_max_len += 1
    else:
        zero_len += 1

assert zero_len == 0

print(f"""
Av de {len(bokmål_documents_token_sequence_lengths)} dokumentene på bokmål er:
    {under_max_len} under NB sBERT sin makslengde 
    {over_max_len}  over NB sBERT sin makslengde 
Altså er {round(under_max_len/len(bokmål_documents_token_sequence_lengths)*100, 2)}% av dokumentene under makslengden 
""")

Av de 256 nynorske dokumentene er:
    2 under NB sBERT sin makslengde
    254  over NB sBERT sin makslengde
Altså er 0.78% av dokumentene under makslengden


Av de 310 dokumentene på bokmål er:
    1 under NB sBERT sin makslengde
    309  over NB sBERT sin makslengde
Altså er 0.32% av dokumentene under makslengden

In [7]:
max_len = model.max_seq_length
tokenizer = model.tokenizer

token_sequence_lengths = df.fulltext.apply(lambda x: [len(tokenizer.tokenize(e)) for e in x])

under_max_len = 0
over_max_len = 0
zero_len = 0
for e in token_sequence_lengths:
    for token_len in e:
        if token_len:
            if token_len > max_len:
                over_max_len += 1
            else:
                under_max_len += 1
        else:
            zero_len += 1

print(f"""
Det er totalt {sum((under_max_len, over_max_len))} ikke-tomme avsnitt/setninger (og {zero_len} er tomme)
Av de ikke-tomme avsnittene er:
    {under_max_len} under NB sBERT sin makslengde 
    {over_max_len}  over NB sBERT sin makslengde 
Altså er {round(under_max_len/sum((under_max_len, over_max_len))*100, 2)}% av de ikke-tomme avsnittene under makslengden 
""")

Det er totalt 12491 ikke-tomme avsnitt/setninger (og 4377 er tomme)
Av de ikke-tomme avsnittene er:
    8877 under NB sBERT sin makslengde
    3614  over NB sBERT sin makslengde
Altså er 71.07% av de ikke-tomme avsnittene under makslengden

# Dokumentalignment

In [8]:
doc_alignment_results = {}

## Aksepter cut-off
Lim sammen avsnittene i hvert dokument, kjør gjennom sbert

In [9]:
import numpy as np

emb_path = Path("embeddings/nb_sbert/texts_joined.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    bokmål_embeddings = model.encode(bokmål_texts_joined)
    nynorsk_embeddings = model.encode(nynorsk_texts_joined)
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
non_matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] <= threshold]

hits, misses = compare_matches_to_fasit(matches)
doc_alignment_results["naiv_cutoff"] = {"matches": len(matches), "threshold": threshold, "percent of docs": round(len(matches)/len(nynorske)*100, 2), "hits": len(hits), "misses": len(misses)}

### Inspiser matches

In [10]:
from utils import print_matches

print_matches(matches, nynorsk_texts_joined, bokmål_texts_joined)
print_matches(non_matches, nynorsk_texts_joined, bokmål_texts_joined)

Søketekst:
        Er du flyktning? Du blir rekna som flyktning dersom du er utanlandsk statsborgar og har fått vern (asyl) i Noreg. Du må vere registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Noreg som er godkjend f
Match:
        Er du flyktning? Du regnes som flyktning hvis du er utenlandsk statsborger og har fått beskyttelse (asyl) i Norge. Du må være registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Norge som er godkjent
Likhet:
        0.9900512099266052

Indekser:
            Nynorsk/søketekst:  0
            Bokmål/treff:       241
_______________________________________________________________

Søketekst:


Det er viktig at du les informasjonen på side 2 i dette søknadsskjemaet. Hugs å sende inn ein , dersom du ikkje har gjort det.

Denne søknaden lastar du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn

Nam
Match:


Det er viktig at du leser informasjonen på side 2 i dette søknadsskjemaet. Husk å sende inn en , hvis du ikke allerede har gjort det.

Denne søknaden laster du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomna
Likhet:
        0.9849685430526733

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       234
_______________________________________________________________

Søketekst:


Du kan logge inn på og endre kontonummeret ditt dersom du har oppretta ein ny konto som du vil bruke dersom du vil ha pengane inn på ein annan av kontoane dine Lånekassen overfører berre lån og stipend til ein norsk konto som du eig. Dersom du nettopp har fått tildelt eit nytt kontonummer kan det
Match:


Du kan logge inn på og endre kontonummeret ditt hvis du har opprettet en ny konto som du vil bruke hvis du vil ha pengene inn på en annen av kontoene dine Lånekassen overfører bare lån og stipend til en norsk konto som du eier. Hvis du nettopp har fått tildelt et nytt kontonummer kan det ta noen d
Likhet:
        0.9751149415969849

Indekser:
            Nynorsk/søketekst:  6
            Bokmål/treff:       238
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer Poststad

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Eg er kjend med vilkåra for fast rente som eg finn i kapittel 2 i Stad og dato Underskrift Søknaden må vere komme
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer Poststed

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Jeg er kjent med vilkårene for fast rente som jeg finner i kapittel 2 i Sted og dato Underskrift Søknaden må være
Likhet:
        0.9879311323165894

Indekser:
            Nynorsk/søketekst:  7
            Bokmål/treff:       239
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer og poststad Telefon

Etternamnet til fullmaktshavaren Fornamnet og mellomnamnet til fullmaktshavaren Fullmakta er gyldig Frå Til

Stad og dato Underskrifta di

Du kan laste opp fullmaktsskjemaet p
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer og poststed Telefon

Fullmaktshavers etternavn Fullmaktshavers fornavn og mellomnavn Fullmakten er gyldig Fra Til

Sted og dato Din underskrift Du kan laste opp fullmaktsskjemaet på Dine sider ell
Likhet:
        0.9820113182067871

Indekser:
            Nynorsk/søketekst:  8
            Bokmål/treff:       240
_______________________________________________________________

Søketekst:
        Søknaden fortset på neste side

Tilleggsstipend kan bli gitt i tillegg til vanleg utdanningsstøtte og er på inntil 4 000 kroner per månad. Stipendet er meint for søkarar som er i stand til å studere, men som på grunn av nedsett funksjonsevne bruker så mykje tid og krefter på å studere, at dei ikkje
Match:
        Søknaden fortsetter på neste side

Tilleggsstipend kan bli gitt i tillegg til vanlig utdanningsstøtte og er på inntil 4 000 kroner per måned. Stipendet er ment for søkere som er i stand til å studere, men som på grunn av nedsatt funksjonsevne bruker så mye tid og krefter på å studere, at de ikke kan
Likhet:
        0.9817426204681396

Indekser:
            Nynorsk/søketekst:  13
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        Skjemaet fortset på neste side

Søknaden gjeld for søkarar som på grunn av nedsett funksjonsevne ikkje er i stand til å ha lønna arbeid i sommarferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og førebu seg til neste semester. Med lønna arbeid meiner vi alt arbeid der lønna er s
Match:
        Skjemaet fortsetter på neste side

Søknaden gjelder for søkere som på grunn av nedsatt funksjonsevne ikke er i stand til å ha lønnet arbeid i sommerferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og forberede seg til neste semester. Med lønnet arbeid menes alt arbeid hvor lønna
Likhet:
        0.9744488596916199

Indekser:
            Nynorsk/søketekst:  14
            Bokmål/treff:       252
_______________________________________________________________

Søketekst:


Etternamn Fornamn og mellomnamn Fødselsdato (dag – månad – år)

Kva utdanning har eleven teke? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førarkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – månad – år

Oppgi siste dato elev
Match:


Etternavn Fornavn og mellomnavn Fødselsdato (dag – måned – år)

Hvilken utdanning har eleven tatt? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førerkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – måned – år

Oppgi siste dato
Likhet:
        0.988250732421875

Indekser:
            Nynorsk/søketekst:  16
            Bokmål/treff:       255
_______________________________________________________________

Søketekst:
        Søknaden held fram på neste side

,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden
Match:
        Søknaden fortsetter på neste side

,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og do
Likhet:
        0.9957735538482666

Indekser:
            Nynorsk/søketekst:  18
            Bokmål/treff:       258
_______________________________________________________________

Søketekst:


04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 04.05.2022 Din Bank (Spar
Match:


02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 02.03.2022 OBOS-banken AS
Likhet:
        0.9755687117576599

Indekser:
            Nynorsk/søketekst:  19
            Bokmål/treff:       291
_______________________________________________________________

Søketekst:


05.01.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 05.01.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 05.01.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 05.01.2022 OBOS-banken AS Boliglån 50 % 1,82 % 05.01.2022 Sunndal Sparebank B
Match:


02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 02.03.2022 OBOS-banken AS
Likhet:
        0.9824929237365723

Indekser:
            Nynorsk/søketekst:  20
            Bokmål/treff:       291
_______________________________________________________________

Søketekst:


01.09.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 01.09.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 01.09.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 01.09.2021 OBOS-banken AS Boliglån 50 % 1,57 % 01.09.2021 Sunndal Sparebank B
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9722211956977844

Indekser:
            Nynorsk/søketekst:  21
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


05.05.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 05.05.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 05.05.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 05.05.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 05.05.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9549770951271057

Indekser:
            Nynorsk/søketekst:  22
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.976466715335846

Indekser:
            Nynorsk/søketekst:  23
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


06.01.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 06.01.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 06.01.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 06.01.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 06.01.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9638140797615051

Indekser:
            Nynorsk/søketekst:  24
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


04.03.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 04.03.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 04.03.2020 Sbanken ASA Boliglån 50 % 2,75 % 04.03.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 04.03.2020 Nordea Direct Boliglån inntil 50 % 2,91 %

11.03
Match:


06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.202
Likhet:
        0.9628556966781616

Indekser:
            Nynorsk/søketekst:  28
            Bokmål/treff:       303
_______________________________________________________________

Søketekst:
        Kven har ikkje ungdomsrett?
Tek du opp igjen fag, har fullført vidaregåande opplæring tidlegare eller er over 24 år, har du ikkje lenger ungdomsrett. Du kan få stipend og lån frå Lånekassen, men etter dei same reglane som for høgare utdanning.
Match:
        Hvem har ikke ungdomsrett?
Tar du opp fag, har fullført tre år på videregående tidligere eller er over 24 år, har du ikke lenger ungdomsrett. Du kan få stipend og lån fra Lånekassen, men etter de samme reglene som for høyere utdanning.
Likhet:
        0.9651800990104675

Indekser:
            Nynorsk/søketekst:  35
            Bokmål/treff:       1
_______________________________________________________________

Søketekst:
        Fagskole
Fagskole
Fagskoleutdanning
Du kan få lån og stipend til fagskoleutdanningar som er godkjende av NOKUT.
Dersom du er usikker på om utdanninga di er godkjent for lån og stipend frå Lånekassen, kan du kontakte oss eller sjå NOKUT si oversikt over godkjende fagskoletilbod.
Alle studentar får ba
Match:
        Fagskole
Fagskole
Fagskoleutdanning
Du kan få lån og stipend til fagskoleutdanninger som er godkjent av NOKUT.
Hvis du er usikker på om utdanningen din er godkjent for lån og stipend fra Lånekassen, kan du spørre oss direkte eller se i NOKUT sin oversikt over akkrediterte fagskoletilbud.
Alle studen
Likhet:
        0.969484806060791

Indekser:
            Nynorsk/søketekst:  36
            Bokmål/treff:       2
_______________________________________________________________

Søketekst:
        Lån og stipend for å gå på folkehøgskole
Er du elev på ein folkehøgskole, kan du få basislån i inntil ti månader.
Kva er basislån?
Basislån er det alle studentar kan få, og er namnet på det dei fleste kallar studielån. Du får ikkje ekstra lån til å dekke utgiftene ved linja du skal gå på, eller til
Match:
        Lån og stipend for å gå på folkehøgskole
Er du elev på en folkehøgskole, kan du få basislån i inntil ti måneder.
Hva er basislån?
Basislån er det alle studenter kan få, og er navnet på det de fleste kaller studielån. Du får ikke ekstra lån til å dekke utgiftene ved linjen du skal gå på, eller til re
Likhet:
        0.9924557209014893

Indekser:
            Nynorsk/søketekst:  37
            Bokmål/treff:       3
_______________________________________________________________

Søketekst:
        Bibel- eller kunstskole
Elever på bibelskole eller kunstskole kan få lån og stipend i inntil ti måneder
Bibelskole eller kunstskole er to ulike skoler. Går du på bibelskole eller kunstskole, får du ikkje lenger stipend slik du kanskje fekk på vidaregåande, men du får eit lån.
Du kan få eit basislån
Match:
        Bibel- eller kunstskole
Elever på bibelskole eller kunstskole kan få stipend og lån i inntil ti måneder
Bibelskole eller kunstskoler er to ulike typer skoler. Går du på bibelskole eller kunstskole, får du ikke lenger stipend slik du kanskje fikk på videregående, men du får et lån.
Du kan få et basis
Likhet:
        0.9957024455070496

Indekser:
            Nynorsk/søketekst:  38
            Bokmål/treff:       4
_______________________________________________________________

Søketekst:
        Du kan ikkje få lån og stipend dersom du berre skal ta førarkort.
Du kan berre få stipend og lån til førarkort dersom du tar det i samband med grunnutdanninga. Du må starte på, eller ta førerkortet innen tolv måneder før grunnutdanningen starter.
Du kan få skolepengelån til å dekke utgiftene til kur
Match:
        Du kan ikke få lån og stipend hvis du bare skal ta førerkort.
Du kan bare få stipend og lån til førerkort hvis du tar det i forbindelse med grunnutdanningen. Du må starte på, eller ta førerkortet innen tolv måneder før grunnutdanningen starter.
Du kan få skolepengelån til å dekke utgiftene til kurse
Likhet:
        0.975279688835144

Indekser:
            Nynorsk/søketekst:  39
            Bokmål/treff:       5
_______________________________________________________________

Søketekst:
        Lån og stipend til sommarkurs
Til enkelte sommarkurs kan du få lån og stipend.
Basislån i inntil 2 månader
Du kan få basislån i inntil 2 månader for å ta sommarkurs. Basislån er det alle studentar kan få, og det dei fleste kallar studielån. Sommaren 2022 er basislånet 11 487 kroner per månad, og du
Match:
        Lån og stipend til sommerkurs
Til enkelte sommerkurs kan du få lån og stipend.
Basislån i inntil 2 måneder
Du kan få basislån i inntil 2 måneder for å ta sommerkurs. Basislån er det alle studenter kan få, og det de fleste kaller studielån. Sommeren 2022 er basislånet 11 487 kroner per måned, og du k
Likhet:
        0.965825617313385

Indekser:
            Nynorsk/søketekst:  40
            Bokmål/treff:       6
_______________________________________________________________

Søketekst:
        Forseinking, avbrot og endring i utdanninga
60 sp
før det påverkar retten til lån og stipend
Når du stryk på eksamen
Stryk du på eksamen, blir du fagleg forseinka. Det kan påverke om du har rett til lån og stipend seinare, og kor mykje lån du får gjort om til stipend.
Eitt års fulltidsutdanning tils
Match:
        Forsinkelse, avbrudd og endring i utdanningen
60 sp
før det påvirker retten til lån og stipend
Når du stryker på eksamen
Hvis du stryker på eksamen, blir du faglig forsinket. Det kan påvirke om du har rett til lån og stipend senere, og hvor mye lån du får gjort om til stipend.
Ett års fulltidsutdann
Likhet:
        0.9694219827651978

Indekser:
            Nynorsk/søketekst:  44
            Bokmål/treff:       12
_______________________________________________________________

Søketekst:
        Nedsett funksjonsevne
Informasjonen nedanfor gjeld ikkje for deg i vanleg vidaregåande opplæring med ungdomsrett.
Tilleggsstipend
Dersom du har nedsett funksjonsevne og derfor ikkje kan jobbe ved sidan av studia, kan du få eit tilleggsstipend (kalt ekstrastipend tidlegare) . Du kan søke om sommarstø
Match:
        Nedsatt funksjonsevne
Informasjonen nedenfor gjelder ikke for deg i vanlig videregående opplæring med ungdomsrett.
Tilleggsstipend
Hvis du har nedsatt funksjonsevne og derfor ikke kan jobbe ved siden av studiene, kan du få et tilleggsstipend (tidligere kalt ekstrastipend).
Stipendet er på 4 000 kron
Likhet:
        0.9813895225524902

Indekser:
            Nynorsk/søketekst:  45
            Bokmål/treff:       13
_______________________________________________________________

Søketekst:
        Tilleggslån
104 340
i året
Tilleggslån for deg som er 30 år eller eldre
Du kan få tilleggslån dersom du tar universitets- eller høgskoleutdanning, fagskole eller vidaregåande skole, og er 30 år eller eldre.
Tilleggslånet på 104 340 er berre for studentar på fagskole, universitets- eller høgskoleutda
Match:
        Tilleggslån
104 340
i året
Tilleggslån for deg som er 30 år eller eldre
Du kan få tilleggslån hvis du tar universitets- eller høgskoleutdanning, fagskole eller videregående skole, og er 30 år eller eldre.
Tilleggslånet på 104 340 er bare for studenter på fagskole, universitets- eller høgskoleutdanni
Likhet:
        0.9879132509231567

Indekser:

#### Falsk positiv
Eksempel på en falsk positiv.  
Noen lister av datoer og banker og renter blir veldig like (similarity score er ~0.98)

In [11]:
i = 19 
print(search_result[i])
print(nynorsk_texts_joined[i][:250])
print("\n___________\n")
print(bokmål_texts_joined[search_result[i][0]["corpus_id"]][:250])

[{'corpus_id': 291, 'score': 0.9755687117576599}]


04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank B

___________



02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Bolig

## Del opp avsnittene i biter mindre enn modellens makslengde og aggreger

In [12]:
from utils import tokenize_and_split_text

nynorsk_maxlen_parts = [tokenize_and_split_text(text, tokenizer=model.tokenizer, model_max_len=model.max_seq_length) for text in nynorsk_texts_joined]
bokmål_maxlen_parts = [tokenize_and_split_text(text, tokenizer=model.tokenizer, model_max_len=model.max_seq_length) for text in bokmål_texts_joined]

In [13]:
# from collections import Counter 
# pd.DataFrame(Counter([len(e) for e in nynorsk_maxlen_parts]).most_common(), columns=("antall lister", "antall dokumenter")).sort_values("antall lister")
# pd.DataFrame(Counter([len(e) for e in bokmål_maxlen_parts]).most_common(), columns=("antall lister", "antall dokumenter")).sort_values("antall lister")

## Bare send alle bitene gjennom

SentenceTransformers aggregerer ved å ta de to første tekstene i hver liste av tekster, og lage en vektor hvor hver halvdel er starten av hver av tekstene (fra starten og opp til 1/2 makslengde) adskilt med et sep-token

In [14]:
emb_path = Path("embeddings/nb_sbert/maxlen_parts.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_maxlen_parts_1 = [e + [""] for e in nynorsk_maxlen_parts]
    bokmål_maxlen_parts_1 = [e + [""] for e in bokmål_maxlen_parts]

    bokmål_embeddings = model.encode(bokmål_maxlen_parts_1)
    nynorsk_embeddings = model.encode(nynorsk_maxlen_parts_1)
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
non_matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] <= threshold]

hits, misses = compare_matches_to_fasit(matches)
doc_alignment_results["naiv_cutoff_biter"] = {"matches": len(matches), "threshold": threshold, "percent of docs": round(len(matches)/len(nynorske)*100, 2), "hits": len(hits), "misses": len(misses)}

### Inspiser matches

In [15]:
print_matches(matches, nynorsk_texts_joined, bokmål_texts_joined)
# print_matches(non_matches, nynorsk_texts_joined, bokmål_texts_joined)

Søketekst:
        Er du flyktning? Du blir rekna som flyktning dersom du er utanlandsk statsborgar og har fått vern (asyl) i Noreg. Du må vere registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Noreg som er godkjend f
Match:
        Er du flyktning? Du regnes som flyktning hvis du er utenlandsk statsborger og har fått beskyttelse (asyl) i Norge. Du må være registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Norge som er godkjent
Likhet:
        0.9803029894828796

Indekser:
            Nynorsk/søketekst:  0
            Bokmål/treff:       241
_______________________________________________________________

Søketekst:


Det er viktig at du les informasjonen på side 2 i dette søknadsskjemaet. Hugs å sende inn ein , dersom du ikkje har gjort det.

Denne søknaden lastar du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn

Nam
Match:


Det er viktig at du leser informasjonen på side 2 i dette søknadsskjemaet. Husk å sende inn en , hvis du ikke allerede har gjort det.

Denne søknaden laster du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomna
Likhet:
        0.961379885673523

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       234
_______________________________________________________________

Søketekst:
        Nynorsk Skjema for lærlinglønn Kor stort bortebuarstipend du kan få, er avhengig av kor mykje du tener som lærling. Derfor må arbeidsgivaren din fylle ut dette skjemaet for å stadfeste lønna di. Vi kan ikkje behandle søknaden din før du har sendt opplysningar om lønna di. Du kan laste opp ferdig utf
Match:
        Bokmål Skjema for lærlinglønn Hvor stort borteboerstipend du kan få, er avhengig av hvor mye du tjener som lærling. Derfor må arbeidsgiveren din fylle ut dette skjemaet for å bekrefte lønnen din. Vi kan ikke behandle søknaden din før du har sendt opplysninger om lønnen din. Du kan laste opp ferdig u
Likhet:
        0.9651823043823242

Indekser:
            Nynorsk/søketekst:  3
            Bokmål/treff:       235
_______________________________________________________________

Søketekst:


Du kan logge inn på og endre kontonummeret ditt dersom du har oppretta ein ny konto som du vil bruke dersom du vil ha pengane inn på ein annan av kontoane dine Lånekassen overfører berre lån og stipend til ein norsk konto som du eig. Dersom du nettopp har fått tildelt eit nytt kontonummer kan det
Match:


Du kan logge inn på og endre kontonummeret ditt hvis du har opprettet en ny konto som du vil bruke hvis du vil ha pengene inn på en annen av kontoene dine Lånekassen overfører bare lån og stipend til en norsk konto som du eier. Hvis du nettopp har fått tildelt et nytt kontonummer kan det ta noen d
Likhet:
        0.9680615663528442

Indekser:
            Nynorsk/søketekst:  6
            Bokmål/treff:       238
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer Poststad

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Eg er kjend med vilkåra for fast rente som eg finn i kapittel 2 i Stad og dato Underskrift Søknaden må vere komme
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer Poststed

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Jeg er kjent med vilkårene for fast rente som jeg finner i kapittel 2 i Sted og dato Underskrift Søknaden må være
Likhet:
        0.9635418653488159

Indekser:
            Nynorsk/søketekst:  7
            Bokmål/treff:       239
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer og poststad Telefon

Etternamnet til fullmaktshavaren Fornamnet og mellomnamnet til fullmaktshavaren Fullmakta er gyldig Frå Til

Stad og dato Underskrifta di

Du kan laste opp fullmaktsskjemaet p
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer og poststed Telefon

Fullmaktshavers etternavn Fullmaktshavers fornavn og mellomnavn Fullmakten er gyldig Fra Til

Sted og dato Din underskrift Du kan laste opp fullmaktsskjemaet på Dine sider ell
Likhet:
        0.9677414894104004

Indekser:
            Nynorsk/søketekst:  8
            Bokmål/treff:       240
_______________________________________________________________

Søketekst:
        Søknaden fortset på neste side

Tilleggsstipend kan bli gitt i tillegg til vanleg utdanningsstøtte og er på inntil 4 000 kroner per månad. Stipendet er meint for søkarar som er i stand til å studere, men som på grunn av nedsett funksjonsevne bruker så mykje tid og krefter på å studere, at dei ikkje
Match:
        Søknaden fortsetter på neste side

Tilleggsstipend kan bli gitt i tillegg til vanlig utdanningsstøtte og er på inntil 4 000 kroner per måned. Stipendet er ment for søkere som er i stand til å studere, men som på grunn av nedsatt funksjonsevne bruker så mye tid og krefter på å studere, at de ikke kan
Likhet:
        0.9728199243545532

Indekser:
            Nynorsk/søketekst:  13
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        Skjemaet fortset på neste side

Søknaden gjeld for søkarar som på grunn av nedsett funksjonsevne ikkje er i stand til å ha lønna arbeid i sommarferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og førebu seg til neste semester. Med lønna arbeid meiner vi alt arbeid der lønna er s
Match:
        Skjemaet fortsetter på neste side

Søknaden gjelder for søkere som på grunn av nedsatt funksjonsevne ikke er i stand til å ha lønnet arbeid i sommerferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og forberede seg til neste semester. Med lønnet arbeid menes alt arbeid hvor lønna
Likhet:
        0.9595788717269897

Indekser:
            Nynorsk/søketekst:  14
            Bokmål/treff:       252
_______________________________________________________________

Søketekst:


Etternamn Fornamn og mellomnamn Fødselsdato (dag – månad – år)

Kva utdanning har eleven teke? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førarkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – månad – år

Oppgi siste dato elev
Match:


Etternavn Fornavn og mellomnavn Fødselsdato (dag – måned – år)

Hvilken utdanning har eleven tatt? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førerkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – måned – år

Oppgi siste dato
Likhet:
        0.988027811050415

Indekser:
            Nynorsk/søketekst:  16
            Bokmål/treff:       255
_______________________________________________________________

Søketekst:
        Søknaden held fram på neste side

,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden
Match:
        Søknaden fortsetter på neste side

,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og do
Likhet:
        0.9936760067939758

Indekser:
            Nynorsk/søketekst:  18
            Bokmål/treff:       258
_______________________________________________________________

Søketekst:


05.01.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 05.01.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 05.01.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 05.01.2022 OBOS-banken AS Boliglån 50 % 1,82 % 05.01.2022 Sunndal Sparebank B
Match:


02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 02.03.2022 OBOS-banken AS
Likhet:
        0.9730126857757568

Indekser:
            Nynorsk/søketekst:  20
            Bokmål/treff:       291
_______________________________________________________________

Søketekst:


05.05.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 05.05.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 05.05.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 05.05.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 05.05.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9541565179824829

Indekser:
            Nynorsk/søketekst:  22
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9592909812927246

Indekser:
            Nynorsk/søketekst:  23
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


06.01.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 06.01.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 06.01.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 06.01.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 06.01.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9566962122917175

Indekser:
            Nynorsk/søketekst:  24
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


04.11.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 04.11.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 04.11.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 04.11.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 04.11.2020 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9524717330932617

Indekser:
            Nynorsk/søketekst:  25
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


04.03.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 04.03.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 04.03.2020 Sbanken ASA Boliglån 50 % 2,75 % 04.03.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 04.03.2020 Nordea Direct Boliglån inntil 50 % 2,91 %

11.03
Match:


06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.202
Likhet:
        0.9698193073272705

Indekser:
            Nynorsk/søketekst:  28
            Bokmål/treff:       303
_______________________________________________________________

Søketekst:
        Kven har ikkje ungdomsrett?
Tek du opp igjen fag, har fullført vidaregåande opplæring tidlegare eller er over 24 år, har du ikkje lenger ungdomsrett. Du kan få stipend og lån frå Lånekassen, men etter dei same reglane som for høgare utdanning.
Match:
        Hvem har ikke ungdomsrett?
Tar du opp fag, har fullført tre år på videregående tidligere eller er over 24 år, har du ikke lenger ungdomsrett. Du kan få stipend og lån fra Lånekassen, men etter de samme reglene som for høyere utdanning.
Likhet:
        0.9630500078201294

Indekser:
            Nynorsk/søketekst:  35
            Bokmål/treff:       1
_______________________________________________________________

Søketekst:
        Fagskole
Fagskole
Fagskoleutdanning
Du kan få lån og stipend til fagskoleutdanningar som er godkjende av NOKUT.
Dersom du er usikker på om utdanninga di er godkjent for lån og stipend frå Lånekassen, kan du kontakte oss eller sjå NOKUT si oversikt over godkjende fagskoletilbod.
Alle studentar får ba
Match:
        Fagskole
Fagskole
Fagskoleutdanning
Du kan få lån og stipend til fagskoleutdanninger som er godkjent av NOKUT.
Hvis du er usikker på om utdanningen din er godkjent for lån og stipend fra Lånekassen, kan du spørre oss direkte eller se i NOKUT sin oversikt over akkrediterte fagskoletilbud.
Alle studen
Likhet:
        0.981545090675354

Indekser:
            Nynorsk/søketekst:  36
            Bokmål/treff:       2
_______________________________________________________________

Søketekst:
        Lån og stipend for å gå på folkehøgskole
Er du elev på ein folkehøgskole, kan du få basislån i inntil ti månader.
Kva er basislån?
Basislån er det alle studentar kan få, og er namnet på det dei fleste kallar studielån. Du får ikkje ekstra lån til å dekke utgiftene ved linja du skal gå på, eller til
Match:
        Lån og stipend for å gå på folkehøgskole
Er du elev på en folkehøgskole, kan du få basislån i inntil ti måneder.
Hva er basislån?
Basislån er det alle studenter kan få, og er navnet på det de fleste kaller studielån. Du får ikke ekstra lån til å dekke utgiftene ved linjen du skal gå på, eller til re
Likhet:
        0.9815951585769653

Indekser:
            Nynorsk/søketekst:  37
            Bokmål/treff:       3
_______________________________________________________________

Søketekst:
        Bibel- eller kunstskole
Elever på bibelskole eller kunstskole kan få lån og stipend i inntil ti måneder
Bibelskole eller kunstskole er to ulike skoler. Går du på bibelskole eller kunstskole, får du ikkje lenger stipend slik du kanskje fekk på vidaregåande, men du får eit lån.
Du kan få eit basislån
Match:
        Bibel- eller kunstskole
Elever på bibelskole eller kunstskole kan få stipend og lån i inntil ti måneder
Bibelskole eller kunstskoler er to ulike typer skoler. Går du på bibelskole eller kunstskole, får du ikke lenger stipend slik du kanskje fikk på videregående, men du får et lån.
Du kan få et basis
Likhet:
        0.9959347248077393

Indekser:
            Nynorsk/søketekst:  38
            Bokmål/treff:       4
_______________________________________________________________

Søketekst:
        Du kan ikkje få lån og stipend dersom du berre skal ta førarkort.
Du kan berre få stipend og lån til førarkort dersom du tar det i samband med grunnutdanninga. Du må starte på, eller ta førerkortet innen tolv måneder før grunnutdanningen starter.
Du kan få skolepengelån til å dekke utgiftene til kur
Match:
        Du kan ikke få lån og stipend hvis du bare skal ta førerkort.
Du kan bare få stipend og lån til førerkort hvis du tar det i forbindelse med grunnutdanningen. Du må starte på, eller ta førerkortet innen tolv måneder før grunnutdanningen starter.
Du kan få skolepengelån til å dekke utgiftene til kurse
Likhet:
        0.9684646129608154

Indekser:
            Nynorsk/søketekst:  39
            Bokmål/treff:       5
_______________________________________________________________

Søketekst:
        Lån og stipend til sommarkurs
Til enkelte sommarkurs kan du få lån og stipend.
Basislån i inntil 2 månader
Du kan få basislån i inntil 2 månader for å ta sommarkurs. Basislån er det alle studentar kan få, og det dei fleste kallar studielån. Sommaren 2022 er basislånet 11 487 kroner per månad, og du
Match:
        Lån og stipend til sommerkurs
Til enkelte sommerkurs kan du få lån og stipend.
Basislån i inntil 2 måneder
Du kan få basislån i inntil 2 måneder for å ta sommerkurs. Basislån er det alle studenter kan få, og det de fleste kaller studielån. Sommeren 2022 er basislånet 11 487 kroner per måned, og du k
Likhet:
        0.9770387411117554

Indekser:
            Nynorsk/søketekst:  40
            Bokmål/treff:       6
_______________________________________________________________

Søketekst:
        Forseinking, avbrot og endring i utdanninga
60 sp
før det påverkar retten til lån og stipend
Når du stryk på eksamen
Stryk du på eksamen, blir du fagleg forseinka. Det kan påverke om du har rett til lån og stipend seinare, og kor mykje lån du får gjort om til stipend.
Eitt års fulltidsutdanning tils
Match:
        Forsinkelse, avbrudd og endring i utdanningen
60 sp
før det påvirker retten til lån og stipend
Når du stryker på eksamen
Hvis du stryker på eksamen, blir du faglig forsinket. Det kan påvirke om du har rett til lån og stipend senere, og hvor mye lån du får gjort om til stipend.
Ett års fulltidsutdann
Likhet:
        0.9601253271102905

Indekser:
            Nynorsk/søketekst:  44
            Bokmål/treff:       12
_______________________________________________________________

Søketekst:
        Tilleggslån
104 340
i året
Tilleggslån for deg som er 30 år eller eldre
Du kan få tilleggslån dersom du tar universitets- eller høgskoleutdanning, fagskole eller vidaregåande skole, og er 30 år eller eldre.
Tilleggslånet på 104 340 er berre for studentar på fagskole, universitets- eller høgskoleutda
Match:
        Tilleggslån
104 340
i året
Tilleggslån for deg som er 30 år eller eldre
Du kan få tilleggslån hvis du tar universitets- eller høgskoleutdanning, fagskole eller videregående skole, og er 30 år eller eldre.
Tilleggslånet på 104 340 er bare for studenter på fagskole, universitets- eller høgskoleutdanni
Likhet:
        0.9924427270889282

Indekser:
            Nynorsk/søketekst:  46
            Bokmål/treff:       14
_______________________________________________________________

Søketekst:
        Du kan få skolepengelån i normert tid for resten av utdanninga di, dersom du begynte på ei gradsutdanning på nett i Storbritannia før 2021
Lærestaden må vere godkjende for støtte frå Lånekassen
Nettstudium på ein norsk lærestad
Du kan få lån og stipend etter dei same reglane som elevar og studentar
Match:
        Du kan få skolepengelån i normert tid for resten av utdanningen din, hvis du begynte på en gradsutdanning på nett i Storbritannia før 2021
Lærestedet må være godkjent for støtte i Lånekassen
Nettstudier på et norsk lærested
Du kan få lån og stipend etter de samme reglene som elever og studenter som
Likhet:
        0.9778319597244263

Indekser:

#### Falsk positiv
Samme som over

In [16]:
i = 22
print(search_result[i])
print(nynorsk_texts_joined[i][:250])
print("\n___________\n")
print(bokmål_texts_joined[search_result[i][0]["corpus_id"]][:250])

[{'corpus_id': 293, 'score': 0.9541565179824829}]


05.05.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 05.05.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 05.05.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 05.05.2021 Sunndal Spareban

___________



03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Spareban

## Aggreger setningsvektorene: Mean pooling

In [17]:
import numpy as np 

emb_path = Path("embeddings/nb_sbert/maxlen_parts_mean_pooling.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_embeddings = np.array([np.mean(model.encode(text_parts), axis=0) for text_parts in nynorsk_maxlen_parts])
    bokmål_embeddings = np.array([np.mean(model.encode(text_parts), axis=0) for text_parts in bokmål_maxlen_parts])
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
non_matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] <= threshold]

hits, misses = compare_matches_to_fasit(matches)

doc_alignment_results["mean_pooling_biter"] = {"matches": len(matches), "threshold": threshold, "percent of docs": round(len(matches)/len(nynorske)*100, 2), "hits": len(hits), "misses": len(misses)}

### Inspiser matches

In [18]:
print_matches(matches, nynorsk_texts_joined, bokmål_texts_joined)

Søketekst:
        Er du flyktning? Du blir rekna som flyktning dersom du er utanlandsk statsborgar og har fått vern (asyl) i Noreg. Du må vere registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Noreg som er godkjend f
Match:
        Er du flyktning? Du regnes som flyktning hvis du er utenlandsk statsborger og har fått beskyttelse (asyl) i Norge. Du må være registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Norge som er godkjent
Likhet:
        0.9855220317840576

Indekser:
            Nynorsk/søketekst:  0
            Bokmål/treff:       241
_______________________________________________________________

Søketekst:


Du kan bruke dette skjemaet dersom du tar høgare utdanning eller fagskoleutdanning i Noreg eller Norden, og du skal søke om støtte til studieopphald i eit anna land.

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn

Kva studieprogram følger du i Noreg/Norden? I k
Match:


Du kan bruke dette skjemaet hvis du tar høyere utdanning eller fagskoleutdanning i Norge eller Norden, og du skal søke om støtte til studieopphold i et annet land.

Skjemaet laster du opp på Dine Sider, eller du kan sende det i posten til Lånekassen behandler personopplysninger i samsvar med regel
Likhet:
        0.9844638109207153

Indekser:
            Nynorsk/søketekst:  1
            Bokmål/treff:       233
_______________________________________________________________

Søketekst:


Det er viktig at du les informasjonen på side 2 i dette søknadsskjemaet. Hugs å sende inn ein , dersom du ikkje har gjort det.

Denne søknaden lastar du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn

Nam
Match:


Det er viktig at du leser informasjonen på side 2 i dette søknadsskjemaet. Husk å sende inn en , hvis du ikke allerede har gjort det.

Denne søknaden laster du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomna
Likhet:
        0.9859692454338074

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       234
_______________________________________________________________

Søketekst:
        Nynorsk Skjema for lærlinglønn Kor stort bortebuarstipend du kan få, er avhengig av kor mykje du tener som lærling. Derfor må arbeidsgivaren din fylle ut dette skjemaet for å stadfeste lønna di. Vi kan ikkje behandle søknaden din før du har sendt opplysningar om lønna di. Du kan laste opp ferdig utf
Match:
        Bokmål Skjema for lærlinglønn Hvor stort borteboerstipend du kan få, er avhengig av hvor mye du tjener som lærling. Derfor må arbeidsgiveren din fylle ut dette skjemaet for å bekrefte lønnen din. Vi kan ikke behandle søknaden din før du har sendt opplysninger om lønnen din. Du kan laste opp ferdig u
Likhet:
        0.9807993173599243

Indekser:
            Nynorsk/søketekst:  3
            Bokmål/treff:       235
_______________________________________________________________

Søketekst:
        Nynorsk Skjema I – artikkelnr. 9001550 – nynorsk – 01.2022 – organisasjonsnummer NO 960 885 406 Namn, adresse og postnummer/-stad Personnummer Fødselsdato Kundenummer i Lånekassen Søknad om betalingsutsetting og/eller sletting av renter Du kan bruke nettsøknaden på

Kva månad/månader søker du om uts
Match:
        Bokmål Skjema I – artikkelnr. 9001550 – bokmål – 01.2022 – organisasjonsnummer NO 960 885 406 Navn, adresse og postnummer/-sted Personnummer Fødselsdato Kundenummer i Lånekassen Søknad om betalingsutsettelse og/eller sletting av renter Du kan bruke nettsøknaden på

Hvilken måned / hvilke måneder søk
Likhet:
        0.9658609628677368

Indekser:
            Nynorsk/søketekst:  4
            Bokmål/treff:       237
_______________________________________________________________

Søketekst:
        Nynorsk Eg stadfester at eg har lese vilkåra på side 2.

Oppgi perioden du søker om sletting av gjeld for

År Månad Dag Frå Til Punkt 4 skal berre fyllast ut dersom du søker om sletting av gjeld på grunn av omsorg. Arbeidstakar Sjølvstendig næringsdrivande Dato og underskrift

Adressa til arbeidsgiv
Match:
        Bokmål Ordningen gjelder for låntakere som er bosatt og yrkesaktive i Finnmark og i disse kommunene i Nord-Troms: Lyngen, Storfjord, Kåfjord, Skjervøy, Nordreisa, Kvænangen og Karlsøy. Ordningen omfatter også yrkesaktive leger i andre utvalgte kommuner. Vi henter informasjon om bosted fra Folkeregis
Likhet:
        0.968889594078064

Indekser:
            Nynorsk/søketekst:  5
            Bokmål/treff:       236
_______________________________________________________________

Søketekst:


Du kan logge inn på og endre kontonummeret ditt dersom du har oppretta ein ny konto som du vil bruke dersom du vil ha pengane inn på ein annan av kontoane dine Lånekassen overfører berre lån og stipend til ein norsk konto som du eig. Dersom du nettopp har fått tildelt eit nytt kontonummer kan det
Match:


Du kan logge inn på og endre kontonummeret ditt hvis du har opprettet en ny konto som du vil bruke hvis du vil ha pengene inn på en annen av kontoene dine Lånekassen overfører bare lån og stipend til en norsk konto som du eier. Hvis du nettopp har fått tildelt et nytt kontonummer kan det ta noen d
Likhet:
        0.9717469811439514

Indekser:
            Nynorsk/søketekst:  6
            Bokmål/treff:       238
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer Poststad

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Eg er kjend med vilkåra for fast rente som eg finn i kapittel 2 i Stad og dato Underskrift Søknaden må vere komme
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer Poststed

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Jeg er kjent med vilkårene for fast rente som jeg finner i kapittel 2 i Sted og dato Underskrift Søknaden må være
Likhet:
        0.980337917804718

Indekser:
            Nynorsk/søketekst:  7
            Bokmål/treff:       239
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer og poststad Telefon

Etternamnet til fullmaktshavaren Fornamnet og mellomnamnet til fullmaktshavaren Fullmakta er gyldig Frå Til

Stad og dato Underskrifta di

Du kan laste opp fullmaktsskjemaet p
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer og poststed Telefon

Fullmaktshavers etternavn Fullmaktshavers fornavn og mellomnavn Fullmakten er gyldig Fra Til

Sted og dato Din underskrift Du kan laste opp fullmaktsskjemaet på Dine sider ell
Likhet:
        0.9834393262863159

Indekser:
            Nynorsk/søketekst:  8
            Bokmål/treff:       240
_______________________________________________________________

Søketekst:
        Du finn informasjon om vilkår og dokumentasjon på neste side. Søknad om sjukestipend Nynorsk Skjema S – artikkelnummer 9001561 – nynorsk – 06.2022 – Organisasjonsnummer NO 960 885 406 Namn, adresse og postnummer/-stad Personnummer Fødselsdato Kundenummer i Lånekassen

Eigen sjukdom Sjukt barn Barnet
Match:
        Du finner informasjon om vilkår og dokumentasjon på neste side. Søknad om sykestipend Bokmål Skjema S – artikkelnummer 9001561 – bokmål – 06.2022– Organisasjonsnummer NO 960 885 406 Navn, adresse og postnummer/-sted Personnummer Fødselsdato Kundenummer i Lånekassen

Egen sykdom Sykt barn Barnets fød
Likhet:
        0.9681345224380493

Indekser:
            Nynorsk/søketekst:  12
            Bokmål/treff:       250
_______________________________________________________________

Søketekst:
        Søknaden fortset på neste side

Tilleggsstipend kan bli gitt i tillegg til vanleg utdanningsstøtte og er på inntil 4 000 kroner per månad. Stipendet er meint for søkarar som er i stand til å studere, men som på grunn av nedsett funksjonsevne bruker så mykje tid og krefter på å studere, at dei ikkje
Match:
        Søknaden fortsetter på neste side

Tilleggsstipend kan bli gitt i tillegg til vanlig utdanningsstøtte og er på inntil 4 000 kroner per måned. Stipendet er ment for søkere som er i stand til å studere, men som på grunn av nedsatt funksjonsevne bruker så mye tid og krefter på å studere, at de ikke kan
Likhet:
        0.9695099592208862

Indekser:
            Nynorsk/søketekst:  13
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        Skjemaet fortset på neste side

Søknaden gjeld for søkarar som på grunn av nedsett funksjonsevne ikkje er i stand til å ha lønna arbeid i sommarferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og førebu seg til neste semester. Med lønna arbeid meiner vi alt arbeid der lønna er s
Match:
        Skjemaet fortsetter på neste side

Søknaden gjelder for søkere som på grunn av nedsatt funksjonsevne ikke er i stand til å ha lønnet arbeid i sommerferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og forberede seg til neste semester. Med lønnet arbeid menes alt arbeid hvor lønna
Likhet:
        0.9584490060806274

Indekser:
            Nynorsk/søketekst:  14
            Bokmål/treff:       252
_______________________________________________________________

Søketekst:
        Sletting av gjeld for lærarar i grunnskolen Nynorsk Skjema2 Namn Oppteningsperiode frå og med dato

Oppteningsperiode til og med dato Frå 2020 er Finnmark og Troms slått saman til det nye fylket Troms og Finnmark, men det påverkar ikkje ordninga med sletting av gjeld. For å få sletta gjeld må du fra
Match:
        Sletting av gjeld for lærere i grunnskolen Bokmål Skjema L – Bokmål – 02

Fra 2020 er Finnmark og Troms slått sammen til det nye fylket Troms og Finnmark, men det påvirker ikke ordningen med sletting av gjeld. For å få slettet gjeld må du fortsatt arbeide i det som tidligere var regionen Finnmark og
Likhet:
        0.9698466062545776

Indekser:
            Nynorsk/søketekst:  15
            Bokmål/treff:       254
_______________________________________________________________

Søketekst:


Etternamn Fornamn og mellomnamn Fødselsdato (dag – månad – år)

Kva utdanning har eleven teke? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førarkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – månad – år

Oppgi siste dato elev
Match:


Etternavn Fornavn og mellomnavn Fødselsdato (dag – måned – år)

Hvilken utdanning har eleven tatt? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førerkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – måned – år

Oppgi siste dato
Likhet:
        0.9895660877227783

Indekser:
            Nynorsk/søketekst:  16
            Bokmål/treff:       255
_______________________________________________________________

Søketekst:
        Søknaden held fram på neste side

,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden
Match:
        Søknaden fortsetter på neste side

,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og do
Likhet:
        0.9754860401153564

Indekser:
            Nynorsk/søketekst:  18
            Bokmål/treff:       258
_______________________________________________________________

Søketekst:


04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 04.05.2022 Din Bank (Spar
Match:


02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 02.03.2022 OBOS-banken AS
Likhet:
        0.9914844036102295

Indekser:
            Nynorsk/søketekst:  19
            Bokmål/treff:       291
_______________________________________________________________

Søketekst:


05.01.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 05.01.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 05.01.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 05.01.2022 OBOS-banken AS Boliglån 50 % 1,82 % 05.01.2022 Sunndal Sparebank B
Match:


02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 02.03.2022 OBOS-banken AS
Likhet:
        0.992565393447876

Indekser:
            Nynorsk/søketekst:  20
            Bokmål/treff:       291
_______________________________________________________________

Søketekst:


01.09.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 01.09.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 01.09.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 01.09.2021 OBOS-banken AS Boliglån 50 % 1,57 % 01.09.2021 Sunndal Sparebank B
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9801101684570312

Indekser:
            Nynorsk/søketekst:  21
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


05.05.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 05.05.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 05.05.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 05.05.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 05.05.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9782202243804932

Indekser:
            Nynorsk/søketekst:  22
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9759193658828735

Indekser:
            Nynorsk/søketekst:  23
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


06.01.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 06.01.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 06.01.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 06.01.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 06.01.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9807298183441162

Indekser:
            Nynorsk/søketekst:  24
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


04.11.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 04.11.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 04.11.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 04.11.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 04.11.2020 Fana Spare
Match:


06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.202
Likhet:
        0.9760984778404236

Indekser:
            Nynorsk/søketekst:  25
            Bokmål/treff:       303
_______________________________________________________________

Søketekst:


02.09.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 02.09.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 02.09.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 02.09.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.09.2020 Fana Spare
Match:


06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.202
Likhet:
        0.9789550304412842

Indekser:
            Nynorsk/søketekst:  26
            Bokmål/treff:       303
_______________________________________________________________

Søketekst:


08.07.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 08.07.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 08.07.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 08.07.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 08.07.2020 Fana Spare
Match:


06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.202
Likhet:
        0.9845519065856934

Indekser:
            Nynorsk/søketekst:  27
            Bokmål/treff:       303
_______________________________________________________________

Søketekst:


04.03.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 04.03.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 04.03.2020 Sbanken ASA Boliglån 50 % 2,75 % 04.03.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 04.03.2020 Nordea Direct Boliglån inntil 50 % 2,91 %

11.03
Match:


06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.202

In [19]:
for nn_i, bm_i in misses:
    match_i = matches[nn_i][1]["corpus_id"]
    print(f"Nynorsktekst indeks: {nn_i} \nFasit indeks: {bm_i} \nSøketreff indeks: {match_i}\nSøketreff score: {matches[nn_i][1]['score']}")
    print("_____\nNynorsk tekst:")
    print(nynorsk_texts_joined[nn_i][:300])
    print("\n_____\nFasit tekst:")
    print(bokmål_texts_joined[bm_i][:300])
    print("\n_____\nSøketreff tekst:")
    print(bokmål_texts_joined[match_i][:300])
    print("\n--------------------------\n")

Nynorsktekst indeks: 153
Fasit indeks: 122
Søketreff indeks: 133
Søketreff score: 0.9754108786582947
_____
Nynorsk tekst:
Ofte stilte spørsmål
Alle lærestader med utdanningar som er godkjente for utdanningsstøtte i Lånekassen, har ein administrator i arbeidsflata. Administratoren er ansvarleg for kven som har tilgang til arbeidsflata for lærestaden. Viss du manglar tilgang, kan administratoren ved din lærestad hjelpe d

_____
Fasit tekst:
Ofte stilte spørsmål
Alle læresteder med utdanninger som er godkjent for utdanningsstøtte i Lånekassen, har en administrator i arbeidsflaten. Administratoren er ansvarlig for hvem som har tilgang til arbeidsflaten for lærestedet. Dersom du mangler tilgang, kan administratoren ved ditt lærested hjelp

_____
Søketreff tekst:
– Fastrenten har aldri vært så mye høyere enn flytende rente som den er fra 1. november i år, sier administrerende direktør i Lånekassen, Morten Rosenkvist.
– Samtidig blir renten for å binde i tre år høyere enn for både 5 og 10 år. Sist vi hadde en slik situasjon var under finanskrisen i 2008, sier

--------------------------

Nynorsktekst indeks: 77
Fasit indeks: 43
Søketreff indeks: 51
Søketreff score: 0.970156192779541
_____
Nynorsk tekst:
Hanne Bjertnes
Vi loggar kontakt frå pressa
All kontakt frå pressa til Lånekassen blir logga. Vi loggar namn, oppdragsgivar, kontaktinformasjon, kva kontakten gjeld og dialogen med journalisten. Informasjonen som blir logga er berre tilgjengeleg for dei som jobbar med pressekontakt i Lånekassen, og

_____
Fasit tekst:
Presse
Vi hjelper journalister med spørsmål om statistikk og Lånekassens ordninger, tjenester og organisasjon.
Har du spørsmål om kundeforholdet ditt?
Er du kunde og har spørsmål som gjelder behandlingen av saken din, kan vi dessverre ikke hjelpe deg. Da må du ringe kundetelefonen, tlf. 21 49 60 00.

_____
Søketreff tekst:
Forsinkelse i utdanningen
Gjelder ikke for deg som tar videregående eller grunnskole med ungdomsrett.
Hva er forsinkelse?
Vi regner deg som forsinket hvis du har fått lån eller stipend til en utdanning du ikke består.
Det betyr at hvis du stryker på eksamen eller avbryter utdanningen din før eksamen

--------------------------

Nynorsktekst indeks: 160
Fasit indeks: 129
Søketreff indeks: 141
Søketreff score: 0.9850661754608154
_____
Nynorsk tekst:
Søknad om foreldrestipend
Søk om vanleg lån og stipend først
Du må vere i ei utdanning som gir rett til stipend og lån, Søk om vanleg lån og stipend før du sender inn denne søknaden.
Dersom perioden med foreldrestipend går over to forskjellige studieår, må du hugse å søke om stipend og lån for år nu

_____
Fasit tekst:
Søknad om foreldrestipend
Søk om vanlig lån og stipend først
Du må være i en utdanning som gir rett til lån og stipend. Søk om vanlig stipend og lån før du sender inn denne søknaden.
Hvis perioden med foreldrestipend går over to forskjellige studieår, må du huske å søke om stipend og lån for år numm

_____
Søketreff tekst:
Færre nordmenn studerer i utlandet
Publisert: 08.06.2022
Antallet norske studenter i utlandet synker. Nedgangen startet før koronapandemien, og har fortsatt de to siste årene. Storbritannia, som har vært norske studenters favoritt i mange år, opplever et markant fall i norske studenter.
19 300 nordm

--------------------------

#### Falsk positiv:

In [20]:
i = 19
print(search_result[i])
print(nynorsk_texts_joined[i][:250])
print("\n___________\n")
print(bokmål_texts_joined[search_result[i][0]["corpus_id"]][:250])

[{'corpus_id': 291, 'score': 0.9914844036102295}]


04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank B

___________



02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Bolig

## Aggreger setningsvektorene: Max pooling

In [21]:
import numpy as np 

emb_path = Path("embeddings/nb_sbert/maxlen_parts_max_pooling.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_embeddings = np.array([np.max(model.encode(text_parts), axis=0) for text_parts in nynorsk_maxlen_parts])
    bokmål_embeddings = np.array([np.max(model.encode(text_parts), axis=0) for text_parts in bokmål_maxlen_parts])
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
non_matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] <= threshold]

hits, misses = compare_matches_to_fasit(matches)
doc_alignment_results["max_pooling_biter"] = {"matches": len(matches), "threshold": threshold, "percent of docs": round(len(matches)/len(nynorske)*100, 2), "hits": len(hits), "misses": len(misses)}

### Inspiser matches

In [22]:
from utils import print_matches

print_matches(matches, nynorsk_texts_joined, bokmål_texts_joined)

Søketekst:
        Er du flyktning? Du blir rekna som flyktning dersom du er utanlandsk statsborgar og har fått vern (asyl) i Noreg. Du må vere registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Noreg som er godkjend f
Match:
        Er du flyktning? Du regnes som flyktning hvis du er utenlandsk statsborger og har fått beskyttelse (asyl) i Norge. Du må være registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Norge som er godkjent
Likhet:
        0.9942201972007751

Indekser:
            Nynorsk/søketekst:  0
            Bokmål/treff:       241
_______________________________________________________________

Søketekst:


Du kan bruke dette skjemaet dersom du tar høgare utdanning eller fagskoleutdanning i Noreg eller Norden, og du skal søke om støtte til studieopphald i eit anna land.

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn

Kva studieprogram følger du i Noreg/Norden? I k
Match:


Du kan bruke dette skjemaet hvis du tar høyere utdanning eller fagskoleutdanning i Norge eller Norden, og du skal søke om støtte til studieopphold i et annet land.

Skjemaet laster du opp på Dine Sider, eller du kan sende det i posten til Lånekassen behandler personopplysninger i samsvar med regel
Likhet:
        0.9845684170722961

Indekser:
            Nynorsk/søketekst:  1
            Bokmål/treff:       233
_______________________________________________________________

Søketekst:


Det er viktig at du les informasjonen på side 2 i dette søknadsskjemaet. Hugs å sende inn ein , dersom du ikkje har gjort det.

Denne søknaden lastar du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn

Nam
Match:


Det er viktig at du leser informasjonen på side 2 i dette søknadsskjemaet. Husk å sende inn en , hvis du ikke allerede har gjort det.

Denne søknaden laster du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomna
Likhet:
        0.9883565902709961

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       234
_______________________________________________________________

Søketekst:
        Nynorsk Skjema for lærlinglønn Kor stort bortebuarstipend du kan få, er avhengig av kor mykje du tener som lærling. Derfor må arbeidsgivaren din fylle ut dette skjemaet for å stadfeste lønna di. Vi kan ikkje behandle søknaden din før du har sendt opplysningar om lønna di. Du kan laste opp ferdig utf
Match:
        Bokmål Skjema for lærlinglønn Hvor stort borteboerstipend du kan få, er avhengig av hvor mye du tjener som lærling. Derfor må arbeidsgiveren din fylle ut dette skjemaet for å bekrefte lønnen din. Vi kan ikke behandle søknaden din før du har sendt opplysninger om lønnen din. Du kan laste opp ferdig u
Likhet:
        0.9880355596542358

Indekser:
            Nynorsk/søketekst:  3
            Bokmål/treff:       235
_______________________________________________________________

Søketekst:
        Nynorsk Skjema I – artikkelnr. 9001550 – nynorsk – 01.2022 – organisasjonsnummer NO 960 885 406 Namn, adresse og postnummer/-stad Personnummer Fødselsdato Kundenummer i Lånekassen Søknad om betalingsutsetting og/eller sletting av renter Du kan bruke nettsøknaden på

Kva månad/månader søker du om uts
Match:
        Bokmål Skjema I – artikkelnr. 9001550 – bokmål – 01.2022 – organisasjonsnummer NO 960 885 406 Navn, adresse og postnummer/-sted Personnummer Fødselsdato Kundenummer i Lånekassen Søknad om betalingsutsettelse og/eller sletting av renter Du kan bruke nettsøknaden på

Hvilken måned / hvilke måneder søk
Likhet:
        0.9796264171600342

Indekser:
            Nynorsk/søketekst:  4
            Bokmål/treff:       237
_______________________________________________________________

Søketekst:
        Nynorsk Eg stadfester at eg har lese vilkåra på side 2.

Oppgi perioden du søker om sletting av gjeld for

År Månad Dag Frå Til Punkt 4 skal berre fyllast ut dersom du søker om sletting av gjeld på grunn av omsorg. Arbeidstakar Sjølvstendig næringsdrivande Dato og underskrift

Adressa til arbeidsgiv
Match:
        Bokmål Ordningen gjelder for låntakere som er bosatt og yrkesaktive i Finnmark og i disse kommunene i Nord-Troms: Lyngen, Storfjord, Kåfjord, Skjervøy, Nordreisa, Kvænangen og Karlsøy. Ordningen omfatter også yrkesaktive leger i andre utvalgte kommuner. Vi henter informasjon om bosted fra Folkeregis
Likhet:
        0.9885954856872559

Indekser:
            Nynorsk/søketekst:  5
            Bokmål/treff:       236
_______________________________________________________________

Søketekst:


Du kan logge inn på og endre kontonummeret ditt dersom du har oppretta ein ny konto som du vil bruke dersom du vil ha pengane inn på ein annan av kontoane dine Lånekassen overfører berre lån og stipend til ein norsk konto som du eig. Dersom du nettopp har fått tildelt eit nytt kontonummer kan det
Match:


Du kan logge inn på og endre kontonummeret ditt hvis du har opprettet en ny konto som du vil bruke hvis du vil ha pengene inn på en annen av kontoene dine Lånekassen overfører bare lån og stipend til en norsk konto som du eier. Hvis du nettopp har fått tildelt et nytt kontonummer kan det ta noen d
Likhet:
        0.9527744650840759

Indekser:
            Nynorsk/søketekst:  6
            Bokmål/treff:       238
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer Poststad

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Eg er kjend med vilkåra for fast rente som eg finn i kapittel 2 i Stad og dato Underskrift Søknaden må vere komme
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer Poststed

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Jeg er kjent med vilkårene for fast rente som jeg finner i kapittel 2 i Sted og dato Underskrift Søknaden må være
Likhet:
        0.9836862087249756

Indekser:
            Nynorsk/søketekst:  7
            Bokmål/treff:       239
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer og poststad Telefon

Etternamnet til fullmaktshavaren Fornamnet og mellomnamnet til fullmaktshavaren Fullmakta er gyldig Frå Til

Stad og dato Underskrifta di

Du kan laste opp fullmaktsskjemaet p
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer og poststed Telefon

Fullmaktshavers etternavn Fullmaktshavers fornavn og mellomnavn Fullmakten er gyldig Fra Til

Sted og dato Din underskrift Du kan laste opp fullmaktsskjemaet på Dine sider ell
Likhet:
        0.9898584485054016

Indekser:
            Nynorsk/søketekst:  8
            Bokmål/treff:       240
_______________________________________________________________

Søketekst:


Forskrifta gjeld tilbakebetaling av utdanningslån som er gitt etter utdanningsstøtteloven og forskrift om tildeling av utdanningsstøtte. Forskrifta gir reglar om renter og tilbakebetaling betalingsutsetjing og sletting av renter sletting av gjeld misleghalden gjeld som er permanent overført til St
Match:


Kapittel 1. Innledende bestemmelser Kapittel 2. Krav til statsborgerskapet og tilknytningen til Norge Kapittel 3. Krav om opptak, studiekompetanse, alder, finansiering fra andre og gjeld Kapittel 4. Hvilke utdanninger som gir rett til lån og stipend Kapittel 5. Foreldrestipend, sykestipend og språ
Likhet:
        0.9714580774307251

Indekser:
            Nynorsk/søketekst:  9
            Bokmål/treff:       282
_______________________________________________________________

Søketekst:


Forskrifta gjeld tilbakebetaling av utdanningslån som er gitt etter utdanningsstøtteloven og forskrift om tildeling av utdanningsstøtte. Forskrifta gir reglar om renter og tilbakebetaling betalingsutsetjing og sletting av renter sletting av gjeld misleghalden gjeld som er permanent overført til St
Match:
        Fastsatt av Kunnskapsdepartementet 13. februar 2018 med hjemmel i lov 3. juni 2005 nr. 37 om utdanningsstøtte (utdanningsstøtteloven) § 3, § 4, § 5, § 6 og § 7. Det Med ”andre stipend” menes for eksempel forsørgerstipend, reisestipend, foreldrestipend, sykestipend, flyktningstipend og språkstipend.
Likhet:
        0.9727482795715332

Indekser:
            Nynorsk/søketekst:  11
            Bokmål/treff:       256
_______________________________________________________________

Søketekst:
        Du finn informasjon om vilkår og dokumentasjon på neste side. Søknad om sjukestipend Nynorsk Skjema S – artikkelnummer 9001561 – nynorsk – 06.2022 – Organisasjonsnummer NO 960 885 406 Namn, adresse og postnummer/-stad Personnummer Fødselsdato Kundenummer i Lånekassen

Eigen sjukdom Sjukt barn Barnet
Match:
        Du finner informasjon om vilkår og dokumentasjon på neste side. Søknad om sykestipend Bokmål Skjema S – artikkelnummer 9001561 – bokmål – 06.2022– Organisasjonsnummer NO 960 885 406 Navn, adresse og postnummer/-sted Personnummer Fødselsdato Kundenummer i Lånekassen

Egen sykdom Sykt barn Barnets fød
Likhet:
        0.9824733138084412

Indekser:
            Nynorsk/søketekst:  12
            Bokmål/treff:       250
_______________________________________________________________

Søketekst:
        Søknaden fortset på neste side

Tilleggsstipend kan bli gitt i tillegg til vanleg utdanningsstøtte og er på inntil 4 000 kroner per månad. Stipendet er meint for søkarar som er i stand til å studere, men som på grunn av nedsett funksjonsevne bruker så mykje tid og krefter på å studere, at dei ikkje
Match:
        Søknaden fortsetter på neste side

Tilleggsstipend kan bli gitt i tillegg til vanlig utdanningsstøtte og er på inntil 4 000 kroner per måned. Stipendet er ment for søkere som er i stand til å studere, men som på grunn av nedsatt funksjonsevne bruker så mye tid og krefter på å studere, at de ikke kan
Likhet:
        0.9874338507652283

Indekser:
            Nynorsk/søketekst:  13
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        Skjemaet fortset på neste side

Søknaden gjeld for søkarar som på grunn av nedsett funksjonsevne ikkje er i stand til å ha lønna arbeid i sommarferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og førebu seg til neste semester. Med lønna arbeid meiner vi alt arbeid der lønna er s
Match:
        Skjemaet fortsetter på neste side

Søknaden gjelder for søkere som på grunn av nedsatt funksjonsevne ikke er i stand til å ha lønnet arbeid i sommerferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og forberede seg til neste semester. Med lønnet arbeid menes alt arbeid hvor lønna
Likhet:
        0.9867182970046997

Indekser:
            Nynorsk/søketekst:  14
            Bokmål/treff:       252
_______________________________________________________________

Søketekst:


Etternamn Fornamn og mellomnamn Fødselsdato (dag – månad – år)

Kva utdanning har eleven teke? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førarkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – månad – år

Oppgi siste dato elev
Match:


Etternavn Fornavn og mellomnavn Fødselsdato (dag – måned – år)

Hvilken utdanning har eleven tatt? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førerkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – måned – år

Oppgi siste dato
Likhet:
        0.9922983646392822

Indekser:
            Nynorsk/søketekst:  16
            Bokmål/treff:       255
_______________________________________________________________

Søketekst:
        Søknaden held fram på neste side

,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden
Match:
        Søknaden fortsetter på neste side

,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og do
Likhet:
        0.9808679223060608

Indekser:
            Nynorsk/søketekst:  18
            Bokmål/treff:       258
_______________________________________________________________

Søketekst:


04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 04.05.2022 Din Bank (Spar
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.961942195892334

Indekser:
            Nynorsk/søketekst:  19
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


05.01.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 05.01.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 05.01.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 05.01.2022 OBOS-banken AS Boliglån 50 % 1,82 % 05.01.2022 Sunndal Sparebank B
Match:


06.07.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 06.07.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 06.07.2022 Haltdalen Sparebank Boliglån 34+ 2,32% 06.07.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 06.07.2022 KLP Banken AS Boliglån ordinær - 7
Likhet:
        0.9619201421737671

Indekser:
            Nynorsk/søketekst:  20
            Bokmål/treff:       288
_______________________________________________________________

Søketekst:


01.09.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 01.09.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 01.09.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 01.09.2021 OBOS-banken AS Boliglån 50 % 1,57 % 01.09.2021 Sunndal Sparebank B
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9742770791053772

Indekser:
            Nynorsk/søketekst:  21
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


05.05.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 05.05.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 05.05.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 05.05.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 05.05.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9662555456161499

Indekser:
            Nynorsk/søketekst:  22
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


04.11.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 04.11.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 04.11.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 04.11.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 04.11.2020 Fana Spare
Match:


06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.202
Likhet:
        0.9531354904174805

Indekser:
            Nynorsk/søketekst:  25
            Bokmål/treff:       303
_______________________________________________________________

Søketekst:


04.03.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 04.03.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 04.03.2020 Sbanken ASA Boliglån 50 % 2,75 % 04.03.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 04.03.2020 Nordea Direct Boliglån inntil 50 % 2,91 %

11.03
Match:


06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.202
Likhet:
        0.9673339128494263

Indekser:
            Nynorsk/søketekst:  28
            Bokmål/treff:       303
_______________________________________________________________

Søketekst:


01.01.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 01.01.2020 Sbanken ASA Boliglån 50 % 2,75 % 01.01.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 01.01.2020 NORDirektebank (Skagerrak Sparebank) Boliglån inntil 60 % 2,89 % 01.01.2020 Gjensidige Bank Boliglån inntil 50 % 2,91 %
Match:


06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.202
Likhet:
        0.9584144353866577

Indekser:
            Nynorsk/søketekst:  29
            Bokmål/treff:       303
_______________________________________________________________

Søketekst:
        Støtte til lengre språkkurs Ein analyse av utvikling, omfang og bruk basert på registerdata

Notat nr. 3/2022 Redaktør: Beate Ellingsen Forfattarar: Tom Halfdan Tobiassen og Kristine von Simson

1.Samandrag .............................................................................................
Match:


Flyktningstipendet Mottakere av flyktningstipendet og deres bruk av Lånekassens ordninger

Notat nr. 5/2022

Redaktør: Beate Ellingsen Forfattere: Elisabeth Elman og Karl Magnus Bjorøy

Sammendrag .....................................................................................................
Likhet:
        0.9770572781562805

Indekser:
            Nynorsk/søketekst:  31
            Bokmål/treff:       307
_______________________________________________________________

Søketekst:
        Utvida stipend til skulepengar ved utvalde lærestader

Påverker det utanlandsstudentane sitt val av studiestad?

Notat nr. 2/2022 Utvida stipend til skolepengar ved utvalde lærestader – Påverker det utanlandsstudentane sitt val av studiestad? Redaktør: Beate Ellingsen Forfattarar: Tom Halfdan Tobias
Match:


Flyktningstipendet Mottakere av flyktningstipendet og deres bruk av Lånekassens ordninger

Notat nr. 5/2022

Redaktør: Beate Ellingsen Forfattere: Elisabeth Elman og Karl Magnus Bjorøy


#### Falsk positiv:
Den samme som over

In [23]:
i = 19
print(search_result[i])
print(nynorsk_texts_joined[i][:250])
print("\n___________\n")
print(bokmål_texts_joined[search_result[i][0]["corpus_id"]][:250])

[{'corpus_id': 293, 'score': 0.961942195892334}]


04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank B

___________



03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Spareban

## Konklusjon

In [24]:
pd.DataFrame(doc_alignment_results).T.sort_values("hits")

                    matches  threshold  percent of docs  hits  misses
naiv_cutoff_biter     180.0       0.95            70.31  40.0    15.0
naiv_cutoff           204.0       0.95            79.69  42.0    13.0
max_pooling_biter     221.0       0.95            86.33  48.0     7.0
mean_pooling_biter    236.0       0.95            92.19  52.0     3.0

Vi får flest matches og flest hits ved å aggregere opp sentence embeddings med mean pooling.   
Vi har ikke så mange negative eksempler, så det er ikke helt sikkert at dette er den mest nøyaktige metoden.

# Setnings/avsnittsalignment

In [25]:
sent_alignment_results = {}

In [26]:
nynorsk_texts_flat = sorted(list({text for text_list in nynorske.fulltext for text in text_list if text}))
bokmål_texts_flat = sorted(list({text for text_list in bokmålske.fulltext for text in text_list if text}))
len(nynorsk_texts_flat), len(bokmål_texts_flat)

(4032, 6452)

In [27]:
nn_pair_indices = set()
bm_pair_indices = set()
for i, text in enumerate(nynorsk_texts_flat):
    for i2, text2 in enumerate(bokmål_texts_flat):
        if text == text2:
            nn_pair_indices.add(i)
            bm_pair_indices.add(i2)
len(nn_pair_indices)

sent_alignment_results["string_comparison"] = {"matches": len(nn_pair_indices), "percent of sents": round(len(nn_pair_indices)/len(nynorsk_texts_flat), 2)}

In [28]:
nynorsk_texts_flat = [text for i, text in enumerate(nynorsk_texts_flat) if i not in nn_pair_indices]
bokmål_texts_flat = [text for i, text in enumerate(bokmål_texts_flat) if i not in bm_pair_indices]

## Naiv approach
Godta cut-off på sBERT sin maxlengde

In [29]:
import numpy as np

emb_path = Path("embeddings/nb_sbert/texts_flat.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_embeddings = model.encode(nynorsk_texts_flat)
    bokmål_embeddings = model.encode(bokmål_texts_flat)
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
sent_alignment_results["naiv_cutoff"] = {"threshold": threshold, "matches": len(matches), "percent of sents": round(len(matches)/len(nynorsk_texts_flat)*100, 2)}

### Inspiser matches

In [30]:
print_matches(matches, nynorsk_texts_flat, bokmål_texts_flat, stop_printing_at=30)

Søketekst:
        ,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden og dokumentasjonen etter at du ha
Match:
        ,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og dokumentasjonen etter at du har fått
Likhet:
        0.9970904588699341

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       9
_______________________________________________________________

Søketekst:
        - Eg er stolt av arbeidsplassen min!
Match:
        - Jeg er stolt av arbeidsplassen min!
Likhet:
        0.9705960750579834

Indekser:
            Nynorsk/søketekst:  3
            Bokmål/treff:       10
_______________________________________________________________

Søketekst:
        - Studentar, spesielt i Sør-Noreg, har fått merke dei høge straumprisane i haust og vinter. Dette er eit målretta tiltak for dei som har fått høgare utgifter til oppvarming av bustad. Tilleggslånet med stipend skal vere tilgjengeleg gjennom Lånekassen i løpet av januar og pengane skal utbetalast ras
Match:
        – Studenter, spesielt i Sør-Norge, har fått merke de høye strømprisene i høst og vinter. Dette er et målrettet tiltak for de som har fått høyere utgifter til oppvarming av bolig. Tilleggslånet med stipend skal være tilgjengelig gjennom Lånekassen i løpet av januar og pengene skal utbetales raskt, si
Likhet:
        0.9712804555892944

Indekser:
            Nynorsk/søketekst:  4
            Bokmål/treff:       6061
_______________________________________________________________

Søketekst:
        0-300 kilometer - 1,92 kroner per kilometer
Match:
        0-300 kilometer - 1,94 kroner per kilometer
Likhet:
        0.9754868745803833

Indekser:
            Nynorsk/søketekst:  11
            Bokmål/treff:       47
_______________________________________________________________

Søketekst:
        01.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 01.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 01.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 01.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 01.06.2022 Haltdalen Sparebank Bolig
Match:
        27.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 27.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 27.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2.07% 27.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 27.04.2022 Din Bank (Spareb
Likhet:
        0.9627858400344849

Indekser:
            Nynorsk/søketekst:  13
            Bokmål/treff:       428
_______________________________________________________________

Søketekst:
        01.09.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 01.09.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 01.09.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 01.09.2021 OBOS-banken AS Boliglån 50 % 1,57 % 01.09.2021 Sunndal Sparebank Bol
Match:
        29.12.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 29.12.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 29.12.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 29.12.2021 OBOS-banken AS Boliglån 50 % 1,82 % 29.12.2021 KLP Banken AS Boliglå
Likhet:
        0.9741160869598389

Indekser:
            Nynorsk/søketekst:  14
            Bokmål/treff:       449
_______________________________________________________________

Søketekst:
        02.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 02.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 02.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 02.06.2021 Sunndal Sparebank Bol
Match:
        29.12.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 29.12.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 29.12.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 29.12.2021 OBOS-banken AS Boliglån 50 % 1,82 % 29.12.2021 KLP Banken AS Boliglå
Likhet:
        0.9730879664421082

Indekser:
            Nynorsk/søketekst:  15
            Bokmål/treff:       449
_______________________________________________________________

Søketekst:
        02.09.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 02.09.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 02.09.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 02.09.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.09.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9854716062545776

Indekser:
            Nynorsk/søketekst:  16
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        02.12.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 02.12.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 02.12.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 02.12.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.12.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9760338664054871

Indekser:
            Nynorsk/søketekst:  17
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        03.02.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.02.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.02.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.02.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.02.2021 Fana Spareba
Match:
        02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 02.03.2022 OBOS-banken AS Bo
Likhet:
        0.9758697748184204

Indekser:
            Nynorsk/søketekst:  18
            Bokmål/treff:       62
_______________________________________________________________

Søketekst:
        03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spareba
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9764666557312012

Indekser:
            Nynorsk/søketekst:  19
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        04.03.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 04.03.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 04.03.2020 Sbanken ASA Boliglån 50 % 2,75 % 04.03.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 04.03.2020 Nordea Direct Boliglån inntil 50 % 2,91 %
Match:
        06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.2020
Likhet:
        0.9628557562828064

Indekser:
            Nynorsk/søketekst:  20
            Bokmål/treff:       93
_______________________________________________________________

Søketekst:
        04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 04.05.2022 Din Bank (Spareb
Match:
        13.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 13.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 13.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2.07% 13.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 13.04.2022 Soknedal Spareba
Likhet:
        0.9900953769683838

Indekser:
            Nynorsk/søketekst:  21
            Bokmål/treff:       201
_______________________________________________________________

Søketekst:
        04.11.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 04.11.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 04.11.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 04.11.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 04.11.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9817332029342651

Indekser:
            Nynorsk/søketekst:  22
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        05.01.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 05.01.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 05.01.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 05.01.2022 OBOS-banken AS Boliglån 50 % 1,82 % 05.01.2022 Sunndal Sparebank Bol
Match:
        06.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 06.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 06.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 06.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 06.04.2022 Landkreditt Bank
Likhet:
        0.9879213571548462

Indekser:
            Nynorsk/søketekst:  23
            Bokmål/treff:       91
_______________________________________________________________

Søketekst:
        05.02.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 05.02.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 05.02.2020 Sbanken ASA Boliglån 50 % 2,75 % 05.02.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 05.02.2020 Gjensidige Bank Boliglån inntil 50 % 2,91 %
Match:
        06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.2020
Likhet:
        0.9772919416427612

Indekser:
            Nynorsk/søketekst:  24
            Bokmål/treff:       93
_______________________________________________________________

Søketekst:
        05.05.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 05.05.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 05.05.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 05.05.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 05.05.2021 Fana Spareba
Match:
        29.12.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 29.12.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 29.12.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 29.12.2021 OBOS-banken AS Boliglån 50 % 1,82 % 29.12.2021 KLP Banken AS Boliglå
Likhet:
        0.9598338603973389

Indekser:
            Nynorsk/søketekst:  25
            Bokmål/treff:       449
_______________________________________________________________

Søketekst:
        06.01.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 06.01.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 06.01.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 06.01.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 06.01.2021 Fana Spareba
Match:
        01.12.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 01.12.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 01.12.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 01.12.2021 OBOS-banken AS Boliglån 50 % 1,82 % 01.12.2021 KLP Banken AS Boliglå
Likhet:
        0.9804394245147705

Indekser:
            Nynorsk/søketekst:  26
            Bokmål/treff:       61
_______________________________________________________________

Søketekst:
        06.10.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 06.10.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 06.10.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 06.10.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 06.10.2021 OBOS-banken
Match:
        10.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 10.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 10.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 10.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 10.11.2021 OBOS-banken
Likhet:
        0.9770461320877075

Indekser:
            Nynorsk/søketekst:  27
            Bokmål/treff:       156
_______________________________________________________________

Søketekst:
        07.04.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 07.04.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 07.04.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 07.04.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 07.04.2021 Fana Spareba
Match:
        06.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 06.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 06.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 06.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 06.04.2022 Landkreditt Bank
Likhet:
        0.9773353338241577

Indekser:
            Nynorsk/søketekst:  29
            Bokmål/treff:       91
_______________________________________________________________

Søketekst:
        07.10.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 07.10.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 07.10.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 07.10.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 07.10.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9839380979537964

Indekser:
            Nynorsk/søketekst:  30
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        08.01.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 08.01.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 08.01.2020 Sbanken ASA Boliglån 50 % 2,75 % 08.01.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 08.01.2020 Gjensidige Bank Boliglån inntil 50 % 2,91 %
Match:
        06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.2020
Likhet:
        0.9656561017036438

Indekser:
            Nynorsk/søketekst:  31
            Bokmål/treff:       93
_______________________________________________________________

Søketekst:
        08.04.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 08.04.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 08.04.2020 Sbanken ASA Boliglån 50 % 2 % 08.04.2020 Nordea Direct Boliglån inntil 50 % 2,08 % 08.04.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 %
Match:
        06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.2020
Likhet:
        0.9676260352134705

Indekser:
            Nynorsk/søketekst:  33
            Bokmål/treff:       93
_______________________________________________________________

Søketekst:
        08.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 08.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 08.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,17% 08.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 08.06.2022 Haltdalen Sparebank Bolig
Match:
        16.08.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,56% 16.08.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,58% 16.08.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,68% 16.08.2022 Sbanken ASA Boliglån 50 % 2,75% 16.08.2022 OBOS-banken AS Boliglån 50 %
Likhet:
        0.9890115857124329

Indekser:
            Nynorsk/søketekst:  34
            Bokmål/treff:       241
_______________________________________________________________

Søketekst:
        08.07.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 08.07.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 08.07.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 08.07.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 08.07.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9826955795288086

Indekser:
            Nynorsk/søketekst:  35
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        09.02.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79 % 09.02.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,81 % 09.02.2022 Haltdalen Sparebank Boliglån 60% 1,96 % 09.02.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 09.02.2022 KLP Banken AS Bol
Match:
        09.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 09.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 09.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 09.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 09.03.2022 OBOS-banken AS Bo
Likhet:

## Del opp setninger/avsnitt som er lengre enn sBERT sin maxlengde

In [31]:
from utils import tokenize_and_split_text

nynorsk_maxlen_parts_flat = [tokenize_and_split_text(text, model.tokenizer, model.max_seq_length) for text in nynorsk_texts_flat]
bokmål_maxlen_parts_flat = [tokenize_and_split_text(text, model.tokenizer, model.max_seq_length) for text in bokmål_texts_flat]

## Naiv 2
Aggreger med Sententence_transformers hack (to første listene kuttes på 1/2 maxlen og konkateneres)

In [32]:
emb_path = Path("embeddings/nb_sbert/maxlen_parts_flat.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_embeddings = model.encode([e+[""] for e in nynorsk_maxlen_parts_flat])
    bokmål_embeddings = model.encode([e+[""] for e in bokmål_maxlen_parts_flat])
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
sent_alignment_results["naiv_cutoff_biter"] = {"threshold": threshold, "matches": len(matches), "percent of sents": round(len(matches)/len(nynorsk_maxlen_parts_flat)*100, 2)}

### Inspiser matches

In [33]:
print_matches(matches, nynorsk_texts_flat, bokmål_texts_flat, stop_printing_at=50)

Søketekst:
        ,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden og dokumentasjonen etter at du ha
Match:
        ,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og dokumentasjonen etter at du har fått
Likhet:
        0.9964262843132019

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       9
_______________________________________________________________

Søketekst:
        - Eg er stolt av arbeidsplassen min!
Match:
        - Jeg er stolt av arbeidsplassen min!
Likhet:
        0.971623420715332

Indekser:
            Nynorsk/søketekst:  3
            Bokmål/treff:       10
_______________________________________________________________

Søketekst:
        - Studentar, spesielt i Sør-Noreg, har fått merke dei høge straumprisane i haust og vinter. Dette er eit målretta tiltak for dei som har fått høgare utgifter til oppvarming av bustad. Tilleggslånet med stipend skal vere tilgjengeleg gjennom Lånekassen i løpet av januar og pengane skal utbetalast ras
Match:
        – Studenter, spesielt i Sør-Norge, har fått merke de høye strømprisene i høst og vinter. Dette er et målrettet tiltak for de som har fått høyere utgifter til oppvarming av bolig. Tilleggslånet med stipend skal være tilgjengelig gjennom Lånekassen i løpet av januar og pengene skal utbetales raskt, si
Likhet:
        0.9600521922111511

Indekser:
            Nynorsk/søketekst:  4
            Bokmål/treff:       6061
_______________________________________________________________

Søketekst:
        0-300 kilometer - 1,92 kroner per kilometer
Match:
        0-300 kilometer - 1,94 kroner per kilometer
Likhet:
        0.9753260612487793

Indekser:
            Nynorsk/søketekst:  11
            Bokmål/treff:       47
_______________________________________________________________

Søketekst:
        01.09.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 01.09.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 01.09.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 01.09.2021 OBOS-banken AS Boliglån 50 % 1,57 % 01.09.2021 Sunndal Sparebank Bol
Match:
        29.12.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 29.12.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 29.12.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 29.12.2021 OBOS-banken AS Boliglån 50 % 1,82 % 29.12.2021 KLP Banken AS Boliglå
Likhet:
        0.96442049741745

Indekser:
            Nynorsk/søketekst:  14
            Bokmål/treff:       449
_______________________________________________________________

Søketekst:
        02.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 02.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 02.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 02.06.2021 Sunndal Sparebank Bol
Match:
        24.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 24.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 24.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 24.11.2021 OBOS-banken AS Boliglån 50 % 1,82 % 24.11.2021 KLP Banken AS Boliglå
Likhet:
        0.9682888984680176

Indekser:
            Nynorsk/søketekst:  15
            Bokmål/treff:       375
_______________________________________________________________

Søketekst:
        02.09.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 02.09.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 02.09.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 02.09.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.09.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9823959469795227

Indekser:
            Nynorsk/søketekst:  16
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        02.12.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 02.12.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 02.12.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 02.12.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.12.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9737945795059204

Indekser:
            Nynorsk/søketekst:  17
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        03.02.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.02.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.02.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.02.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.02.2021 Fana Spareba
Match:
        06.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 06.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 06.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 06.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 06.04.2022 Landkreditt Bank
Likhet:
        0.9543505907058716

Indekser:
            Nynorsk/søketekst:  18
            Bokmål/treff:       91
_______________________________________________________________

Søketekst:
        03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spareba
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9592908620834351

Indekser:
            Nynorsk/søketekst:  19
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        04.03.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 04.03.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 04.03.2020 Sbanken ASA Boliglån 50 % 2,75 % 04.03.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 04.03.2020 Nordea Direct Boliglån inntil 50 % 2,91 %
Match:
        06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.2020
Likhet:
        0.9698192477226257

Indekser:
            Nynorsk/søketekst:  20
            Bokmål/treff:       93
_______________________________________________________________

Søketekst:
        04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 04.05.2022 Din Bank (Spareb
Match:
        13.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 13.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 13.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2.07% 13.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 13.04.2022 Soknedal Spareba
Likhet:
        0.9900388717651367

Indekser:
            Nynorsk/søketekst:  21
            Bokmål/treff:       201
_______________________________________________________________

Søketekst:
        04.11.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 04.11.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 04.11.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 04.11.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 04.11.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9794953465461731

Indekser:
            Nynorsk/søketekst:  22
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        05.01.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 05.01.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 05.01.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 05.01.2022 OBOS-banken AS Boliglån 50 % 1,82 % 05.01.2022 Sunndal Sparebank Bol
Match:
        23.08.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,56% 23.08.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,58% 23.08.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,68% 23.08.2022 OBOS-banken AS Boliglån 50 % 2,82% 23.08.2022 Sunndal Sparebank Boliglå
Likhet:
        0.9751293659210205

Indekser:
            Nynorsk/søketekst:  23
            Bokmål/treff:       364
_______________________________________________________________

Søketekst:
        05.02.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 05.02.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 05.02.2020 Sbanken ASA Boliglån 50 % 2,75 % 05.02.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 05.02.2020 Gjensidige Bank Boliglån inntil 50 % 2,91 %
Match:
        06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.2020
Likhet:
        0.9654372930526733

Indekser:
            Nynorsk/søketekst:  24
            Bokmål/treff:       93
_______________________________________________________________

Søketekst:
        05.05.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 05.05.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 05.05.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 05.05.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 05.05.2021 Fana Spareba
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9541563987731934

Indekser:
            Nynorsk/søketekst:  25
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        06.01.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 06.01.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 06.01.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 06.01.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 06.01.2021 Fana Spareba
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.956696093082428

Indekser:
            Nynorsk/søketekst:  26
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        06.10.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 06.10.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 06.10.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 06.10.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 06.10.2021 OBOS-banken
Match:
        10.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 10.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 10.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 10.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 10.11.2021 OBOS-banken
Likhet:
        0.9634050130844116

Indekser:
            Nynorsk/søketekst:  27
            Bokmål/treff:       156
_______________________________________________________________

Søketekst:
        07.04.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 07.04.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 07.04.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 07.04.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 07.04.2021 Fana Spareba
Match:
        06.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 06.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 06.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 06.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 06.04.2022 Landkreditt Bank
Likhet:
        0.9638874530792236

Indekser:
            Nynorsk/søketekst:  29
            Bokmål/treff:       91
_______________________________________________________________

Søketekst:
        07.10.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 07.10.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 07.10.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 07.10.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 07.10.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9809838533401489

Indekser:
            Nynorsk/søketekst:  30
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        08.01.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 08.01.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 08.01.2020 Sbanken ASA Boliglån 50 % 2,75 % 08.01.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 08.01.2020 Gjensidige Bank Boliglån inntil 50 % 2,91 %
Match:
        06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.2020
Likhet:
        0.9565320611000061

Indekser:
            Nynorsk/søketekst:  31
            Bokmål/treff:       93
_______________________________________________________________

Søketekst:
        08.04.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 08.04.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 08.04.2020 Sbanken ASA Boliglån 50 % 2 % 08.04.2020 Nordea Direct Boliglån inntil 50 % 2,08 % 08.04.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 %
Match:
        06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.2020
Likhet:
        0.9778530597686768

Indekser:
            Nynorsk/søketekst:  33
            Bokmål/treff:       93
_______________________________________________________________

Søketekst:
        08.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 08.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 08.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,17% 08.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 08.06.2022 Haltdalen Sparebank Bolig
Match:
        23.08.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,56% 23.08.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,58% 23.08.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,68% 23.08.2022 OBOS-banken AS Boliglån 50 % 2,82% 23.08.2022 Sunndal Sparebank Boliglå
Likhet:
        0.984533429145813

Indekser:
            Nynorsk/søketekst:  34
            Bokmål/treff:       364
_______________________________________________________________

Søketekst:
        08.07.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 08.07.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 08.07.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 08.07.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 08.07.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9813273549079895

Indekser:
            Nynorsk/søketekst:  35
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        09.02.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79 % 09.02.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,81 % 09.02.2022 Haltdalen Sparebank Boliglån 60% 1,96 % 09.02.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 09.02.2022 KLP Banken AS Bol
Match:
        09.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 09.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 09.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 09.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 09.03.2022 OBOS-banken AS Bo
Likhet:
        0.9586855173110962

Indekser:
            Nynorsk/søketekst:  36
            Bokmål/treff:       113
_______________________________________________________________

Søketekst:
        09.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 09.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 09.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 09.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 09.06.2021 Sunndal Sparebank Bol
Match:
        24.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 24.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 24.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 24.11.2021 OBOS-banken AS Boliglån 50 % 1,82 % 24.11.2021 KLP Banken AS Boliglå
Likhet:

#### Falsk positiv

In [34]:
i = 24
print(search_result[i])
print(nynorsk_texts_flat[i])
print("\n___________\n")
print(bokmål_texts_flat[search_result[i][0]["corpus_id"]])

[{'corpus_id': 93, 'score': 0.9654372930526733}]
05.02.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 05.02.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 05.02.2020 Sbanken ASA Boliglån 50 % 2,75 % 05.02.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 05.02.2020 Gjensidige Bank Boliglån inntil 50 % 2,91 %

___________

06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 13.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 13.05.2020 Fana Sparebank Nettlån Bolig 50 % 1,73 % 13.05.2020 Sandnes Sparebank Nedbetalingslån innenfor 70 % 1,92 % 13.05.2020 BN Bank ASA Boliglån Alltid Fornøyd 50 % 1,97 % 20.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 20.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 20.05.2020 Fana Sparebank Nettlån Bolig 50 % 1,73 % 20.05.2020 OBOS-banken AS Boliglån 50 % 1,87 % 20.05.2020 Sbanken ASA Boliglån 50 % 1,90 % 27.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 27.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 27.05.2020 Fana Sparebank Nettlån Bolig 50 % 1,73 % 27.05.2020 OBOS-banken AS Boliglån 50 % 1,87 % 27.05.2020 Sbanken ASA Boliglån 50 % 1,90 % 03.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.06.2020 Fana Sparebank Nettlån Bolig 50 % 1,73 % 03.06.2020 OBOS-banken AS Boliglån 50 % 1,87 % 03.06.2020 Sbanken ASA Boliglån 50 % 1,90 % 10.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 10.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 10.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 10.06.2020 Fana Sparebank Nettlån Bolig 50 % 1,73 % 10.06.2020 OBOS-banken AS Boliglån 50 % 1,87 %

## Mean pooling

In [35]:
emb_path = Path("embeddings/nb_sbert/maxlen_parts_flat_mean_pooling.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_embeddings = np.array([np.mean(model.encode(sent), axis=0) for sent in nynorsk_maxlen_parts_flat])
    bokmål_embeddings = np.array([np.mean(model.encode(sent), axis=0) for sent in bokmål_maxlen_parts_flat])
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)
    
search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
sent_alignment_results["mean_pooling_biter"] = {"threshold": threshold, "matches": len(matches), "percent of sents": round(len(matches)/len(nynorsk_maxlen_parts_flat)*100, 2)}

### Inspiser matches

In [36]:
print_matches(matches, nynorsk_texts_flat, bokmål_texts_flat, stop_printing_at=20)

Søketekst:
        ,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden og dokumentasjonen etter at du ha
Match:
        ,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og dokumentasjonen etter at du har fått
Likhet:
        0.9942946434020996

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       9
_______________________________________________________________

Søketekst:
        - Eg er stolt av arbeidsplassen min!
Match:
        - Jeg er stolt av arbeidsplassen min!
Likhet:
        0.970596194267273

Indekser:
            Nynorsk/søketekst:  3
            Bokmål/treff:       10
_______________________________________________________________

Søketekst:
        - Studentar, spesielt i Sør-Noreg, har fått merke dei høge straumprisane i haust og vinter. Dette er eit målretta tiltak for dei som har fått høgare utgifter til oppvarming av bustad. Tilleggslånet med stipend skal vere tilgjengeleg gjennom Lånekassen i løpet av januar og pengane skal utbetalast ras
Match:
        – Studenter, spesielt i Sør-Norge, har fått merke de høye strømprisene i høst og vinter. Dette er et målrettet tiltak for de som har fått høyere utgifter til oppvarming av bolig. Tilleggslånet med stipend skal være tilgjengelig gjennom Lånekassen i løpet av januar og pengene skal utbetales raskt, si
Likhet:
        0.9728579521179199

Indekser:
            Nynorsk/søketekst:  4
            Bokmål/treff:       6061
_______________________________________________________________

Søketekst:
        0-300 kilometer - 1,92 kroner per kilometer
Match:
        0-300 kilometer - 1,94 kroner per kilometer
Likhet:
        0.9754868745803833

Indekser:
            Nynorsk/søketekst:  11
            Bokmål/treff:       47
_______________________________________________________________

Søketekst:
        01.01.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 01.01.2020 Sbanken ASA Boliglån 50 % 2,75 % 01.01.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 01.01.2020 NORDirektebank (Skagerrak Sparebank) Boliglån inntil 60 % 2,89 % 01.01.2020 Gjensidige Bank Boliglån inntil 50 % 2,91 %
Match:
        06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.2020
Likhet:
        0.9699519276618958

Indekser:
            Nynorsk/søketekst:  12
            Bokmål/treff:       93
_______________________________________________________________

Søketekst:
        01.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 01.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 01.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 01.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 01.06.2022 Haltdalen Sparebank Bolig
Match:
        02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 02.03.2022 OBOS-banken AS Bo
Likhet:
        0.9782564640045166

Indekser:
            Nynorsk/søketekst:  13
            Bokmål/treff:       62
_______________________________________________________________

Søketekst:
        01.09.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 01.09.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 01.09.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 01.09.2021 OBOS-banken AS Boliglån 50 % 1,57 % 01.09.2021 Sunndal Sparebank Bol
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9771021008491516

Indekser:
            Nynorsk/søketekst:  14
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        02.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 02.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 02.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 02.06.2021 Sunndal Sparebank Bol
Match:
        17.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 17.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 17.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 17.11.2021 OBOS-banken
Likhet:
        0.9738302230834961

Indekser:
            Nynorsk/søketekst:  15
            Bokmål/treff:       252
_______________________________________________________________

Søketekst:
        02.09.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 02.09.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 02.09.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 02.09.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.09.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9843835830688477

Indekser:
            Nynorsk/søketekst:  16
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        02.12.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 02.12.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 02.12.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 02.12.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.12.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.973263144493103

Indekser:
            Nynorsk/søketekst:  17
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        03.02.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.02.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.02.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.02.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.02.2021 Fana Spareba
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9759365320205688

Indekser:
            Nynorsk/søketekst:  18
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spareba
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9799888730049133

Indekser:
            Nynorsk/søketekst:  19
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        04.03.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 04.03.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 04.03.2020 Sbanken ASA Boliglån 50 % 2,75 % 04.03.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 04.03.2020 Nordea Direct Boliglån inntil 50 % 2,91 %
Match:
        06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.2020
Likhet:
        0.9739149808883667

Indekser:
            Nynorsk/søketekst:  20
            Bokmål/treff:       93
_______________________________________________________________

Søketekst:
        04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 04.05.2022 Din Bank (Spareb
Match:
        27.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 27.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 27.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2.07% 27.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 27.04.2022 Din Bank (Spareb
Likhet:
        0.9870688915252686

Indekser:
            Nynorsk/søketekst:  21
            Bokmål/treff:       428
_______________________________________________________________

Søketekst:
        04.11.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 04.11.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 04.11.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 04.11.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 04.11.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9820359945297241

Indekser:
            Nynorsk/søketekst:  22
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        05.01.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 05.01.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 05.01.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 05.01.2022 OBOS-banken AS Boliglån 50 % 1,82 % 05.01.2022 Sunndal Sparebank Bol
Match:
        06.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 06.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 06.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 06.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 06.04.2022 Landkreditt Bank
Likhet:
        0.9863043427467346

Indekser:
            Nynorsk/søketekst:  23
            Bokmål/treff:       91
_______________________________________________________________

Søketekst:
        05.02.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 05.02.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 05.02.2020 Sbanken ASA Boliglån 50 % 2,75 % 05.02.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 05.02.2020 Gjensidige Bank Boliglån inntil 50 % 2,91 %
Match:
        06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.2020
Likhet:
        0.97381991147995

Indekser:
            Nynorsk/søketekst:  24
            Bokmål/treff:       93
_______________________________________________________________

Søketekst:
        05.05.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 05.05.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 05.05.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 05.05.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 05.05.2021 Fana Spareba
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9585309028625488

Indekser:
            Nynorsk/søketekst:  25
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        06.01.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 06.01.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 06.01.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 06.01.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 06.01.2021 Fana Spareba
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.975770890712738

Indekser:
            Nynorsk/søketekst:  26
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        06.10.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 06.10.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 06.10.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 06.10.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 06.10.2021 OBOS-banken
Match:
        10.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 10.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 10.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 10.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 10.11.2021 OBOS-banken
Likhet:
        0.9864321351051331

Indekser:
            Nynorsk/søketekst:  27
            Bokmål/treff:       156
_______________________________________________________________

## Max pooling

In [37]:
emb_path = Path("embeddings/nb_sbert/maxlen_parts_flat_max_pooling.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_embeddings = np.array([np.max(model.encode(sent), axis=0) for sent in nynorsk_maxlen_parts_flat])
    bokmål_embeddings = np.array([np.max(model.encode(sent), axis=0) for sent in bokmål_maxlen_parts_flat])
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
non_matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] <= threshold]

sent_alignment_results["max_pooling_biter"] = {"threshold": threshold, "matches": len(matches), "percent of sents": round(len(matches)/len(nynorsk_maxlen_parts_flat)*100, 2)}

### Inspiser matches

In [38]:
# print_matches(matches, nynorsk_texts_flat, bokmål_texts_flat, stop_printing_at=50)
print_matches(non_matches, nynorsk_texts_flat, bokmål_texts_flat, stop_printing_at=50)

Søketekst:
        "Alltid i jobb" "Mista/sagt opp jobben" "Komme i jobb" "Aldri i jobb"
Match:
        hvis han/hun er midlertidig arbeidsufør på grunn av sykdom eller ulykke.
Likhet:
        0.592862606048584

Indekser:
            Nynorsk/søketekst:  0
            Bokmål/treff:       5745
_______________________________________________________________

Søketekst:
        '
Match:
        .
Likhet:
        0.8640571236610413

Indekser:
            Nynorsk/søketekst:  1
            Bokmål/treff:       38
_______________________________________________________________

Søketekst:
        - barn av låntakaren sin ektefelle som bur saman med låntakaren minst 40 prosent av tida
Match:
        Barna må bo hos deg minst 40 prosent av tiden for at du skal få mer stipend og lån.
Likhet:
        0.7128099203109741

Indekser:
            Nynorsk/søketekst:  5
            Bokmål/treff:       967
_______________________________________________________________

Søketekst:
        - barn av låntakaren sin sambuar som bur saman med låntakaren minst 40 prosent av tida, dersom låntakaren og sambuaren i tillegg har felles barn
Match:
        Du som har barn, kan få ekstra lån og stipend. Hovedregelen er at barna er under 16 år, og at de bor sammen med deg minst 40 prosent av tiden.
Likhet:
        0.6558802723884583

Indekser:
            Nynorsk/søketekst:  6
            Bokmål/treff:       1860
_______________________________________________________________

Søketekst:
        - barn av låntakaren sin sambuar som bur saman med låntakaren minst 40 prosent av tida, dersom låntakaren og sambuaren i tillegg har felles barn Låntakarar kan få sletta delar av utdanningsgjelda dersom dei har vore busette og yrkesaktive i Finnmark eller i ein av kommunane Lyngen, Storfjord, Kåfjor
Match:
        Bokmål Ordningen gjelder for låntakere som er bosatt og yrkesaktive i Finnmark og i disse kommunene i Nord-Troms: Lyngen, Storfjord, Kåfjord, Skjervøy, Nordreisa, Kvænangen og Karlsøy. Ordningen omfatter også yrkesaktive leger i andre utvalgte kommuner. Vi henter informasjon om bosted fra Folkeregis
Likhet:
        0.864072322845459

Indekser:
            Nynorsk/søketekst:  7
            Bokmål/treff:       1073
_______________________________________________________________

Søketekst:
        - barn av låntakaren sin sambuar som bur saman med låntakaren minst 40 prosent av tida, dersom søkjaren og sambuaren i tillegg har felles barn
Match:
        Hvis du ikke er registrert på samme adresse som barnet, må du sende inn dokumentasjon som viser at du har minst 40 prosent samvær (for eksempel samværsavtale signert av begge foreldrene)
Likhet:
        0.6692414283752441

Indekser:
            Nynorsk/søketekst:  8
            Bokmål/treff:       2890
_______________________________________________________________

Søketekst:
        0 39 304 182 104 67 32 18 10 11 0 767 1-200k 1 159 6 305 4 490 3 510 2 093 943 407 220 85 0 19 212 200k- # 500k 268 2 460 1 937 2 286 1 887 1 348 539 258 81 0 11 064 500k- 1mill 67 554 408 535 705 620 332 175 84 0 3 480 1mill- # 3mill 5 291 343 645 1 156 1 500 1 078 777 382 0 6 177 3mill- # 5mill 0
Match:
        2002 -353 000 000 375 876 289 -22 876 289 2003 -1 482 200 000 1 537 280 481 -55 080 481 2004 -3 126 000 000 2 837 271 551 288 728 449 2005 -4 377 774 000 4 134 008 826 243 765 174 2006 -4 379 980 000 4 086 493 846 293 486 154 2007 -4 124 900 000 4 076 287 999 48 612 001 2008 -4 098 600 000 4 038 731
Likhet:
        0.8566968441009521

Indekser:
            Nynorsk/søketekst:  9
            Bokmål/treff:       314
_______________________________________________________________

Søketekst:
        0% 5% 10% 15% 20% 25% < -100k -100k til - 50k -50k til - 20k -20k til -1 Inga endring +1 til 20k +20k til 50k +50k til 100k >+100k Enkeltståande (n=23 663) Tilbakevendande (n=12 967) Vedvarande (n=6 336) 0% 10% 20% 30% 40% 50% 60% 70% "Alltid i jobb" "Mista/sagt opp jobben" "Komme i jobb" "Aldri i j
Match:
        e fag Helse-, sosial- og idrettsfag -6 348,3 (435,4) -6 326,5 (435,8) -3 681,7 (432,4) Øvrige fagfelt og uoppgitt -8 298,5 (665,5) -8 335,2 (665,9) -5 856,6 (646,8) Masterstudier 5 952,4 (260,9) 5 855,6 (262,6) 4 247,5 (255,7) Foreldres høyeste utdanning når 16 år (grunnskole ref): Videregående 1 31
Likhet:
        0.7593162059783936

Indekser:
            Nynorsk/søketekst:  10
            Bokmål/treff:       5689
_______________________________________________________________

Søketekst:
        01.01.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 01.01.2020 Sbanken ASA Boliglån 50 % 2,75 % 01.01.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 01.01.2020 NORDirektebank (Skagerrak Sparebank) Boliglån inntil 60 % 2,89 % 01.01.2020 Gjensidige Bank Boliglån inntil 50 % 2,91 %
Match:
        02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 02.03.2022 OBOS-banken AS Bo
Likhet:
        0.9350517988204956

Indekser:
            Nynorsk/søketekst:  12
            Bokmål/treff:       62
_______________________________________________________________

Søketekst:
        01.09.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 01.09.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 01.09.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 01.09.2021 OBOS-banken AS Boliglån 50 % 1,57 % 01.09.2021 Sunndal Sparebank Bol
Match:
        29.12.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 29.12.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 29.12.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 29.12.2021 OBOS-banken AS Boliglån 50 % 1,82 % 29.12.2021 KLP Banken AS Boliglå
Likhet:
        0.9479497671127319

Indekser:
            Nynorsk/søketekst:  14
            Bokmål/treff:       449
_______________________________________________________________

Søketekst:
        03.02.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.02.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.02.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.02.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.02.2021 Fana Spareba
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9495526552200317

Indekser:
            Nynorsk/søketekst:  18
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        04.03.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 04.03.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 04.03.2020 Sbanken ASA Boliglån 50 % 2,75 % 04.03.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 04.03.2020 Nordea Direct Boliglån inntil 50 % 2,91 %
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9222737550735474

Indekser:
            Nynorsk/søketekst:  20
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        05.02.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 05.02.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 05.02.2020 Sbanken ASA Boliglån 50 % 2,75 % 05.02.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 05.02.2020 Gjensidige Bank Boliglån inntil 50 % 2,91 %
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9214978814125061

Indekser:
            Nynorsk/søketekst:  24
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        05.05.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 05.05.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 05.05.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 05.05.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 05.05.2021 Fana Spareba
Match:
        24.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 24.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 24.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 24.11.2021 OBOS-banken AS Boliglån 50 % 1,82 % 24.11.2021 KLP Banken AS Boliglå
Likhet:
        0.9383913278579712

Indekser:
            Nynorsk/søketekst:  25
            Bokmål/treff:       375
_______________________________________________________________

Søketekst:
        06.11.2019 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 06.11.2019 Sbanken ASA Boliglån 50 % 2,75 % 06.11.2019 Fana Sparebank Nettlån Bolig 50 % 2,80 % 06.11.2019 NORDirektebank (Skagerrak Sparebank) Boliglån inntil 60 % 2,89 % 06.11.2019 Gjensidige Bank Boliglån inntil 50 % 2,91 % 1
Match:
        06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.2020
Likhet:
        0.9372709393501282

Indekser:
            Nynorsk/søketekst:  28
            Bokmål/treff:       93
_______________________________________________________________

Søketekst:
        08.01.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 08.01.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 08.01.2020 Sbanken ASA Boliglån 50 % 2,75 % 08.01.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 08.01.2020 Gjensidige Bank Boliglån inntil 50 % 2,91 %
Match:
        09.08.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 09.08.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 09.08.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,58% 09.08.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,68% 09.08.2022 Sbanken ASA Boli
Likhet:
        0.9248161315917969

Indekser:
            Nynorsk/søketekst:  31
            Bokmål/treff:       114
_______________________________________________________________

Søketekst:
        08.02.2022
Match:
        Publisert 21.2.2022:
Likhet:
        0.7276034355163574

Indekser:
            Nynorsk/søketekst:  32
            Bokmål/treff:       4471
_______________________________________________________________

Søketekst:
        08.04.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 08.04.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 08.04.2020 Sbanken ASA Boliglån 50 % 2 % 08.04.2020 Nordea Direct Boliglån inntil 50 % 2,08 % 08.04.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 %
Match:
        03.08.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 03.08.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 03.08.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,58% 03.08.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,68% 03.08.2022 Nordea Direct Bo
Likhet:
        0.9208086729049683

Indekser:
            Nynorsk/søketekst:  33
            Bokmål/treff:       70
_______________________________________________________________

Søketekst:
        09.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 09.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 09.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 09.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 09.06.2021 Sunndal Sparebank Bol
Match:
        29.12.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 29.12.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 29.12.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 29.12.2021 OBOS-banken AS Boliglån 50 % 1,82 % 29.12.2021 KLP Banken AS Boliglå
Likhet:
        0.9429879188537598

Indekser:
            Nynorsk/søketekst:  37
            Bokmål/treff:       449
_______________________________________________________________

Søketekst:
        1 230 1 650 1 240 680 7 % 3 % 4 % 4 %
Match:
        2002 6 000 2003 12 000 2004 60 802 2005 181 822 2006 305 595 2007 244 716 2008 340 802 2009 570 223 2010 1 227 531 2011 2 279 014 2012 4 213 123 2013 7 701 446 2014 60 733 960 2015 141 948 840 2016 286 002 646 2017 1 275 466 033 2018 5 286 611 390 2019 0
Likhet:
        0.7626595497131348

Indekser:
            Nynorsk/søketekst:  40
            Bokmål/treff:       319
_______________________________________________________________

Søketekst:
        1 Sjå for eksempel for ei liste over offentlege og private universitet etter land. 2 Frøhlich (2007) klassifiserer for-profit lærestader etter eigarskap og finansiering: For at ein lærestad skal vere for-profit må den vere i privat eigarskap og ha privat finansiering. I tillegg er forteneste eit sen
Match:
        Fondets kapital er et uttrykk for de estimerte fordringene som ligger i kundenes forskriftsfestede rett til konvertering av studielån til stipend etter avlagt eksamen. Kapitalen bevilges årlig over statsbudsjettet under kap. 2410 – Statens lånekasse for utdanning, post 50 – Avsetning til utdanningss
Likhet:
        0.5914443135261536

Indekser:
            Nynorsk/søketekst:  41
            Bokmål/treff:       2276
_______________________________________________________________

Søketekst:
        1 Tilleggsstipendet har i forskriftene f.o.m. 2020–2021 bytt namn til «Utvida stipend til dekning av skulepengar ved utvalde lærestader». Vi vil i dette dokumentet omtale det ved det gamle namnet «tilleggsstipend».
Match:
        Endrer praksis for tilleggsstipend
Likhet:
        0.7959810495376587

Indekser:
            Nynorsk/søketekst:  42
            Bokmål/treff:       2052
_______________________________________________________________

Søketekst:
        1. Samandrag .............................................................................................................................................5 2. Bakgrunn ....................................................................................................................................
Match:
        4.5.6 Individuell utvikling ............................................................................................................. 35 5. Vurdering av framtidsutsikter ......................................................................................................... 35 6. Årsregnskap ..
Likhet:
        0.9424899816513062

Indekser:
            Nynorsk/søketekst:  43
            Bokmål/treff:       565
_______________________________________________________________

Søketekst:
        10 Vi har berre data på kor mykje lån og stipend kundane har blitt tildelt. Tala er dermed ikkje eit uttrykk for kor mykje dei har betalt i skolepengar, berre kor mykje dei har blitt tildelt. Det kan vere fleire årsaker til at studenten ikkje har blitt tildelt skolepengelån: dersom studenten ikkje h
Match:
        Fremfor alt er skolepenger interessant med tanke på Lånekassens finansiering av studentenes utdanningskostnader. Prinsippet er at man får utbetalt det beløpet man faktisk skal betale til lærestedet, inntil en viss grense. Studenter i Norge og andre nordiske land får hele støtten i form av lån. Av om
Likhet:
        0.863921046257019

Indekser:
            Nynorsk/søketekst:  47
            Bokmål/treff:       2520
_______________________________________________________________

Søketekst:
        10.–17. april 1. mai 10.–17. juni 1. juli 10.–17. august 1. september 10.–17. oktober 1. november 10.–17. desember 1. januar Inngåing av fastrenteavtale i Lånekassen er ikkje omfatta av reglane om angrerett i finansavtaleloven. Låntakaren kan derfor ikkje trekkje tilbake søknaden om fast rente etter
Match:
        I dette delkapitlet skal vi se på hvordan det går med mottakerne av flyktningstipendet i tilbakebetalingsfasen. Vi skal se på hvor stor andel som får studielånet sitt oppsagt midlertidig (10.1) og permanent (10.2), begge deler en form for mislighold. Vi skal sammenligne resultatene med alle tilbakeb
Likhet:
        0.8440210819244385

Indekser:
            Nynorsk/søketekst:  51
            Bokmål/treff:       3112
_______________________________________________________________

Søketekst:
        106 793
Match:
        28467
Likhet:
        0.637201189994812

Indekser:
            Nynorsk/søketekst:  52
            Bokmål/treff:       445
_______________________________________________________________

Søketekst:
        11 717
Match:
        11
Likhet:
        0.7298008799552917

Indekser:
            Nynorsk/søketekst:  53
            Bokmål/treff:       164
_______________________________________________________________

Søketekst:
        11.03.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 11.03.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 11.03.2020 Sbanken ASA Boliglån 50 % 2,75 % 11.03.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 11.03.2020 Nordea Direct Boliglån inntil 50 % 2,91 %
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9216973781585693

Indekser:
            Nynorsk/søketekst:  54
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        12 I datagrunnlaget vårt har vi berre inkludert første lærestad for studentar som har vore på språkleg tilrettelegging ved fleire lærestader i same land. Svært få av opphalda er registrert med meir enn ein lærestad (32 opphald totalt i løpet av perioden), men ei overvekt av desse (22) gjeld studenta
Match:
        Microdata.no inneholder en rekke variabler som er relevante å ha med når vi ønsker å undersøke bruken av studiestøtte blant studenter med innvandrerbakgrunn (se avsnitt 3). Under følger en beskrivelse av variablene vi inkluderer i vår analyse. En del av variablene er tidspunktbestemte og oppdateres
Likhet:
        0.7429875135421753

Indekser:
            Nynorsk/søketekst:  57
            Bokmål/treff:       4060
_______________________________________________________________

Søketekst:
        12.02.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 12.02.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 12.02.2020 Sbanken ASA Boliglån 50 % 2,75 % 12.02.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 12.02.2020 Gjensidige Bank Boliglån inntil 50 % 2,91 %
Match:
        09.08.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 09.08.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 09.08.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,58% 09.08.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,68% 09.08.2022 Sbanken ASA Boli
Likhet:
        0.9252125024795532

Indekser:
            Nynorsk/søketekst:  58
            Bokmål/treff:       114
_______________________________________________________________


#### Falsk negativ

In [39]:
i = 90
print(search_result[i])
print(nynorsk_texts_flat[i])
print("\n___________\n")
print(bokmål_texts_flat[search_result[i][0]["corpus_id"]])

[{'corpus_id': 283, 'score': 0.9358025789260864}]
2 heimreiser

___________

2 hjemreiser

## Konklusjon
Vi får flest matches med naiv cutoff (vi vet at 71.07% av avsnittene er innenfor modellens makslengde)  
Vi har ikke gulldata å sammenlikne med, så det er ikke så godt å si helt sikkert om dette er den beste metoden.

In [41]:
pd.DataFrame(sent_alignment_results).T.sort_values("matches")

                    matches  percent of sents  threshold
string_comparison     341.0              0.08        NaN
naiv_cutoff_biter    2237.0             60.61       0.95
max_pooling_biter    2252.0             61.01       0.95
mean_pooling_biter   2294.0             62.15       0.95
naiv_cutoff          2343.0             63.48       0.95