# Eksperimenter med lånekassens dokumenter med LaBSE
De har mye parallelldata

In [1]:
from pathlib import Path
import pandas as pd
from hemmelig import data_path

p = Path(data_path)

filer = [e for e in p.iterdir() if "lanekassen" in e.name]

dfs = []
for e in filer:
    with e.open("rb") as f:
        dfs.append(pd.read_json(e, lines=True))


df = pd.concat(dfs)
df

,doc_hash,lang,url,domain,date,mimetype,fulltext
0,b5fc6f81d5709f0051da1964c3900e7ca8df65f7,nno,http://lanekassen.no/globalassets/brosjyrer-fe...,lanekassen.no,2022-12-19 01:53:28+00:00,pdf,[Er du flyktning? Du blir rekna som flyktning ...
1,1fbe096fdfdd9916be1313006ac5cf44ac650231,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 01:57:14+00:00,pdf,"[, , Du kan bruke dette skjemaet dersom du tar..."
2,582aaf9a510b3bde21b5b3e13ffc3453d6ca8174,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 01:57:21+00:00,pdf,"[, , Det er viktig at du les informasjonen på ..."
3,32e23cf05e4db850a9e2f622c2edd0482572677e,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 02:00:45+00:00,pdf,[Nynorsk Skjema for lærlinglønn Kor stort bort...
4,4ea46648c7ce59fe0c39b45779ed6402d8b41369,nno,http://lanekassen.no/globalassets/skjemaer-fel...,lanekassen.no,2022-12-19 02:01:01+00:00,pdf,[Nynorsk Skjema I – artikkelnr. 9001550 – nyno...
...,...,...,...,...,...,...,...
72,e29a43da7165d92d937c56416d50f563201ab5fa,nob,http://lanekassen.no/siteassets/skjemaer-og-fi...,lanekassen.no,2022-12-19 02:50:18+00:00,pdf,"[, , 01.01.2020 Storebrand Bank ASA 70 % Bolig..."
73,c120ee7f582c758ae392b8f90795a7c664c39e90,nob,http://lanekassen.no/siteassets/skjemaer-og-fi...,lanekassen.no,2022-12-19 02:50:23+00:00,pdf,"[, , 06.11.2019 Storebrand Bank ASA 70 % Bolig..."
74,553101a9b0a9fac935cf31e5dd59555d23ecbefe,nob,https://statistikk.lanekassen.no/globalassets/...,lanekassen.no,2022-12-19 03:10:41+00:00,pdf,"[, , Flyktningstipendet Mottakere av flyktning..."
75,1f14c7bcc564613f79be7a8cae1a946e27cfd755,nob,https://statistikk.lanekassen.no/globalassets/...,lanekassen.no,2022-12-19 03:10:44+00:00,pdf,"[, , Tall og fakta om Lånekassens kunder og or..."
76,ad84c32284570d5883b5c12276961d0a74ec1649,nob,https://statistikk.lanekassen.no/globalassets/...,lanekassen.no,2022-12-19 03:10:46+00:00,pdf,[Bruk av studiestøtte blant studenter med innv...

In [2]:
nynorske = df[df.lang == "nno"]
nynorske.index = range(len(nynorske))

bokmålske = df[df.lang == "nob"]
bokmålske.index = range(len(bokmålske))

len(nynorske), len(bokmålske)

(256, 310)

Lim sammen avsnittene i hvert dokument

In [3]:
nynorsk_texts_joined = nynorske.fulltext.apply(lambda x: "\n".join(x))
bokmål_texts_joined = bokmålske.fulltext.apply(lambda x: "\n".join(x))

Last inn fasit

In [4]:
hash_to_i_nn = {e.doc_hash: e.Index for e in nynorske.itertuples()}
hash_to_i_bm = {e.doc_hash: e.Index for e in bokmålske.itertuples()}

fasit = pd.read_csv("lanekassen_fasit.csv")
fasit_set = set(zip(fasit.nynorsk_doc_hash, fasit.bokmål_doc_hash))

def compare_matches_to_fasit(matches):
    nn_i, bm_i = zip(*[(i, match["corpus_id"]) for i, match in matches])
    hash_matches = set(zip(nynorske.iloc[list(nn_i)].doc_hash, bokmålske.iloc[list(bm_i)].doc_hash))

    hits = fasit_set.intersection(hash_matches)
    misses = fasit_set - hash_matches
    
    hits_indices = [(hash_to_i_nn[nn_doc_hash], hash_to_i_bm[bm_doc_hash]) for nn_doc_hash, bm_doc_hash in hits]
    misses_indices = [(hash_to_i_nn[nn_doc_hash], hash_to_i_bm[bm_doc_hash]) for nn_doc_hash, bm_doc_hash in misses]
    
    return (hits_indices, misses_indices)

Last inn modellen

In [5]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('sentence-transformers/LaBSE', device="cuda")

# Tell hvor mange dokumenter og avsnitt som er for lange for modellen

In [6]:
max_len = model.max_seq_length
tokenizer = model.tokenizer

nynorsk_documents_token_sequence_lengths = [len(tokenizer.tokenize(text)) for text in nynorsk_texts_joined]

under_max_len = 0
over_max_len = 0
zero_len = 0
for token_len in nynorsk_documents_token_sequence_lengths:
    if token_len:
        if token_len > max_len:
            over_max_len += 1
        else:
            under_max_len += 1
    else:
        zero_len += 1

assert zero_len == 0

print(f"""
Av de {len(nynorsk_documents_token_sequence_lengths)} nynorske dokumentene er:
    {under_max_len} under LaBSE sin makslengde 
    {over_max_len}  over LaBSE sin makslengde 
Altså er {round(under_max_len/len(nynorsk_documents_token_sequence_lengths)*100, 2)}% av dokumentene under makslengden 
""")

bokmål_documents_token_sequence_lengths = [len(tokenizer.tokenize(text)) for text in bokmål_texts_joined]

under_max_len = 0
over_max_len = 0
zero_len = 0
for token_len in bokmål_documents_token_sequence_lengths:
    if token_len:
        if token_len > max_len:
            over_max_len += 1
        else:
            under_max_len += 1
    else:
        zero_len += 1

assert zero_len == 0

print(f"""
Av de {len(bokmål_documents_token_sequence_lengths)} dokumentene på bokmål er:
    {under_max_len} under LaBSE sin makslengde 
    {over_max_len}  over LaBSE sin makslengde 
Altså er {round(under_max_len/len(bokmål_documents_token_sequence_lengths)*100, 2)}% av dokumentene under makslengden 
""")

Token indices sequence length is longer than the specified maximum sequence length for this model (1802 > 512). Running this sequence through the model will result in indexing errors

Av de 256 nynorske dokumentene er:
    48 under LaBSE sin makslengde
    208  over LaBSE sin makslengde
Altså er 18.75% av dokumentene under makslengden


Av de 310 dokumentene på bokmål er:
    63 under LaBSE sin makslengde
    247  over LaBSE sin makslengde
Altså er 20.32% av dokumentene under makslengden

In [7]:
max_len = model.max_seq_length
tokenizer = model.tokenizer

token_sequence_lengths = df.fulltext.apply(lambda x: [len(tokenizer.tokenize(e)) for e in x])

under_max_len = 0
over_max_len = 0
zero_len = 0
for e in token_sequence_lengths:
    for token_len in e:
        if token_len:
            if token_len > max_len:
                over_max_len += 1
            else:
                under_max_len += 1
        else:
            zero_len += 1

print(f"""
Det er totalt {sum((under_max_len, over_max_len))} ikke-tomme avsnitt/setninger (og {zero_len} er tomme)
Av de ikke-tomme avsnittene er:
    {under_max_len} under LaBSE sin makslengde 
    {over_max_len}  over LaBSE sin makslengde 
Altså er {round(under_max_len/sum((under_max_len, over_max_len))*100, 2)}% av de ikke-tomme avsnittene under makslengden 
""")

Det er totalt 12491 ikke-tomme avsnitt/setninger (og 4377 er tomme)
Av de ikke-tomme avsnittene er:
    11648 under LaBSE sin makslengde
    843  over LaBSE sin makslengde
Altså er 93.25% av de ikke-tomme avsnittene under makslengden

# Dokumentalignment
Finn den likeste bokmål-dokument-embeddingen for hver nynorsk-dokument-embedding.  
Her kan man eksperimentere med ulike terskelverdier for å akseptere en match (trade-off med precision og recall)

In [8]:
doc_alignment_results = {}

## Aksepter cut-off

In [9]:
import numpy as np 

emb_path = Path("embeddings/labse/texts_joined.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    bokmål_embeddings = model.encode(bokmål_texts_joined)
    nynorsk_embeddings = model.encode(nynorsk_texts_joined)
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
non_matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] <= threshold]


hits, misses = compare_matches_to_fasit(matches)
doc_alignment_results["naiv_cutoff"] = {"matches": len(matches), "threshold": threshold, "percent of docs": round(len(matches)/len(nynorske)*100, 2), "hits": len(hits), "misses": len(misses)}

### Inspiser matches

In [10]:
from utils import print_matches

print_matches(matches, nynorsk_texts_joined, bokmål_texts_joined)
# print_matches(non_matches, nynorsk_texts_joined, bokmål_texts_joined)

Søketekst:
        Er du flyktning? Du blir rekna som flyktning dersom du er utanlandsk statsborgar og har fått vern (asyl) i Noreg. Du må vere registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Noreg som er godkjend f
Match:
        Er du flyktning? Du regnes som flyktning hvis du er utenlandsk statsborger og har fått beskyttelse (asyl) i Norge. Du må være registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Norge som er godkjent
Likhet:
        0.9881253242492676

Indekser:
            Nynorsk/søketekst:  0
            Bokmål/treff:       241
_______________________________________________________________

Søketekst:


Du kan bruke dette skjemaet dersom du tar høgare utdanning eller fagskoleutdanning i Noreg eller Norden, og du skal søke om støtte til studieopphald i eit anna land.

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn

Kva studieprogram følger du i Noreg/Norden? I k
Match:


Du kan bruke dette skjemaet hvis du tar høyere utdanning eller fagskoleutdanning i Norge eller Norden, og du skal søke om støtte til studieopphold i et annet land.

Skjemaet laster du opp på Dine Sider, eller du kan sende det i posten til Lånekassen behandler personopplysninger i samsvar med regel
Likhet:
        0.9761447906494141

Indekser:
            Nynorsk/søketekst:  1
            Bokmål/treff:       233
_______________________________________________________________

Søketekst:


Det er viktig at du les informasjonen på side 2 i dette søknadsskjemaet. Hugs å sende inn ein , dersom du ikkje har gjort det.

Denne søknaden lastar du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn

Nam
Match:


Det er viktig at du leser informasjonen på side 2 i dette søknadsskjemaet. Husk å sende inn en , hvis du ikke allerede har gjort det.

Denne søknaden laster du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomna
Likhet:
        0.9869408011436462

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       234
_______________________________________________________________

Søketekst:
        Nynorsk Skjema for lærlinglønn Kor stort bortebuarstipend du kan få, er avhengig av kor mykje du tener som lærling. Derfor må arbeidsgivaren din fylle ut dette skjemaet for å stadfeste lønna di. Vi kan ikkje behandle søknaden din før du har sendt opplysningar om lønna di. Du kan laste opp ferdig utf
Match:
        Bokmål Skjema for lærlinglønn Hvor stort borteboerstipend du kan få, er avhengig av hvor mye du tjener som lærling. Derfor må arbeidsgiveren din fylle ut dette skjemaet for å bekrefte lønnen din. Vi kan ikke behandle søknaden din før du har sendt opplysninger om lønnen din. Du kan laste opp ferdig u
Likhet:
        0.9752347469329834

Indekser:
            Nynorsk/søketekst:  3
            Bokmål/treff:       235
_______________________________________________________________

Søketekst:
        Nynorsk Skjema I – artikkelnr. 9001550 – nynorsk – 01.2022 – organisasjonsnummer NO 960 885 406 Namn, adresse og postnummer/-stad Personnummer Fødselsdato Kundenummer i Lånekassen Søknad om betalingsutsetting og/eller sletting av renter Du kan bruke nettsøknaden på

Kva månad/månader søker du om uts
Match:
        Bokmål Skjema I – artikkelnr. 9001550 – bokmål – 01.2022 – organisasjonsnummer NO 960 885 406 Navn, adresse og postnummer/-sted Personnummer Fødselsdato Kundenummer i Lånekassen Søknad om betalingsutsettelse og/eller sletting av renter Du kan bruke nettsøknaden på

Hvilken måned / hvilke måneder søk
Likhet:
        0.9899375438690186

Indekser:
            Nynorsk/søketekst:  4
            Bokmål/treff:       237
_______________________________________________________________

Søketekst:


Du kan logge inn på og endre kontonummeret ditt dersom du har oppretta ein ny konto som du vil bruke dersom du vil ha pengane inn på ein annan av kontoane dine Lånekassen overfører berre lån og stipend til ein norsk konto som du eig. Dersom du nettopp har fått tildelt eit nytt kontonummer kan det
Match:


Du kan logge inn på og endre kontonummeret ditt hvis du har opprettet en ny konto som du vil bruke hvis du vil ha pengene inn på en annen av kontoene dine Lånekassen overfører bare lån og stipend til en norsk konto som du eier. Hvis du nettopp har fått tildelt et nytt kontonummer kan det ta noen d
Likhet:
        0.9737570285797119

Indekser:
            Nynorsk/søketekst:  6
            Bokmål/treff:       238
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer Poststad

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Eg er kjend med vilkåra for fast rente som eg finn i kapittel 2 i Stad og dato Underskrift Søknaden må vere komme
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer Poststed

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Jeg er kjent med vilkårene for fast rente som jeg finner i kapittel 2 i Sted og dato Underskrift Søknaden må være
Likhet:
        0.9908832311630249

Indekser:
            Nynorsk/søketekst:  7
            Bokmål/treff:       239
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer og poststad Telefon

Etternamnet til fullmaktshavaren Fornamnet og mellomnamnet til fullmaktshavaren Fullmakta er gyldig Frå Til

Stad og dato Underskrifta di

Du kan laste opp fullmaktsskjemaet p
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer og poststed Telefon

Fullmaktshavers etternavn Fullmaktshavers fornavn og mellomnavn Fullmakten er gyldig Fra Til

Sted og dato Din underskrift Du kan laste opp fullmaktsskjemaet på Dine sider ell
Likhet:
        0.9903063774108887

Indekser:
            Nynorsk/søketekst:  8
            Bokmål/treff:       240
_______________________________________________________________

Søketekst:
        Du finn informasjon om vilkår og dokumentasjon på neste side. Søknad om sjukestipend Nynorsk Skjema S – artikkelnummer 9001561 – nynorsk – 06.2022 – Organisasjonsnummer NO 960 885 406 Namn, adresse og postnummer/-stad Personnummer Fødselsdato Kundenummer i Lånekassen

Eigen sjukdom Sjukt barn Barnet
Match:
        Du finner informasjon om vilkår og dokumentasjon på neste side. Søknad om sykestipend Bokmål Skjema S – artikkelnummer 9001561 – bokmål – 06.2022– Organisasjonsnummer NO 960 885 406 Navn, adresse og postnummer/-sted Personnummer Fødselsdato Kundenummer i Lånekassen

Egen sykdom Sykt barn Barnets fød
Likhet:
        0.9911423921585083

Indekser:
            Nynorsk/søketekst:  12
            Bokmål/treff:       250
_______________________________________________________________

Søketekst:
        Søknaden fortset på neste side

Tilleggsstipend kan bli gitt i tillegg til vanleg utdanningsstøtte og er på inntil 4 000 kroner per månad. Stipendet er meint for søkarar som er i stand til å studere, men som på grunn av nedsett funksjonsevne bruker så mykje tid og krefter på å studere, at dei ikkje
Match:
        Søknaden fortsetter på neste side

Tilleggsstipend kan bli gitt i tillegg til vanlig utdanningsstøtte og er på inntil 4 000 kroner per måned. Stipendet er ment for søkere som er i stand til å studere, men som på grunn av nedsatt funksjonsevne bruker så mye tid og krefter på å studere, at de ikke kan
Likhet:
        0.9879758954048157

Indekser:
            Nynorsk/søketekst:  13
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        Skjemaet fortset på neste side

Søknaden gjeld for søkarar som på grunn av nedsett funksjonsevne ikkje er i stand til å ha lønna arbeid i sommarferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og førebu seg til neste semester. Med lønna arbeid meiner vi alt arbeid der lønna er s
Match:
        Skjemaet fortsetter på neste side

Søknaden gjelder for søkere som på grunn av nedsatt funksjonsevne ikke er i stand til å ha lønnet arbeid i sommerferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og forberede seg til neste semester. Med lønnet arbeid menes alt arbeid hvor lønna
Likhet:
        0.975484311580658

Indekser:
            Nynorsk/søketekst:  14
            Bokmål/treff:       252
_______________________________________________________________

Søketekst:
        Sletting av gjeld for lærarar i grunnskolen Nynorsk Skjema2 Namn Oppteningsperiode frå og med dato

Oppteningsperiode til og med dato Frå 2020 er Finnmark og Troms slått saman til det nye fylket Troms og Finnmark, men det påverkar ikkje ordninga med sletting av gjeld. For å få sletta gjeld må du fra
Match:
        Sletting av gjeld for lærere i grunnskolen Bokmål Skjema L – Bokmål – 02

Fra 2020 er Finnmark og Troms slått sammen til det nye fylket Troms og Finnmark, men det påvirker ikke ordningen med sletting av gjeld. For å få slettet gjeld må du fortsatt arbeide i det som tidligere var regionen Finnmark og
Likhet:
        0.9618865251541138

Indekser:
            Nynorsk/søketekst:  15
            Bokmål/treff:       254
_______________________________________________________________

Søketekst:


Etternamn Fornamn og mellomnamn Fødselsdato (dag – månad – år)

Kva utdanning har eleven teke? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førarkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – månad – år

Oppgi siste dato elev
Match:


Etternavn Fornavn og mellomnavn Fødselsdato (dag – måned – år)

Hvilken utdanning har eleven tatt? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førerkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – måned – år

Oppgi siste dato
Likhet:
        0.9896743297576904

Indekser:
            Nynorsk/søketekst:  16
            Bokmål/treff:       255
_______________________________________________________________

Søketekst:


Skal fyllast ut av den administrative leiaren ved lærestaden

Namn (fornamn og etternamn) Namn på lærestaden Administratoren si e-postadresse (direkte e-post, ikkje postmottak) Administratoren sitt telefonnummer Administratoren sitt mobilnummer

Lånekassen treng signatur til den administrative lei
Match:


Skal fylles ut av den administrative lederen ved lærestedet

Navn (fornavn og etternavn) Navn på lærestedet Administratorens e-postadresse (direkte e-post, ikke postmottak) Administratorens telefonnummer Administratorens mobilnummer

Lånekassen trenger den administrative lederens signatur for å gi
Likhet:
        0.9912883043289185

Indekser:
            Nynorsk/søketekst:  17
            Bokmål/treff:       257
_______________________________________________________________

Søketekst:
        Søknaden held fram på neste side

,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden
Match:
        Søknaden fortsetter på neste side

,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og do
Likhet:
        0.9913134574890137

Indekser:
            Nynorsk/søketekst:  18
            Bokmål/treff:       258
_______________________________________________________________

Søketekst:


01.09.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 01.09.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 01.09.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 01.09.2021 OBOS-banken AS Boliglån 50 % 1,57 % 01.09.2021 Sunndal Sparebank B
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9657115936279297

Indekser:
            Nynorsk/søketekst:  21
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9537823796272278

Indekser:
            Nynorsk/søketekst:  23
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:
        Universitet og høgskole
Hoyskole og universitet i norge
Studere i Noreg
Utdanning ved alle universitet og godkjente høgskolar gir rett til støtte frå Lånekassen til å ta 480 studiepoeng. Det er det same som åtte år med fulltidsstudium.
Alle studentar får basislån
Basislån kan alle studentar få, og d
Match:
        Universitet og høgskole
Her finner du informasjon om hvor mye lån og stipend du kan få, og hvor mye du kan tjene før du mister stipendet.
Hoyskole og universitet i Norge
Studere i Norge
Studier ved alle universiteter og godkjente høgskoler gir rett til støtte fra Lånekassen til å ta 480 studiepoeng.
Likhet:
        0.9732034206390381

Indekser:
            Nynorsk/søketekst:  34
            Bokmål/treff:       0
_______________________________________________________________

Søketekst:
        Kven har ikkje ungdomsrett?
Tek du opp igjen fag, har fullført vidaregåande opplæring tidlegare eller er over 24 år, har du ikkje lenger ungdomsrett. Du kan få stipend og lån frå Lånekassen, men etter dei same reglane som for høgare utdanning.
Match:
        Hvem har ikke ungdomsrett?
Tar du opp fag, har fullført tre år på videregående tidligere eller er over 24 år, har du ikke lenger ungdomsrett. Du kan få stipend og lån fra Lånekassen, men etter de samme reglene som for høyere utdanning.
Likhet:
        0.9655788540840149

Indekser:
            Nynorsk/søketekst:  35
            Bokmål/treff:       1
_______________________________________________________________

Søketekst:
        Fagskole
Fagskole
Fagskoleutdanning
Du kan få lån og stipend til fagskoleutdanningar som er godkjende av NOKUT.
Dersom du er usikker på om utdanninga di er godkjent for lån og stipend frå Lånekassen, kan du kontakte oss eller sjå NOKUT si oversikt over godkjende fagskoletilbod.
Alle studentar får ba
Match:
        Fagskole
Fagskole
Fagskoleutdanning
Du kan få lån og stipend til fagskoleutdanninger som er godkjent av NOKUT.
Hvis du er usikker på om utdanningen din er godkjent for lån og stipend fra Lånekassen, kan du spørre oss direkte eller se i NOKUT sin oversikt over akkrediterte fagskoletilbud.
Alle studen
Likhet:
        0.9904121160507202

Indekser:
            Nynorsk/søketekst:  36
            Bokmål/treff:       2
_______________________________________________________________

Søketekst:
        Lån og stipend for å gå på folkehøgskole
Er du elev på ein folkehøgskole, kan du få basislån i inntil ti månader.
Kva er basislån?
Basislån er det alle studentar kan få, og er namnet på det dei fleste kallar studielån. Du får ikkje ekstra lån til å dekke utgiftene ved linja du skal gå på, eller til
Match:
        Lån og stipend for å gå på folkehøgskole
Er du elev på en folkehøgskole, kan du få basislån i inntil ti måneder.
Hva er basislån?
Basislån er det alle studenter kan få, og er navnet på det de fleste kaller studielån. Du får ikke ekstra lån til å dekke utgiftene ved linjen du skal gå på, eller til re
Likhet:
        0.9950793981552124

Indekser:
            Nynorsk/søketekst:  37
            Bokmål/treff:       3
_______________________________________________________________

Søketekst:
        Bibel- eller kunstskole
Elever på bibelskole eller kunstskole kan få lån og stipend i inntil ti måneder
Bibelskole eller kunstskole er to ulike skoler. Går du på bibelskole eller kunstskole, får du ikkje lenger stipend slik du kanskje fekk på vidaregåande, men du får eit lån.
Du kan få eit basislån
Match:
        Bibel- eller kunstskole
Elever på bibelskole eller kunstskole kan få stipend og lån i inntil ti måneder
Bibelskole eller kunstskoler er to ulike typer skoler. Går du på bibelskole eller kunstskole, får du ikke lenger stipend slik du kanskje fikk på videregående, men du får et lån.
Du kan få et basis
Likhet:
        0.9933326244354248

Indekser:
            Nynorsk/søketekst:  38
            Bokmål/treff:       4
_______________________________________________________________

Søketekst:
        Du kan ikkje få lån og stipend dersom du berre skal ta førarkort.
Du kan berre få stipend og lån til førarkort dersom du tar det i samband med grunnutdanninga. Du må starte på, eller ta førerkortet innen tolv måneder før grunnutdanningen starter.
Du kan få skolepengelån til å dekke utgiftene til kur
Match:
        Du kan ikke få lån og stipend hvis du bare skal ta førerkort.
Du kan bare få stipend og lån til førerkort hvis du tar det i forbindelse med grunnutdanningen. Du må starte på, eller ta førerkortet innen tolv måneder før grunnutdanningen starter.
Du kan få skolepengelån til å dekke utgiftene til kurse
Likhet:
        0.9933665990829468

Indekser:
            Nynorsk/søketekst:  39
            Bokmål/treff:       5
_______________________________________________________________

Søketekst:
        Lån og stipend til sommarkurs
Til enkelte sommarkurs kan du få lån og stipend.
Basislån i inntil 2 månader
Du kan få basislån i inntil 2 månader for å ta sommarkurs. Basislån er det alle studentar kan få, og det dei fleste kallar studielån. Sommaren 2022 er basislånet 11 487 kroner per månad, og du
Match:
        Lån og stipend til sommerkurs
Til enkelte sommerkurs kan du få lån og stipend.
Basislån i inntil 2 måneder
Du kan få basislån i inntil 2 måneder for å ta sommerkurs. Basislån er det alle studenter kan få, og det de fleste kaller studielån. Sommeren 2022 er basislånet 11 487 kroner per måned, og du k
Likhet:
        0.9926384687423706

Indekser:
            Nynorsk/søketekst:  40
            Bokmål/treff:       6
_______________________________________________________________

Søketekst:
        at inntekt og formue er lågare enn grensene
Kva skal til for å få omgjering?
Det vanlege studielånet som alle får, blir kalla basislån. Opptil 40 prosent av basislånet kan bli til stipend.
Du må bu borte
Du kan ikkje få gjort om lån til stipend for periodar du har budd heime hos foreldra dine. Når d
Match:
        at inntekt og formue er lavere enn grensene
Hva skal til for å få omgjøring?
Det vanlige studielånet som alle får, kalles basislån. Opptil 40 prosent av basislånet kan bli til stipend.
Du må bo borte fra foreldrene dine
Du kan ikke få gjort om lån til stipend for perioder du har bodd hjemme hos fore
Likhet:

#### Falsk positiv
Eksempel på en falsk positiv.  
Noen lister av datoer og banker og renter blir veldig like

In [11]:
i = 21
print(search_result[i])
print(nynorsk_texts_joined[i][:250])
print("\n___________\n")
print(bokmål_texts_joined[search_result[i][0]["corpus_id"]][:250])

[{'corpus_id': 293, 'score': 0.9657115936279297}]


01.09.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 01.09.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 01.09.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 01.09.2021 OBOS-banken AS B

___________



03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Spareban

#### Falsk negativ

In [12]:
i = 80
print(search_result[i])
print(nynorsk_texts_joined[i][:250])
print("\n___________\n")
print(bokmål_texts_joined[search_result[i][0]["corpus_id"]][:250])

[{'corpus_id': 46, 'score': 0.9480304718017578}]
Personvern­erklæring
Kva er personopplysningar?
Ei personopplysning er ei opplysning som er med på å identifisere deg som enkeltperson. Det blir skilt mellom personopplysningar og særlege kategoriar (sensitive) personopplysningar.
Lånekassen er behan

___________

Personvern­erklæring
Hva er personopplysninger?
En personopplysning er en opplysning som er med på å identifisere deg som enkeltperson. Det skilles mellom personopplysninger og særlige kategorier (sensitive) personopplysninger.
Lånekassen er behandli

## Del opp avsnittene i biter mindre enn modellens makslengde og aggreger

In [13]:
from utils import tokenize_and_split_text

nynorsk_maxlen_parts = [tokenize_and_split_text(text, tokenizer=model.tokenizer, model_max_len=model.max_seq_length) for text in nynorsk_texts_joined]
bokmål_maxlen_parts = [tokenize_and_split_text(text, tokenizer=model.tokenizer, model_max_len=model.max_seq_length) for text in bokmål_texts_joined]

In [14]:
# from collections import Counter 
# pd.DataFrame(Counter([len(e) for e in nynorsk_maxlen_parts]).most_common(), columns=("antall lister", "antall dokumenter")).sort_values("antall lister")
# pd.DataFrame(Counter([len(e) for e in bokmål_maxlen_parts]).most_common(), columns=("antall lister", "antall dokumenter")).sort_values("antall lister")

## Bare send alle bitene gjennom

SentenceTransformers aggregerer ved å ta de to første tekstene i hver liste av tekster, og lage en vektor hvor hver halvdel er starten av hver av tekstene (fra starten og opp til 1/2 makslengde) adskilt med et sep-token

In [15]:
import numpy as np

emb_path = Path("embeddings/labse/maxlen_parts.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_maxlen_parts_1 = [e + [""] for e in nynorsk_maxlen_parts]
    bokmål_maxlen_parts_1 = [e + [""] for e in bokmål_maxlen_parts]
    
    bokmål_embeddings = model.encode(bokmål_maxlen_parts_1)
    nynorsk_embeddings = model.encode(nynorsk_maxlen_parts_1)
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]


hits, misses = compare_matches_to_fasit(matches)
doc_alignment_results["naiv_cutoff_biter"] = {"matches": len(matches), "threshold": threshold, "percent of docs": round(len(matches)/len(nynorske)*100, 2), "hits": len(hits), "misses": len(misses)}

### Inspiser matches

In [16]:
from utils import print_matches

print_matches(matches, nynorsk_texts_joined, bokmål_texts_joined)

Søketekst:
        Er du flyktning? Du blir rekna som flyktning dersom du er utanlandsk statsborgar og har fått vern (asyl) i Noreg. Du må vere registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Noreg som er godkjend f
Match:
        Er du flyktning? Du regnes som flyktning hvis du er utenlandsk statsborger og har fått beskyttelse (asyl) i Norge. Du må være registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Norge som er godkjent
Likhet:
        0.9743765592575073

Indekser:
            Nynorsk/søketekst:  0
            Bokmål/treff:       241
_______________________________________________________________

Søketekst:


Du kan bruke dette skjemaet dersom du tar høgare utdanning eller fagskoleutdanning i Noreg eller Norden, og du skal søke om støtte til studieopphald i eit anna land.

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn

Kva studieprogram følger du i Noreg/Norden? I k
Match:


Du kan bruke dette skjemaet hvis du tar høyere utdanning eller fagskoleutdanning i Norge eller Norden, og du skal søke om støtte til studieopphold i et annet land.

Skjemaet laster du opp på Dine Sider, eller du kan sende det i posten til Lånekassen behandler personopplysninger i samsvar med regel
Likhet:
        0.981036901473999

Indekser:
            Nynorsk/søketekst:  1
            Bokmål/treff:       233
_______________________________________________________________

Søketekst:


Det er viktig at du les informasjonen på side 2 i dette søknadsskjemaet. Hugs å sende inn ein , dersom du ikkje har gjort det.

Denne søknaden lastar du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn

Nam
Match:


Det er viktig at du leser informasjonen på side 2 i dette søknadsskjemaet. Husk å sende inn en , hvis du ikke allerede har gjort det.

Denne søknaden laster du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomna
Likhet:
        0.985571563243866

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       234
_______________________________________________________________

Søketekst:
        Nynorsk Skjema for lærlinglønn Kor stort bortebuarstipend du kan få, er avhengig av kor mykje du tener som lærling. Derfor må arbeidsgivaren din fylle ut dette skjemaet for å stadfeste lønna di. Vi kan ikkje behandle søknaden din før du har sendt opplysningar om lønna di. Du kan laste opp ferdig utf
Match:
        Bokmål Skjema for lærlinglønn Hvor stort borteboerstipend du kan få, er avhengig av hvor mye du tjener som lærling. Derfor må arbeidsgiveren din fylle ut dette skjemaet for å bekrefte lønnen din. Vi kan ikke behandle søknaden din før du har sendt opplysninger om lønnen din. Du kan laste opp ferdig u
Likhet:
        0.9846628904342651

Indekser:
            Nynorsk/søketekst:  3
            Bokmål/treff:       235
_______________________________________________________________

Søketekst:
        Nynorsk Skjema I – artikkelnr. 9001550 – nynorsk – 01.2022 – organisasjonsnummer NO 960 885 406 Namn, adresse og postnummer/-stad Personnummer Fødselsdato Kundenummer i Lånekassen Søknad om betalingsutsetting og/eller sletting av renter Du kan bruke nettsøknaden på

Kva månad/månader søker du om uts
Match:
        Bokmål Skjema I – artikkelnr. 9001550 – bokmål – 01.2022 – organisasjonsnummer NO 960 885 406 Navn, adresse og postnummer/-sted Personnummer Fødselsdato Kundenummer i Lånekassen Søknad om betalingsutsettelse og/eller sletting av renter Du kan bruke nettsøknaden på

Hvilken måned / hvilke måneder søk
Likhet:
        0.9909232258796692

Indekser:
            Nynorsk/søketekst:  4
            Bokmål/treff:       237
_______________________________________________________________

Søketekst:


Du kan logge inn på og endre kontonummeret ditt dersom du har oppretta ein ny konto som du vil bruke dersom du vil ha pengane inn på ein annan av kontoane dine Lånekassen overfører berre lån og stipend til ein norsk konto som du eig. Dersom du nettopp har fått tildelt eit nytt kontonummer kan det
Match:


Du kan logge inn på og endre kontonummeret ditt hvis du har opprettet en ny konto som du vil bruke hvis du vil ha pengene inn på en annen av kontoene dine Lånekassen overfører bare lån og stipend til en norsk konto som du eier. Hvis du nettopp har fått tildelt et nytt kontonummer kan det ta noen d
Likhet:
        0.9854365587234497

Indekser:
            Nynorsk/søketekst:  6
            Bokmål/treff:       238
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer Poststad

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Eg er kjend med vilkåra for fast rente som eg finn i kapittel 2 i Stad og dato Underskrift Søknaden må vere komme
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer Poststed

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Jeg er kjent med vilkårene for fast rente som jeg finner i kapittel 2 i Sted og dato Underskrift Søknaden må være
Likhet:
        0.9915481805801392

Indekser:
            Nynorsk/søketekst:  7
            Bokmål/treff:       239
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer og poststad Telefon

Etternamnet til fullmaktshavaren Fornamnet og mellomnamnet til fullmaktshavaren Fullmakta er gyldig Frå Til

Stad og dato Underskrifta di

Du kan laste opp fullmaktsskjemaet p
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer og poststed Telefon

Fullmaktshavers etternavn Fullmaktshavers fornavn og mellomnavn Fullmakten er gyldig Fra Til

Sted og dato Din underskrift Du kan laste opp fullmaktsskjemaet på Dine sider ell
Likhet:
        0.9920178651809692

Indekser:
            Nynorsk/søketekst:  8
            Bokmål/treff:       240
_______________________________________________________________

Søketekst:
        Du finn informasjon om vilkår og dokumentasjon på neste side. Søknad om sjukestipend Nynorsk Skjema S – artikkelnummer 9001561 – nynorsk – 06.2022 – Organisasjonsnummer NO 960 885 406 Namn, adresse og postnummer/-stad Personnummer Fødselsdato Kundenummer i Lånekassen

Eigen sjukdom Sjukt barn Barnet
Match:
        Du finner informasjon om vilkår og dokumentasjon på neste side. Søknad om sykestipend Bokmål Skjema S – artikkelnummer 9001561 – bokmål – 06.2022– Organisasjonsnummer NO 960 885 406 Navn, adresse og postnummer/-sted Personnummer Fødselsdato Kundenummer i Lånekassen

Egen sykdom Sykt barn Barnets fød
Likhet:
        0.9905437231063843

Indekser:
            Nynorsk/søketekst:  12
            Bokmål/treff:       250
_______________________________________________________________

Søketekst:
        Søknaden fortset på neste side

Tilleggsstipend kan bli gitt i tillegg til vanleg utdanningsstøtte og er på inntil 4 000 kroner per månad. Stipendet er meint for søkarar som er i stand til å studere, men som på grunn av nedsett funksjonsevne bruker så mykje tid og krefter på å studere, at dei ikkje
Match:
        Søknaden fortsetter på neste side

Tilleggsstipend kan bli gitt i tillegg til vanlig utdanningsstøtte og er på inntil 4 000 kroner per måned. Stipendet er ment for søkere som er i stand til å studere, men som på grunn av nedsatt funksjonsevne bruker så mye tid og krefter på å studere, at de ikke kan
Likhet:
        0.9937683343887329

Indekser:
            Nynorsk/søketekst:  13
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        Skjemaet fortset på neste side

Søknaden gjeld for søkarar som på grunn av nedsett funksjonsevne ikkje er i stand til å ha lønna arbeid i sommarferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og førebu seg til neste semester. Med lønna arbeid meiner vi alt arbeid der lønna er s
Match:
        Skjemaet fortsetter på neste side

Søknaden gjelder for søkere som på grunn av nedsatt funksjonsevne ikke er i stand til å ha lønnet arbeid i sommerferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og forberede seg til neste semester. Med lønnet arbeid menes alt arbeid hvor lønna
Likhet:
        0.992562472820282

Indekser:
            Nynorsk/søketekst:  14
            Bokmål/treff:       252
_______________________________________________________________

Søketekst:


Etternamn Fornamn og mellomnamn Fødselsdato (dag – månad – år)

Kva utdanning har eleven teke? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førarkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – månad – år

Oppgi siste dato elev
Match:


Etternavn Fornavn og mellomnavn Fødselsdato (dag – måned – år)

Hvilken utdanning har eleven tatt? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førerkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – måned – år

Oppgi siste dato
Likhet:
        0.9916613101959229

Indekser:
            Nynorsk/søketekst:  16
            Bokmål/treff:       255
_______________________________________________________________

Søketekst:


Skal fyllast ut av den administrative leiaren ved lærestaden

Namn (fornamn og etternamn) Namn på lærestaden Administratoren si e-postadresse (direkte e-post, ikkje postmottak) Administratoren sitt telefonnummer Administratoren sitt mobilnummer

Lånekassen treng signatur til den administrative lei
Match:


Skal fylles ut av den administrative lederen ved lærestedet

Navn (fornavn og etternavn) Navn på lærestedet Administratorens e-postadresse (direkte e-post, ikke postmottak) Administratorens telefonnummer Administratorens mobilnummer

Lånekassen trenger den administrative lederens signatur for å gi
Likhet:
        0.9910480976104736

Indekser:
            Nynorsk/søketekst:  17
            Bokmål/treff:       257
_______________________________________________________________

Søketekst:
        Søknaden held fram på neste side

,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden
Match:
        Søknaden fortsetter på neste side

,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og do
Likhet:
        0.992556631565094

Indekser:
            Nynorsk/søketekst:  18
            Bokmål/treff:       258
_______________________________________________________________

Søketekst:


04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 04.05.2022 Din Bank (Spar
Match:


02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 02.03.2022 OBOS-banken AS
Likhet:
        0.9502831697463989

Indekser:
            Nynorsk/søketekst:  19
            Bokmål/treff:       291
_______________________________________________________________

Søketekst:


01.09.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 01.09.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 01.09.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 01.09.2021 OBOS-banken AS Boliglån 50 % 1,57 % 01.09.2021 Sunndal Sparebank B
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9701328277587891

Indekser:
            Nynorsk/søketekst:  21
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9613387584686279

Indekser:
            Nynorsk/søketekst:  23
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:
        Universitet og høgskole
Hoyskole og universitet i norge
Studere i Noreg
Utdanning ved alle universitet og godkjente høgskolar gir rett til støtte frå Lånekassen til å ta 480 studiepoeng. Det er det same som åtte år med fulltidsstudium.
Alle studentar får basislån
Basislån kan alle studentar få, og d
Match:
        Universitet og høgskole
Her finner du informasjon om hvor mye lån og stipend du kan få, og hvor mye du kan tjene før du mister stipendet.
Hoyskole og universitet i Norge
Studere i Norge
Studier ved alle universiteter og godkjente høgskoler gir rett til støtte fra Lånekassen til å ta 480 studiepoeng.
Likhet:
        0.9671710729598999

Indekser:
            Nynorsk/søketekst:  34
            Bokmål/treff:       0
_______________________________________________________________

Søketekst:
        Kven har ikkje ungdomsrett?
Tek du opp igjen fag, har fullført vidaregåande opplæring tidlegare eller er over 24 år, har du ikkje lenger ungdomsrett. Du kan få stipend og lån frå Lånekassen, men etter dei same reglane som for høgare utdanning.
Match:
        Hvem har ikke ungdomsrett?
Tar du opp fag, har fullført tre år på videregående tidligere eller er over 24 år, har du ikke lenger ungdomsrett. Du kan få stipend og lån fra Lånekassen, men etter de samme reglene som for høyere utdanning.
Likhet:
        0.9670020937919617

Indekser:
            Nynorsk/søketekst:  35
            Bokmål/treff:       1
_______________________________________________________________

Søketekst:
        Fagskole
Fagskole
Fagskoleutdanning
Du kan få lån og stipend til fagskoleutdanningar som er godkjende av NOKUT.
Dersom du er usikker på om utdanninga di er godkjent for lån og stipend frå Lånekassen, kan du kontakte oss eller sjå NOKUT si oversikt over godkjende fagskoletilbod.
Alle studentar får ba
Match:
        Fagskole
Fagskole
Fagskoleutdanning
Du kan få lån og stipend til fagskoleutdanninger som er godkjent av NOKUT.
Hvis du er usikker på om utdanningen din er godkjent for lån og stipend fra Lånekassen, kan du spørre oss direkte eller se i NOKUT sin oversikt over akkrediterte fagskoletilbud.
Alle studen
Likhet:
        0.9915552139282227

Indekser:
            Nynorsk/søketekst:  36
            Bokmål/treff:       2
_______________________________________________________________

Søketekst:
        Lån og stipend for å gå på folkehøgskole
Er du elev på ein folkehøgskole, kan du få basislån i inntil ti månader.
Kva er basislån?
Basislån er det alle studentar kan få, og er namnet på det dei fleste kallar studielån. Du får ikkje ekstra lån til å dekke utgiftene ved linja du skal gå på, eller til
Match:
        Lån og stipend for å gå på folkehøgskole
Er du elev på en folkehøgskole, kan du få basislån i inntil ti måneder.
Hva er basislån?
Basislån er det alle studenter kan få, og er navnet på det de fleste kaller studielån. Du får ikke ekstra lån til å dekke utgiftene ved linjen du skal gå på, eller til re
Likhet:
        0.9827646613121033

Indekser:
            Nynorsk/søketekst:  37
            Bokmål/treff:       3
_______________________________________________________________

Søketekst:
        Bibel- eller kunstskole
Elever på bibelskole eller kunstskole kan få lån og stipend i inntil ti måneder
Bibelskole eller kunstskole er to ulike skoler. Går du på bibelskole eller kunstskole, får du ikkje lenger stipend slik du kanskje fekk på vidaregåande, men du får eit lån.
Du kan få eit basislån
Match:
        Bibel- eller kunstskole
Elever på bibelskole eller kunstskole kan få stipend og lån i inntil ti måneder
Bibelskole eller kunstskoler er to ulike typer skoler. Går du på bibelskole eller kunstskole, får du ikke lenger stipend slik du kanskje fikk på videregående, men du får et lån.
Du kan få et basis
Likhet:
        0.9956610798835754

Indekser:
            Nynorsk/søketekst:  38
            Bokmål/treff:       4
_______________________________________________________________

Søketekst:
        Du kan ikkje få lån og stipend dersom du berre skal ta førarkort.
Du kan berre få stipend og lån til førarkort dersom du tar det i samband med grunnutdanninga. Du må starte på, eller ta førerkortet innen tolv måneder før grunnutdanningen starter.
Du kan få skolepengelån til å dekke utgiftene til kur
Match:
        Du kan ikke få lån og stipend hvis du bare skal ta førerkort.
Du kan bare få stipend og lån til førerkort hvis du tar det i forbindelse med grunnutdanningen. Du må starte på, eller ta førerkortet innen tolv måneder før grunnutdanningen starter.
Du kan få skolepengelån til å dekke utgiftene til kurse
Likhet:
        0.9918527007102966

Indekser:
            Nynorsk/søketekst:  39
            Bokmål/treff:       5
_______________________________________________________________

Søketekst:
        Lån og stipend til sommarkurs
Til enkelte sommarkurs kan du få lån og stipend.
Basislån i inntil 2 månader
Du kan få basislån i inntil 2 månader for å ta sommarkurs. Basislån er det alle studentar kan få, og det dei fleste kallar studielån. Sommaren 2022 er basislånet 11 487 kroner per månad, og du
Match:
        Lån og stipend til sommerkurs
Til enkelte sommerkurs kan du få lån og stipend.
Basislån i inntil 2 måneder
Du kan få basislån i inntil 2 måneder for å ta sommerkurs. Basislån er det alle studenter kan få, og det de fleste kaller studielån. Sommeren 2022 er basislånet 11 487 kroner per måned, og du k
Likhet:
        0.9979276657104492

Indekser:
            Nynorsk/søketekst:  40
            Bokmål/treff:       6
_______________________________________________________________

Søketekst:
        at inntekt og formue er lågare enn grensene
Kva skal til for å få omgjering?
Det vanlege studielånet som alle får, blir kalla basislån. Opptil 40 prosent av basislånet kan bli til stipend.
Du må bu borte
Du kan ikkje få gjort om lån til stipend for periodar du har budd heime hos foreldra dine. Når d
Match:
        at inntekt og formue er lavere enn grensene
Hva skal til for å få omgjøring?
Det vanlige studielånet som alle får, kalles basislån. Opptil 40 prosent av basislånet kan bli til stipend.
Du må bo borte fra foreldrene dine
Du kan ikke få gjort om lån til stipend for perioder du har bodd hjemme hos fore
Likhet:
        0.9569530487060547

Indekser:

#### Falsk positiv
Samme som over

In [17]:
i = 21
print(search_result[i])
print(nynorsk_texts_joined[i][:250])
print("\n___________\n")
print(bokmål_texts_joined[search_result[i][0]["corpus_id"]][:250])

[{'corpus_id': 293, 'score': 0.9701328277587891}]


01.09.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 01.09.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 01.09.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 01.09.2021 OBOS-banken AS B

___________



03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Spareban

## Aggreger setningsvektorene: Mean pooling

In [18]:
import numpy as np 

emb_path = Path("embeddings/labse/maxlen_parts_mean_pooling.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_embeddings = np.array([np.mean(model.encode(text_parts), axis=0) for text_parts in nynorsk_maxlen_parts])
    bokmål_embeddings = np.array([np.mean(model.encode(text_parts), axis=0) for text_parts in bokmål_maxlen_parts])
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
non_matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] <= threshold]

hits, misses = compare_matches_to_fasit(matches)
doc_alignment_results["mean_pooling_biter"] = {"matches": len(matches), "threshold": threshold, "percent of docs": round(len(matches)/len(nynorske)*100, 2), "hits": len(hits), "misses": len(misses)}

### Inspiser matches

In [19]:
print_matches(matches, nynorsk_texts_joined, bokmål_texts_joined)

Søketekst:
        Er du flyktning? Du blir rekna som flyktning dersom du er utanlandsk statsborgar og har fått vern (asyl) i Noreg. Du må vere registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Noreg som er godkjend f
Match:
        Er du flyktning? Du regnes som flyktning hvis du er utenlandsk statsborger og har fått beskyttelse (asyl) i Norge. Du må være registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Norge som er godkjent
Likhet:
        0.9922596216201782

Indekser:
            Nynorsk/søketekst:  0
            Bokmål/treff:       241
_______________________________________________________________

Søketekst:


Du kan bruke dette skjemaet dersom du tar høgare utdanning eller fagskoleutdanning i Noreg eller Norden, og du skal søke om støtte til studieopphald i eit anna land.

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn

Kva studieprogram følger du i Noreg/Norden? I k
Match:


Du kan bruke dette skjemaet hvis du tar høyere utdanning eller fagskoleutdanning i Norge eller Norden, og du skal søke om støtte til studieopphold i et annet land.

Skjemaet laster du opp på Dine Sider, eller du kan sende det i posten til Lånekassen behandler personopplysninger i samsvar med regel
Likhet:
        0.9899264574050903

Indekser:
            Nynorsk/søketekst:  1
            Bokmål/treff:       233
_______________________________________________________________

Søketekst:


Det er viktig at du les informasjonen på side 2 i dette søknadsskjemaet. Hugs å sende inn ein , dersom du ikkje har gjort det.

Denne søknaden lastar du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn

Nam
Match:


Det er viktig at du leser informasjonen på side 2 i dette søknadsskjemaet. Husk å sende inn en , hvis du ikke allerede har gjort det.

Denne søknaden laster du opp på Dine sider, eller du kan sende den i posten til .

Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomna
Likhet:
        0.9914705753326416

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       234
_______________________________________________________________

Søketekst:
        Nynorsk Skjema I – artikkelnr. 9001550 – nynorsk – 01.2022 – organisasjonsnummer NO 960 885 406 Namn, adresse og postnummer/-stad Personnummer Fødselsdato Kundenummer i Lånekassen Søknad om betalingsutsetting og/eller sletting av renter Du kan bruke nettsøknaden på

Kva månad/månader søker du om uts
Match:
        Bokmål Skjema I – artikkelnr. 9001550 – bokmål – 01.2022 – organisasjonsnummer NO 960 885 406 Navn, adresse og postnummer/-sted Personnummer Fødselsdato Kundenummer i Lånekassen Søknad om betalingsutsettelse og/eller sletting av renter Du kan bruke nettsøknaden på

Hvilken måned / hvilke måneder søk
Likhet:
        0.9915809631347656

Indekser:
            Nynorsk/søketekst:  4
            Bokmål/treff:       237
_______________________________________________________________

Søketekst:
        Nynorsk Eg stadfester at eg har lese vilkåra på side 2.

Oppgi perioden du søker om sletting av gjeld for

År Månad Dag Frå Til Punkt 4 skal berre fyllast ut dersom du søker om sletting av gjeld på grunn av omsorg. Arbeidstakar Sjølvstendig næringsdrivande Dato og underskrift

Adressa til arbeidsgiv
Match:
        Bokmål Ordningen gjelder for låntakere som er bosatt og yrkesaktive i Finnmark og i disse kommunene i Nord-Troms: Lyngen, Storfjord, Kåfjord, Skjervøy, Nordreisa, Kvænangen og Karlsøy. Ordningen omfatter også yrkesaktive leger i andre utvalgte kommuner. Vi henter informasjon om bosted fra Folkeregis
Likhet:
        0.9887145161628723

Indekser:
            Nynorsk/søketekst:  5
            Bokmål/treff:       236
_______________________________________________________________

Søketekst:


Du kan logge inn på og endre kontonummeret ditt dersom du har oppretta ein ny konto som du vil bruke dersom du vil ha pengane inn på ein annan av kontoane dine Lånekassen overfører berre lån og stipend til ein norsk konto som du eig. Dersom du nettopp har fått tildelt eit nytt kontonummer kan det
Match:


Du kan logge inn på og endre kontonummeret ditt hvis du har opprettet en ny konto som du vil bruke hvis du vil ha pengene inn på en annen av kontoene dine Lånekassen overfører bare lån og stipend til en norsk konto som du eier. Hvis du nettopp har fått tildelt et nytt kontonummer kan det ta noen d
Likhet:
        0.9907739758491516

Indekser:
            Nynorsk/søketekst:  6
            Bokmål/treff:       238
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer Poststad

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Eg er kjend med vilkåra for fast rente som eg finn i kapittel 2 i Stad og dato Underskrift Søknaden må vere komme
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer Poststed

(01.01.2023–31.12.2025) (01.01.2023–31.12.2027) (01.01.2023–31.12.2032)

Jeg er kjent med vilkårene for fast rente som jeg finner i kapittel 2 i Sted og dato Underskrift Søknaden må være
Likhet:
        0.9908833503723145

Indekser:
            Nynorsk/søketekst:  7
            Bokmål/treff:       239
_______________________________________________________________

Søketekst:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternamn Fornamn og mellomnamn Adresse Postnummer og poststad Telefon

Etternamnet til fullmaktshavaren Fornamnet og mellomnamnet til fullmaktshavaren Fullmakta er gyldig Frå Til

Stad og dato Underskrifta di

Du kan laste opp fullmaktsskjemaet p
Match:


Kundenummer i Lånekassen Fødselsnummer (11 siffer) Etternavn Fornavn og mellomnavn Adresse Postnummer og poststed Telefon

Fullmaktshavers etternavn Fullmaktshavers fornavn og mellomnavn Fullmakten er gyldig Fra Til

Sted og dato Din underskrift Du kan laste opp fullmaktsskjemaet på Dine sider ell
Likhet:
        0.9903062582015991

Indekser:
            Nynorsk/søketekst:  8
            Bokmål/treff:       240
_______________________________________________________________

Søketekst:
        Du finn informasjon om vilkår og dokumentasjon på neste side. Søknad om sjukestipend Nynorsk Skjema S – artikkelnummer 9001561 – nynorsk – 06.2022 – Organisasjonsnummer NO 960 885 406 Namn, adresse og postnummer/-stad Personnummer Fødselsdato Kundenummer i Lånekassen

Eigen sjukdom Sjukt barn Barnet
Match:
        Du finner informasjon om vilkår og dokumentasjon på neste side. Søknad om sykestipend Bokmål Skjema S – artikkelnummer 9001561 – bokmål – 06.2022– Organisasjonsnummer NO 960 885 406 Navn, adresse og postnummer/-sted Personnummer Fødselsdato Kundenummer i Lånekassen

Egen sykdom Sykt barn Barnets fød
Likhet:
        0.9879823923110962

Indekser:
            Nynorsk/søketekst:  12
            Bokmål/treff:       250
_______________________________________________________________

Søketekst:
        Søknaden fortset på neste side

Tilleggsstipend kan bli gitt i tillegg til vanleg utdanningsstøtte og er på inntil 4 000 kroner per månad. Stipendet er meint for søkarar som er i stand til å studere, men som på grunn av nedsett funksjonsevne bruker så mykje tid og krefter på å studere, at dei ikkje
Match:
        Søknaden fortsetter på neste side

Tilleggsstipend kan bli gitt i tillegg til vanlig utdanningsstøtte og er på inntil 4 000 kroner per måned. Stipendet er ment for søkere som er i stand til å studere, men som på grunn av nedsatt funksjonsevne bruker så mye tid og krefter på å studere, at de ikke kan
Likhet:
        0.9937467575073242

Indekser:
            Nynorsk/søketekst:  13
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        Skjemaet fortset på neste side

Søknaden gjeld for søkarar som på grunn av nedsett funksjonsevne ikkje er i stand til å ha lønna arbeid i sommarferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og førebu seg til neste semester. Med lønna arbeid meiner vi alt arbeid der lønna er s
Match:
        Skjemaet fortsetter på neste side

Søknaden gjelder for søkere som på grunn av nedsatt funksjonsevne ikke er i stand til å ha lønnet arbeid i sommerferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og forberede seg til neste semester. Med lønnet arbeid menes alt arbeid hvor lønna
Likhet:
        0.9890145063400269

Indekser:
            Nynorsk/søketekst:  14
            Bokmål/treff:       252
_______________________________________________________________

Søketekst:
        Sletting av gjeld for lærarar i grunnskolen Nynorsk Skjema2 Namn Oppteningsperiode frå og med dato

Oppteningsperiode til og med dato Frå 2020 er Finnmark og Troms slått saman til det nye fylket Troms og Finnmark, men det påverkar ikkje ordninga med sletting av gjeld. For å få sletta gjeld må du fra
Match:
        Sletting av gjeld for lærere i grunnskolen Bokmål Skjema L – Bokmål – 02

Fra 2020 er Finnmark og Troms slått sammen til det nye fylket Troms og Finnmark, men det påvirker ikke ordningen med sletting av gjeld. For å få slettet gjeld må du fortsatt arbeide i det som tidligere var regionen Finnmark og
Likhet:
        0.9518939256668091

Indekser:
            Nynorsk/søketekst:  15
            Bokmål/treff:       254
_______________________________________________________________

Søketekst:


Skal fyllast ut av den administrative leiaren ved lærestaden

Namn (fornamn og etternamn) Namn på lærestaden Administratoren si e-postadresse (direkte e-post, ikkje postmottak) Administratoren sitt telefonnummer Administratoren sitt mobilnummer

Lånekassen treng signatur til den administrative lei
Match:


Skal fylles ut av den administrative lederen ved lærestedet

Navn (fornavn og etternavn) Navn på lærestedet Administratorens e-postadresse (direkte e-post, ikke postmottak) Administratorens telefonnummer Administratorens mobilnummer

Lånekassen trenger den administrative lederens signatur for å gi
Likhet:
        0.9912881851196289

Indekser:
            Nynorsk/søketekst:  17
            Bokmål/treff:       257
_______________________________________________________________

Søketekst:
        Søknaden held fram på neste side

,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden
Match:
        Søknaden fortsetter på neste side

,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og do
Likhet:
        0.9952884316444397

Indekser:
            Nynorsk/søketekst:  18
            Bokmål/treff:       258
_______________________________________________________________

Søketekst:


04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 04.05.2022 Din Bank (Spar
Match:


02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 02.03.2022 OBOS-banken AS
Likhet:
        0.9716790318489075

Indekser:
            Nynorsk/søketekst:  19
            Bokmål/treff:       291
_______________________________________________________________

Søketekst:


05.01.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 05.01.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 05.01.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 05.01.2022 OBOS-banken AS Boliglån 50 % 1,82 % 05.01.2022 Sunndal Sparebank B
Match:


02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 02.03.2022 OBOS-banken AS
Likhet:
        0.9810688495635986

Indekser:
            Nynorsk/søketekst:  20
            Bokmål/treff:       291
_______________________________________________________________

Søketekst:


01.09.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 01.09.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 01.09.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 01.09.2021 OBOS-banken AS Boliglån 50 % 1,57 % 01.09.2021 Sunndal Sparebank B
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9804571270942688

Indekser:
            Nynorsk/søketekst:  21
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


05.05.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 05.05.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 05.05.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 05.05.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 05.05.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9731904864311218

Indekser:
            Nynorsk/søketekst:  22
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9624838829040527

Indekser:
            Nynorsk/søketekst:  23
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


06.01.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 06.01.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 06.01.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 06.01.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 06.01.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9612705707550049

Indekser:
            Nynorsk/søketekst:  24
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


04.11.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 04.11.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 04.11.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 04.11.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 04.11.2020 Fana Spare
Match:


06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.202
Likhet:
        0.9643847346305847

Indekser:
            Nynorsk/søketekst:  25
            Bokmål/treff:       303
_______________________________________________________________

Søketekst:


02.09.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 02.09.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 02.09.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 02.09.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.09.2020 Fana Spare
Match:


06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.202
Likhet:
        0.965580403804779

Indekser:
            Nynorsk/søketekst:  26
            Bokmål/treff:       303
_______________________________________________________________

Søketekst:


08.07.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 08.07.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 08.07.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 08.07.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 08.07.2020 Fana Spare
Match:


06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.202
Likhet:
        0.9626497626304626

Indekser:
            Nynorsk/søketekst:  27
            Bokmål/treff:       303
_______________________________________________________________

Søketekst:


04.03.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 04.03.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 04.03.2020 Sbanken ASA Boliglån 50 % 2,75 % 04.03.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 04.03.2020 Nordea Direct Boliglån inntil 50 % 2,91 %

11.03
Match:


06.05.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,92 % 06.05.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 06.05.2020 Sbanken ASA Boliglån 50 % 2 % 06.05.2020 Fana Sparebank Nettlån Bolig 75 % 2,14 % 06.05.2020 Nordea Direct Boliglån inntil 50 % 2,15 % 13.05.202
Likhet:
        0.9519432187080383

Indekser:
            Nynorsk/søketekst:  28
            Bokmål/treff:       303
_______________________________________________________________

Søketekst:
        Universitet og høgskole
Hoyskole og universitet i norge
Studere i Noreg
Utdanning ved alle universitet og godkjente høgskolar gir rett til støtte frå Lånekassen til å ta 480 studiepoeng. Det er det same som åtte år med fulltidsstudium.
Alle studentar får basislån
Basislån kan alle studentar få, og d
Match:
        Universitet og høgskole
Her finner du informasjon om hvor mye lån og stipend du kan få, og hvor mye du kan tjene før du mister stipendet.
Hoyskole og universitet i Norge
Studere i Norge
Studier ved alle universiteter og godkjente høgskoler gir rett til støtte fra Lånekassen til å ta 480 studiepoeng.

#### Falsk positiv:

In [20]:
i = 19
print(search_result[i])
print(nynorsk_texts_joined[i][:250])
print("\n___________\n")
print(bokmål_texts_joined[search_result[i][0]["corpus_id"]][:250])

[{'corpus_id': 291, 'score': 0.9716790318489075}]


04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank B

___________



02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Bolig

#### Falsk negativ

In [21]:
i = 72
print(search_result[i])
print(nynorsk_texts_joined[i])
print("\n___________\n")
print(bokmål_texts_joined[search_result[i][0]["corpus_id"]])

[{'corpus_id': 38, 'score': 0.936010479927063}]
Hjelp og kontakt
Veileder frister
Aktuelt
Nytt straumstipend hausten 2022
Alle som kan ha rett til strømstipend, har fått ein e-post frå oss. Logg inn for å søke. Søknadsfristen er 15. januar 2023.
Bruker du avtalegiro? Sjekk nettbanken
06.12.2022
På grunn av en feil har rekninga med frist 15. desember blitt sletta for nokon kundar. Dersom dette gjeld deg, må du betale rekninga med frist 15. desember manuelt, og opprette avtalegiro på nytt. Logg inn på lanekassen.no og vel Di rekning for å finne rekninga.
Når du har oppfylt vilkåra for å få utbetalt pengane, overfører vi dei. Det vil ta 2-3 dagar frå vi utbetaler pengane til du har dei på din konto. Deretter får du ei utbetaling den 15. kvar månad resten av semesteret dersom du studerer i Noreg. Studerer du i utlandet, får du utbetaling for heile semesteret med den første utbetalinga.
Når du er under 18 år er det ein av foreldra dine (ev. verje) som skal signere på dine vegne. Begge foreldra får tilsendt avtalen enten i digital postkasse (Digipost eller E-boks) eller som brev i posten, men det er nok at éin av dei signerer avtalen. Foreldre signerer digitalt i tenesta Foreldresignering med BankID eller tilsvarande. Dersom du er under 18 år og har søkt om lån i tillegg til stipend skal du signere avtalen saman med éin av foreldra dine.
Når du er over 18 år skal du signere avtalen sjølv. Det gjer du ved å logge inn på Dine sider og finne avtalen som skal signerast. Du må bruke BankID eller tilsvarande for å signere digitalt.
Dersom du ikkje får til å signere, kan du oppdatere til nyaste versjon av nettlesaren eller bruke ein annan nettlesar.
Lånet ditt er rente- og avdragsfritt så lenge du får lån og stipend til fulltidsutdanning frå oss. Får du ikkje lenger lån og stipend til fulltidsutdanning, blir lånet rentebærande og du må begynne å betale etter ein betalingsfri periode på omtrent sju månader. Det gjeld både om du avsluttar eller avbryt utdanninga di, om du går over til deltidsutdanning eller om du studerer utan lån og stipend frå Lånekassen.
Du får ein betalingsplan frå oss når du skal begynne nedbetalinga.
Kontakt oss
Kundesenteret vårt har ope på kvardagar frå 09-15. Kontakt oss på telefonnummer

___________

Hjelp og kontakt
Veileder frister
Aktuelt
Nytt strømstipend høsten 2022
Alle som kan ha rett til strømstipend, har fått en e-post fra oss. Logg inn for å søke. Søknadsfristen er 15. januar 2023.
Bruker du avtalegiro? Sjekk nettbanken
06.12.2022
På grunn av en feil har avtalegiro blitt borte for noen kunder. Hvis dette gjelder deg, må du betale regningen med frist 15. desember manuelt, og opprette avtalegiro på nytt. Logg inn på lanekassen.no og velg Din regning for å finne regningen.
Når du har oppfylt vilkårene for å få utbetalt pengene, overfører vi dem. Det vil ta 2-3 dager fra vi utbetaler pengene til du har dem på din konto. Deretter får du en utbetaling den 15. hver måned resten av semesteret hvis du studerer i Norge. Hvis du studerer i utlandet får du utbetaling for hele semesteret med den første utbetalingen.
Når du er under 18 år er det en av foreldrene dine (ev. verge) som skal signere på dine vegne. Begge foreldre får tilsendt avtalen enten i digital postkasse (Digipost eller E-boks) eller som brev i posten, men det er nok at én av dem signerer avtalen. Foreldre signerer digitalt i tjenesten Foreldresignering med BankID eller tilsvarende. Hvis du er under 18 år og har søkt om lån i tillegg til stipend skal du signere avtalen sammen med én av foreldrene dine.
Når du er over 18 år skal du signere avtalen selv. Det gjør du ved å logge inn på Dine sider og finne avtalen som skal signeres. Du må bruke BankID eller tilsvarende for å signere digitalt.
Hvis du ikke får til å signere, kan du oppdatere til nyeste versjon av nettleseren eller bruke en annen nettleser.
Lånet ditt er rente- og avdragsfritt så lenge du får lån og stipend til fulltidsutdanning fra oss. Hvis du ikke får lån og stipend til fulltidsutdanning lenger, blir lånet rentebærende og du må begynne å betale etter en betalingsfri periode på omtrent sju måneder. Det gjelder både hvis du avslutter eller avbryter utdanningen din, hvis du går over til deltidsutdanning eller hvis du studerer uten lån og stipend fra Lånekassen.
Kontakt oss
Kundesenteret vårt har åpent på hverdager fra 09-15. Kontakt oss på telefonnummer

## Aggreger setningsvektorene: Max pooling

In [22]:
import numpy as np 

emb_path = Path("embeddings/labse/maxlen_parts_max_pooling.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_embeddings = np.array([np.max(model.encode(text_parts), axis=0) for text_parts in nynorsk_maxlen_parts])
    bokmål_embeddings = np.array([np.max(model.encode(text_parts), axis=0) for text_parts in bokmål_maxlen_parts])
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
non_matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] <= threshold]


hits, misses = compare_matches_to_fasit(matches)
doc_alignment_results["max_pooling_biter"] = {"matches": len(matches), "threshold": threshold, "percent of docs": round(len(matches)/len(nynorske)*100, 2), "hits": len(hits), "misses": len(misses)}

### Inspiser matches

In [23]:
from utils import print_matches

# print_matches(matches, nynorsk_texts_joined, bokmål_texts_joined)
print_matches(non_matches, nynorsk_texts_joined, bokmål_texts_joined)

Søketekst:
        Er du flyktning? Du blir rekna som flyktning dersom du er utanlandsk statsborgar og har fått vern (asyl) i Noreg. Du må vere registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Noreg som er godkjend f
Match:
        Er du flyktning? Du regnes som flyktning hvis du er utenlandsk statsborger og har fått beskyttelse (asyl) i Norge. Du må være registrert med flyktningstatus hos Utlendingsdirektoratet (UDI). Du kan få stipend og lån Er du flyktning, kan du få stipend og lån til all utdanning i Norge som er godkjent
Likhet:
        0.9044878482818604

Indekser:
            Nynorsk/søketekst:  0
            Bokmål/treff:       241
_______________________________________________________________

Søketekst:
        Nynorsk Skjema for lærlinglønn Kor stort bortebuarstipend du kan få, er avhengig av kor mykje du tener som lærling. Derfor må arbeidsgivaren din fylle ut dette skjemaet for å stadfeste lønna di. Vi kan ikkje behandle søknaden din før du har sendt opplysningar om lønna di. Du kan laste opp ferdig utf
Match:
        Bokmål Skjema for lærlinglønn Hvor stort borteboerstipend du kan få, er avhengig av hvor mye du tjener som lærling. Derfor må arbeidsgiveren din fylle ut dette skjemaet for å bekrefte lønnen din. Vi kan ikke behandle søknaden din før du har sendt opplysninger om lønnen din. Du kan laste opp ferdig u
Likhet:
        0.8358446359634399

Indekser:
            Nynorsk/søketekst:  3
            Bokmål/treff:       235
_______________________________________________________________

Søketekst:
        Nynorsk Eg stadfester at eg har lese vilkåra på side 2.

Oppgi perioden du søker om sletting av gjeld for

År Månad Dag Frå Til Punkt 4 skal berre fyllast ut dersom du søker om sletting av gjeld på grunn av omsorg. Arbeidstakar Sjølvstendig næringsdrivande Dato og underskrift

Adressa til arbeidsgiv
Match:
        Bokmål Ordningen gjelder for låntakere som er bosatt og yrkesaktive i Finnmark og i disse kommunene i Nord-Troms: Lyngen, Storfjord, Kåfjord, Skjervøy, Nordreisa, Kvænangen og Karlsøy. Ordningen omfatter også yrkesaktive leger i andre utvalgte kommuner. Vi henter informasjon om bosted fra Folkeregis
Likhet:
        0.9209349155426025

Indekser:
            Nynorsk/søketekst:  5
            Bokmål/treff:       236
_______________________________________________________________

Søketekst:


Forskrifta gjeld tilbakebetaling av utdanningslån som er gitt etter utdanningsstøtteloven og forskrift om tildeling av utdanningsstøtte. Forskrifta gir reglar om renter og tilbakebetaling betalingsutsetjing og sletting av renter sletting av gjeld misleghalden gjeld som er permanent overført til St
Match:
        Fastsatt av Kunnskapsdepartementet 13. februar 2018 med hjemmel i lov 3. juni 2005 nr. 37 om utdanningsstøtte (utdanningsstøtteloven) § 3, § 4, § 5, § 6 og § 7. Det Med ”andre stipend” menes for eksempel forsørgerstipend, reisestipend, foreldrestipend, sykestipend, flyktningstipend og språkstipend.
Likhet:
        0.9164102077484131

Indekser:
            Nynorsk/søketekst:  9
            Bokmål/treff:       256
_______________________________________________________________

Søketekst:
        Fastsett av Kunnskapsdepartementet 25. februar 2021 med heimel i lov 3. juni 2005 nr. 37 om utdanningsstøtte (utdanningsstøtteloven) § 8, § 9, § 10, § 14 og § 15

I forskrift 17. desember 2020 nr. 3022 om tilbakebetaling av utdanningslån 2021 blir det gjort følgjande endring: Ny § 7-1 a skal lyde: U
Match:


Fastsatt av Kunnskapsdepartementet 21. desember 2021 med hjemmel i lov 3. juni 2005 nr. 37 om utdanningsstøtte (utdanningsstøtteloven) § 4 og § 5

I forskrift 1. juli 2020 nr. 1459 om midlertidige regler for utdanningsstøtte som følge av utbruddet av covid-19 gjøres følgende endringer: § 3 skal ly
Likhet:
        0.8421823978424072

Indekser:
            Nynorsk/søketekst:  10
            Bokmål/treff:       280
_______________________________________________________________

Søketekst:


Forskrifta gjeld tilbakebetaling av utdanningslån som er gitt etter utdanningsstøtteloven og forskrift om tildeling av utdanningsstøtte. Forskrifta gir reglar om renter og tilbakebetaling betalingsutsetjing og sletting av renter sletting av gjeld misleghalden gjeld som er permanent overført til St
Match:
        Fastsatt av Kunnskapsdepartementet 10. mars 2017 med hjemmel i lov 3. juni 2005 nr. 37 om utdanningsstøtte (utdanningsstøtteloven) § 3, § 4, § 5, § 6 og § 7. Med ”andre stipend” menes for eksempel forsørgerstipend, reisestipend, foreldrestipend, sykestipend, flyktningstipend og språkstipend. Flyktni
Likhet:
        0.9126266837120056

Indekser:
            Nynorsk/søketekst:  11
            Bokmål/treff:       285
_______________________________________________________________

Søketekst:
        Du finn informasjon om vilkår og dokumentasjon på neste side. Søknad om sjukestipend Nynorsk Skjema S – artikkelnummer 9001561 – nynorsk – 06.2022 – Organisasjonsnummer NO 960 885 406 Namn, adresse og postnummer/-stad Personnummer Fødselsdato Kundenummer i Lånekassen

Eigen sjukdom Sjukt barn Barnet
Match:
        Du finner informasjon om vilkår og dokumentasjon på neste side. Søknad om sykestipend Bokmål Skjema S – artikkelnummer 9001561 – bokmål – 06.2022– Organisasjonsnummer NO 960 885 406 Navn, adresse og postnummer/-sted Personnummer Fødselsdato Kundenummer i Lånekassen

Egen sykdom Sykt barn Barnets fød
Likhet:
        0.9167348146438599

Indekser:
            Nynorsk/søketekst:  12
            Bokmål/treff:       250
_______________________________________________________________

Søketekst:
        Skjemaet fortset på neste side

Søknaden gjeld for søkarar som på grunn av nedsett funksjonsevne ikkje er i stand til å ha lønna arbeid i sommarferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og førebu seg til neste semester. Med lønna arbeid meiner vi alt arbeid der lønna er s
Match:
        Skjemaet fortsetter på neste side

Søknaden gjelder for søkere som på grunn av nedsatt funksjonsevne ikke er i stand til å ha lønnet arbeid i sommerferien (16.06.2023– 15.08.2023), men likevel er i stand til å studere og forberede seg til neste semester. Med lønnet arbeid menes alt arbeid hvor lønna
Likhet:
        0.9341356754302979

Indekser:
            Nynorsk/søketekst:  14
            Bokmål/treff:       252
_______________________________________________________________

Søketekst:
        Sletting av gjeld for lærarar i grunnskolen Nynorsk Skjema2 Namn Oppteningsperiode frå og med dato

Oppteningsperiode til og med dato Frå 2020 er Finnmark og Troms slått saman til det nye fylket Troms og Finnmark, men det påverkar ikkje ordninga med sletting av gjeld. For å få sletta gjeld må du fra
Match:
        Sletting av gjeld for lærere i grunnskolen Bokmål Skjema L – Bokmål – 02

Fra 2020 er Finnmark og Troms slått sammen til det nye fylket Troms og Finnmark, men det påvirker ikke ordningen med sletting av gjeld. For å få slettet gjeld må du fortsatt arbeide i det som tidligere var regionen Finnmark og
Likhet:
        0.8181188702583313

Indekser:
            Nynorsk/søketekst:  15
            Bokmål/treff:       254
_______________________________________________________________

Søketekst:


Etternamn Fornamn og mellomnamn Fødselsdato (dag – månad – år)

Kva utdanning har eleven teke? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førarkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – månad – år

Oppgi siste dato elev
Match:


Etternavn Fornavn og mellomnavn Fødselsdato (dag – måned – år)

Hvilken utdanning har eleven tatt? Kryss av for riktig utdanning. 140 t grunnutdanning, yrkessjåfør Førerkort kl. C/CE/D + 140 t grunnutdanning, yrkessjåfør Oppgi startdato for 140 t grunnutdanning. Dag – måned – år

Oppgi siste dato
Likhet:
        0.7089682817459106

Indekser:
            Nynorsk/søketekst:  16
            Bokmål/treff:       255
_______________________________________________________________

Søketekst:


04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 04.05.2022 Din Bank (Spar
Match:


02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 02.03.2022 OBOS-banken AS
Likhet:
        0.937472939491272

Indekser:
            Nynorsk/søketekst:  19
            Bokmål/treff:       291
_______________________________________________________________

Søketekst:


05.01.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,54 % 05.01.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 05.01.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,72 % 05.01.2022 OBOS-banken AS Boliglån 50 % 1,82 % 05.01.2022 Sunndal Sparebank B
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9112894535064697

Indekser:
            Nynorsk/søketekst:  20
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


05.05.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 05.05.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 05.05.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 05.05.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 05.05.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9418544769287109

Indekser:
            Nynorsk/søketekst:  22
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9380552768707275

Indekser:
            Nynorsk/søketekst:  23
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


06.01.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 06.01.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 06.01.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 06.01.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 06.01.2021 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.917755126953125

Indekser:
            Nynorsk/søketekst:  24
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


04.11.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 04.11.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 04.11.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 04.11.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 04.11.2020 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.9098293781280518

Indekser:
            Nynorsk/søketekst:  25
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


02.09.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 02.09.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 02.09.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 02.09.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.09.2020 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.8893947005271912

Indekser:
            Nynorsk/søketekst:  26
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


08.07.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 08.07.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 08.07.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 08.07.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 08.07.2020 Fana Spare
Match:


03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banke
Likhet:
        0.8830122947692871

Indekser:
            Nynorsk/søketekst:  27
            Bokmål/treff:       293
_______________________________________________________________

Søketekst:


04.03.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 04.03.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,73 % 04.03.2020 Sbanken ASA Boliglån 50 % 2,75 % 04.03.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 04.03.2020 Nordea Direct Boliglån inntil 50 % 2,91 %

11.03
Match:


06.07.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 06.07.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 06.07.2022 Haltdalen Sparebank Boliglån 34+ 2,32% 06.07.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 06.07.2022 KLP Banken AS Boliglån ordinær - 7
Likhet:
        0.8881958723068237

Indekser:
            Nynorsk/søketekst:  28
            Bokmål/treff:       288
_______________________________________________________________

Søketekst:


01.01.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 01.01.2020 Sbanken ASA Boliglån 50 % 2,75 % 01.01.2020 Fana Sparebank Nettlån Bolig 50 % 2,80 % 01.01.2020 NORDirektebank (Skagerrak Sparebank) Boliglån inntil 60 % 2,89 % 01.01.2020 Gjensidige Bank Boliglån inntil 50 % 2,91 %
Match:


06.07.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 06.07.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 06.07.2022 Haltdalen Sparebank Boliglån 34+ 2,32% 06.07.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 06.07.2022 KLP Banken AS Boliglån ordinær - 7
Likhet:
        0.906413197517395

Indekser:
            Nynorsk/søketekst:  29
            Bokmål/treff:       288
_______________________________________________________________

Søketekst:


06.11.2019 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,68 % 06.11.2019 Sbanken ASA Boliglån 50 % 2,75 % 06.11.2019 Fana Sparebank Nettlån Bolig 50 % 2,80 % 06.11.2019 NORDirektebank (Skagerrak Sparebank) Boliglån inntil 60 % 2,89 % 06.11.2019 Gjensidige Bank Boliglån inntil 50 % 2,91 %
Match:


06.11.2019 Storebrand Bank ASA 70 % Boliglån fastrente 3 år 2,70 % 06.11.2019 KLP Banken AS Fastrente Ordinær - 3 år innenfor 75% 2,70 % 06.11.2019 SpareBank 1 Østfold Akershus Fastrentelån - 3 års binding 2,76 % 06.11.2019 Danske Bank Fastrentelån 3 år 80 % 2,80 % 06.11.2019 Gjensidige Bank Fastr
Likhet:
        0.8129357099533081

Indekser:
            Nynorsk/søketekst:  30
            Bokmål/treff:       306
_______________________________________________________________

Søketekst:
        Utvida stipend til skulepengar ved utvalde lærestader

Påverker det utanlandsstudentane sitt val av studiestad?

Notat nr. 2/2022 Utvida stipend til skolepengar ved utvalde lærestader – Påverker det utanlandsstudentane sitt val av studiestad? Redaktør: Beate Ellingsen Forfattarar: Tom Halfdan Tobias
Match:
        Dato: 14.03.2018 Versjon: 1.0 Arkivref: 201600992 ved414600 1.

1 Styrets beretning ................................................................................................................ 1 2 Introduksjon til virksomheten og hovedtall ........................................................
Likhet:
        0.9464141726493835

Indekser:
            Nynorsk/søketekst:  32
            Bokmål/treff:       267
_______________________________________________________________

Søketekst:
        Universitet og høgskole
Hoyskole og universitet i norge
Studere i Noreg
Utdanning ved alle universitet og godkjente høgskolar gir rett til støtte frå Lånekassen til å ta 480 studiepoeng. Det er det same som åtte år med fulltidsstudium.
Alle studentar får basislån
Basislån kan alle studentar få, og d
Match:
        Universitet og høgskole
Her finner du informasjon om hvor mye lån og stipend du kan få, og hvor mye du kan tjene før du mister stipendet.
Hoyskole og universitet i Norge
Studere i Norge
Studier ved alle universiteter og godkjente høgskoler gir rett til støtte fra Lånekassen til å ta 480 studiepoeng.
Likhet:
        0.9403376579284668

Indekser:
            Nynorsk/søketekst:  34
            Bokmål/treff:       0
_______________________________________________________________

Søketekst:
        Fagskole
Fagskole
Fagskoleutdanning
Du kan få lån og stipend til fagskoleutdanningar som er godkjende av NOKUT.
Dersom du er usikker på om utdanninga di er godkjent for lån og stipend frå Lånekassen, kan du kontakte oss eller sjå NOKUT si oversikt over godkjende fagskoletilbod.
Alle studentar får ba
Match:
        Fagskole
Fagskole
Fagskoleutdanning
Du kan få lån og stipend til fagskoleutdanninger som er godkjent av NOKUT.
Hvis du er usikker på om utdanningen din er godkjent for lån og stipend fra Lånekassen, kan du spørre oss direkte eller se i NOKUT sin oversikt over akkrediterte fagskoletilbud.
Alle studen
Likhet:
        0.9445965886116028

Indekser:
            Nynorsk/søketekst:  36
            Bokmål/treff:       2
_______________________________________________________________

Søketekst:
        Lån og stipend for å gå på folkehøgskole
Er du elev på ein folkehøgskole, kan du få basislån i inntil ti månader.
Kva er basislån?
Basislån er det alle studentar kan få, og er namnet på det dei fleste kallar studielån. Du får ikkje ekstra lån til å dekke utgiftene ved linja du skal gå på, eller til
Match:
        Lån og stipend for å gå på folkehøgskole
Er du elev på en folkehøgskole, kan du få basislån i inntil ti måneder.
Hva er basislån?

#### Falsk positiv

In [24]:
i = 19
print(search_result[i])
print(nynorsk_texts_joined[i][:250])
print("\n___________\n")
print(bokmål_texts_joined[search_result[i][0]["corpus_id"]][:250])

[{'corpus_id': 291, 'score': 0.937472939491272}]


04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank B

___________



02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Bolig

#### Falske negativer
Veldig lav score!

In [25]:
i = 72
print(search_result[i])
print(nynorsk_texts_joined[i])
print("\n___________\n")
print(bokmål_texts_joined[search_result[i][0]["corpus_id"]])

[{'corpus_id': 38, 'score': 0.7574380040168762}]
Hjelp og kontakt
Veileder frister
Aktuelt
Nytt straumstipend hausten 2022
Alle som kan ha rett til strømstipend, har fått ein e-post frå oss. Logg inn for å søke. Søknadsfristen er 15. januar 2023.
Bruker du avtalegiro? Sjekk nettbanken
06.12.2022
På grunn av en feil har rekninga med frist 15. desember blitt sletta for nokon kundar. Dersom dette gjeld deg, må du betale rekninga med frist 15. desember manuelt, og opprette avtalegiro på nytt. Logg inn på lanekassen.no og vel Di rekning for å finne rekninga.
Når du har oppfylt vilkåra for å få utbetalt pengane, overfører vi dei. Det vil ta 2-3 dagar frå vi utbetaler pengane til du har dei på din konto. Deretter får du ei utbetaling den 15. kvar månad resten av semesteret dersom du studerer i Noreg. Studerer du i utlandet, får du utbetaling for heile semesteret med den første utbetalinga.
Når du er under 18 år er det ein av foreldra dine (ev. verje) som skal signere på dine vegne. Begge foreldra får tilsendt avtalen enten i digital postkasse (Digipost eller E-boks) eller som brev i posten, men det er nok at éin av dei signerer avtalen. Foreldre signerer digitalt i tenesta Foreldresignering med BankID eller tilsvarande. Dersom du er under 18 år og har søkt om lån i tillegg til stipend skal du signere avtalen saman med éin av foreldra dine.
Når du er over 18 år skal du signere avtalen sjølv. Det gjer du ved å logge inn på Dine sider og finne avtalen som skal signerast. Du må bruke BankID eller tilsvarande for å signere digitalt.
Dersom du ikkje får til å signere, kan du oppdatere til nyaste versjon av nettlesaren eller bruke ein annan nettlesar.
Lånet ditt er rente- og avdragsfritt så lenge du får lån og stipend til fulltidsutdanning frå oss. Får du ikkje lenger lån og stipend til fulltidsutdanning, blir lånet rentebærande og du må begynne å betale etter ein betalingsfri periode på omtrent sju månader. Det gjeld både om du avsluttar eller avbryt utdanninga di, om du går over til deltidsutdanning eller om du studerer utan lån og stipend frå Lånekassen.
Du får ein betalingsplan frå oss når du skal begynne nedbetalinga.
Kontakt oss
Kundesenteret vårt har ope på kvardagar frå 09-15. Kontakt oss på telefonnummer

___________

Hjelp og kontakt
Veileder frister
Aktuelt
Nytt strømstipend høsten 2022
Alle som kan ha rett til strømstipend, har fått en e-post fra oss. Logg inn for å søke. Søknadsfristen er 15. januar 2023.
Bruker du avtalegiro? Sjekk nettbanken
06.12.2022
På grunn av en feil har avtalegiro blitt borte for noen kunder. Hvis dette gjelder deg, må du betale regningen med frist 15. desember manuelt, og opprette avtalegiro på nytt. Logg inn på lanekassen.no og velg Din regning for å finne regningen.
Når du har oppfylt vilkårene for å få utbetalt pengene, overfører vi dem. Det vil ta 2-3 dager fra vi utbetaler pengene til du har dem på din konto. Deretter får du en utbetaling den 15. hver måned resten av semesteret hvis du studerer i Norge. Hvis du studerer i utlandet får du utbetaling for hele semesteret med den første utbetalingen.
Når du er under 18 år er det en av foreldrene dine (ev. verge) som skal signere på dine vegne. Begge foreldre får tilsendt avtalen enten i digital postkasse (Digipost eller E-boks) eller som brev i posten, men det er nok at én av dem signerer avtalen. Foreldre signerer digitalt i tjenesten Foreldresignering med BankID eller tilsvarende. Hvis du er under 18 år og har søkt om lån i tillegg til stipend skal du signere avtalen sammen med én av foreldrene dine.
Når du er over 18 år skal du signere avtalen selv. Det gjør du ved å logge inn på Dine sider og finne avtalen som skal signeres. Du må bruke BankID eller tilsvarende for å signere digitalt.
Hvis du ikke får til å signere, kan du oppdatere til nyeste versjon av nettleseren eller bruke en annen nettleser.
Lånet ditt er rente- og avdragsfritt så lenge du får lån og stipend til fulltidsutdanning fra oss. Hvis du ikke får lån og stipend til fulltidsutdanning lenger, blir lånet rentebærende og du må begynne å betale etter en betalingsfri periode på omtrent sju måneder. Det gjelder både hvis du avslutter eller avbryter utdanningen din, hvis du går over til deltidsutdanning eller hvis du studerer uten lån og stipend fra Lånekassen.
Kontakt oss
Kundesenteret vårt har åpent på hverdager fra 09-15. Kontakt oss på telefonnummer

In [26]:
i = 80
print(search_result[i])
print(nynorsk_texts_joined[i][:250])
print("\n___________\n")
print(bokmål_texts_joined[search_result[i][0]["corpus_id"]][:250])

[{'corpus_id': 46, 'score': 0.919640064239502}]
Personvern­erklæring
Kva er personopplysningar?
Ei personopplysning er ei opplysning som er med på å identifisere deg som enkeltperson. Det blir skilt mellom personopplysningar og særlege kategoriar (sensitive) personopplysningar.
Lånekassen er behan

___________

Personvern­erklæring
Hva er personopplysninger?
En personopplysning er en opplysning som er med på å identifisere deg som enkeltperson. Det skilles mellom personopplysninger og særlige kategorier (sensitive) personopplysninger.
Lånekassen er behandli

## Konklusjon

Vi får like mange treff på fasit med naiv cutoff og mean pooling.  
Men naiv cutoff treffer litt flere av den totale mengden dokumenter.  
Vi har ikke gulldata å sammenlikne med, så det er ikke så godt å si helt sikkert om dette er den beste metoden.

In [27]:
pd.DataFrame(doc_alignment_results).T.sort_values("hits")

                    matches  threshold  percent of docs  hits  misses
max_pooling_biter     120.0       0.95            46.88  26.0    29.0
naiv_cutoff_biter     202.0       0.95            78.91  46.0     9.0
naiv_cutoff           217.0       0.95            84.77  48.0     7.0
mean_pooling_biter    212.0       0.95            82.81  48.0     7.0

# Setnings/avsnittsalignment

In [28]:
sent_alignment_results = {}

In [29]:
nynorsk_texts_flat = sorted(list({text for text_list in nynorske.fulltext for text in text_list if text}))
bokmål_texts_flat = sorted(list({text for text_list in bokmålske.fulltext for text in text_list if text}))
len(nynorsk_texts_flat), len(bokmål_texts_flat)

(4032, 6452)

In [30]:
nn_pair_indices = set()
bm_pair_indices = set()
for i, text in enumerate(nynorsk_texts_flat):
    for i2, text2 in enumerate(bokmål_texts_flat):
        if text == text2:
            nn_pair_indices.add(i)
            bm_pair_indices.add(i2)

sent_alignment_results["string_comparison"] = {"matches": len(nn_pair_indices), "percent of sents": round(len(nn_pair_indices)/len(nynorsk_texts_flat), 2)}

In [31]:
nynorsk_texts_flat = [text for i, text in enumerate(nynorsk_texts_flat) if i not in nn_pair_indices]
bokmål_texts_flat = [text for i, text in enumerate(bokmål_texts_flat) if i not in bm_pair_indices]

## Naiv approach
Godta cut-off på sBERT sin maxlengde

In [32]:
import numpy as np

emb_path = Path("embeddings/labse/texts_flat.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_embeddings = model.encode(nynorsk_texts_flat)
    bokmål_embeddings = model.encode(bokmål_texts_flat)
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
sent_alignment_results["naiv_cutoff"] = {"threshold": threshold, "matches": len(matches), "percent of sents": round(len(matches)/len(nynorsk_texts_flat)*100, 2)}

### Inspiser matches

In [33]:
print_matches(matches, nynorsk_texts_flat, bokmål_texts_flat, stop_printing_at=30)

Søketekst:
        ,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden og dokumentasjonen etter at du ha
Match:
        ,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og dokumentasjonen etter at du har fått
Likhet:
        0.9972662925720215

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       9
_______________________________________________________________

Søketekst:
        - Eg er stolt av arbeidsplassen min!
Match:
        - Jeg er stolt av arbeidsplassen min!
Likhet:
        0.9997571706771851

Indekser:
            Nynorsk/søketekst:  3
            Bokmål/treff:       10
_______________________________________________________________

Søketekst:
        - Studentar, spesielt i Sør-Noreg, har fått merke dei høge straumprisane i haust og vinter. Dette er eit målretta tiltak for dei som har fått høgare utgifter til oppvarming av bustad. Tilleggslånet med stipend skal vere tilgjengeleg gjennom Lånekassen i løpet av januar og pengane skal utbetalast ras
Match:
        – Studenter, spesielt i Sør-Norge, har fått merke de høye strømprisene i høst og vinter. Dette er et målrettet tiltak for de som har fått høyere utgifter til oppvarming av bolig. Tilleggslånet med stipend skal være tilgjengelig gjennom Lånekassen i løpet av januar og pengene skal utbetales raskt, si
Likhet:
        0.9760537147521973

Indekser:
            Nynorsk/søketekst:  4
            Bokmål/treff:       6061
_______________________________________________________________

Søketekst:
        0-300 kilometer - 1,92 kroner per kilometer
Match:
        0-300 kilometer - 1,94 kroner per kilometer
Likhet:
        0.9797797203063965

Indekser:
            Nynorsk/søketekst:  11
            Bokmål/treff:       47
_______________________________________________________________

Søketekst:
        01.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 01.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 01.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 01.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 01.06.2022 Haltdalen Sparebank Bolig
Match:
        06.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 06.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 06.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 06.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 06.04.2022 Landkreditt Bank
Likhet:
        0.9539695978164673

Indekser:
            Nynorsk/søketekst:  13
            Bokmål/treff:       91
_______________________________________________________________

Søketekst:
        02.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 02.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 02.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 02.06.2021 Sunndal Sparebank Bol
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9513348340988159

Indekser:
            Nynorsk/søketekst:  15
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spareba
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9523082971572876

Indekser:
            Nynorsk/søketekst:  19
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 04.05.2022 Din Bank (Spareb
Match:
        27.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 27.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 27.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2.07% 27.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 27.04.2022 Din Bank (Spareb
Likhet:
        0.9711713194847107

Indekser:
            Nynorsk/søketekst:  21
            Bokmål/treff:       428
_______________________________________________________________

Søketekst:
        08.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 08.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 08.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,17% 08.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 08.06.2022 Haltdalen Sparebank Bolig
Match:
        06.07.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 06.07.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 06.07.2022 Haltdalen Sparebank Boliglån 34+ 2,32% 06.07.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 06.07.2022 KLP Banken AS Boliglån ordinær - 75%
Likhet:
        0.9536641240119934

Indekser:
            Nynorsk/søketekst:  34
            Bokmål/treff:       96
_______________________________________________________________

Søketekst:
        08.07.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 08.07.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 08.07.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 08.07.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 08.07.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9530143737792969

Indekser:
            Nynorsk/søketekst:  35
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        1. juli stig fastrentene i Lånekassen. Det er elleve år sidan fastrentene var høgare.
Match:
        1. juli stiger fastrentene i Lånekassen. Det er elleve år siden fastrentene var høyere.
Likhet:
        0.9756991863250732

Indekser:
            Nynorsk/søketekst:  44
            Bokmål/treff:       141
_______________________________________________________________

Søketekst:
        10 år: 2,413 prosent (endring: ned frå 2,550 prosent)
Match:
        10 år: 2,413 prosent (endring: ned fra 2,550 prosent)
Likhet:
        0.9995080828666687

Indekser:
            Nynorsk/søketekst:  48
            Bokmål/treff:       152
_______________________________________________________________

Søketekst:
        11.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 11.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 11.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 11.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 11.05.2022 Din Bank (Spareb
Match:
        27.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 27.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 27.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2.07% 27.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 27.04.2022 Din Bank (Spareb
Likhet:
        0.9548418521881104

Indekser:
            Nynorsk/søketekst:  55
            Bokmål/treff:       428
_______________________________________________________________

Søketekst:
        120 400 studentar har så langt søkt om og fått straumstipend, og Lånekassen har til saman utbetalt 361 millionar kroner. Fristen for å søke er 15. juni.
Match:
        120 400 studenter har så langt søkt om og mottatt strømstipend, og Lånekassen har til sammen utbetalt 361 millioner kroner. Fristen for å søke er 15. juni.
Likhet:
        0.9817264080047607

Indekser:
            Nynorsk/søketekst:  60
            Bokmål/treff:       189
_______________________________________________________________

Søketekst:
        15. november (haustsemesteret)
Match:
        15. november (høstsemesteret)
Likhet:
        0.9909558296203613

Indekser:
            Nynorsk/søketekst:  66
            Bokmål/treff:       229
_______________________________________________________________

Søketekst:
        15. november for heile året eller berre haustsemesteret
Match:
        15. november for hele året eller bare høstsemesteret
Likhet:
        0.9928370714187622

Indekser:
            Nynorsk/søketekst:  67
            Bokmål/treff:       231
_______________________________________________________________

Søketekst:
        1500 kilometer eller meir – 0,39 kroner per kilometer
Match:
        1500 kilometer eller mer – 0,39 kroner per kilometer
Likhet:
        0.9993831515312195

Indekser:
            Nynorsk/søketekst:  71
            Bokmål/treff:       233
_______________________________________________________________

Søketekst:
        180 000 elevar kan søke
Match:
        180 000 elever kan søke
Likhet:
        0.9872269630432129

Indekser:
            Nynorsk/søketekst:  82
            Bokmål/treff:       265
_______________________________________________________________

Søketekst:
        180 000 elevar på vidaregåande har kvart år rett på utstyrsstipend. Av desse var det 20 000 som ikkje fekk stipend skoleåret 2021-2022. Om lag 15 000 elevar unnlet å søke, medan 5 000 let vere å signere for stipendet, og fekk derfor ikkje utbetalt pengane.
Match:
        180 000 elever på videregående har hvert år rett på utstyrsstipend. Av disse var det 20 000 som ikke mottok stipend skoleåret 2021-2022. Om lag 15 000 elever unnlot å søke, mens 5 000 lot være å signere for stipendet, og fikk derfor ikke utbetalt pengene.
Likhet:
        0.9928888082504272

Indekser:
            Nynorsk/søketekst:  83
            Bokmål/treff:       266
_______________________________________________________________

Søketekst:
        19 000 kundar har utsett alle innbetalingane til Lånekassen sidan pandemien starta. Det betyr at dei ikkje har betalt ned på studiegjelda si sidan mars 2020.
Match:
        19 000 kunder har utsatt alle innbetalingene til Lånekassen siden pandemiens start. Det betyr at de ikke har betalt ned på studiegjelden sin siden mars 2020.
Likhet:
        0.9797946214675903

Indekser:
            Nynorsk/søketekst:  84
            Bokmål/treff:       271
_______________________________________________________________

Søketekst:
        19 300 nordmenn får støtte frå Lånekassen til å studere i utlandet dette studieåret. Det er det lågaste talet sidan 2008–2009, sett bort frå koronaåret 2020–2021.
Match:
        19 300 nordmenn får støtte fra Lånekassen til å studere i utlandet dette studieåret. Det er det laveste tallet siden 2008–2009, sett bort fra koronaåret 2020–2021.
Likhet:
        0.9977661371231079

Indekser:
            Nynorsk/søketekst:  85
            Bokmål/treff:       272
_______________________________________________________________

Søketekst:
        2 heimreiser
Match:
        2 hjemreiser
Likhet:
        0.9851893782615662

Indekser:
            Nynorsk/søketekst:  90
            Bokmål/treff:       283
_______________________________________________________________

Søketekst:
        2,774 prosent for tre års binding (opp frå 2,403 prosent)
Match:
        2,774 prosent for tre års binding (opp fra 2,403 prosent)
Likhet:
        0.9990999698638916

Indekser:
            Nynorsk/søketekst:  91
            Bokmål/treff:       286
_______________________________________________________________

Søketekst:
        2,901 prosent for fem års binding (opp frå 2,589 prosent)
Match:
        2,901 prosent for fem års binding (opp fra 2,589 prosent)
Likhet:
        0.9990863800048828

Indekser:
            Nynorsk/søketekst:  92
            Bokmål/treff:       288
_______________________________________________________________

Søketekst:
        20 000 studentar over 30 år fekk tilleggslån
Match:
        20 000 studenter over 30 år fikk tilleggslån
Likhet:
        0.9971657991409302

Indekser:
            Nynorsk/søketekst:  93
            Bokmål/treff:       294
_______________________________________________________________

Søketekst:
        22.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 22.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 22.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,17% 22.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 22.06.2022 Haltdalen Sparebank Bolig
Match:
        06.07.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 06.07.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 06.07.2022 Haltdalen Sparebank Boliglån 34+ 2,32% 06.07.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 06.07.2022 KLP Banken AS Boliglån ordinær - 75%
Likhet:
        0.9522784352302551

Indekser:
            Nynorsk/søketekst:  100
            Bokmål/treff:       96
_______________________________________________________________

Søketekst:
        23.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 23.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 23.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 23.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 23.06.2021 Sunndal Sparebank Bol
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.954301118850708

Indekser:
            Nynorsk/søketekst:  101
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        230 300 studentar fekk i starten av februar e-post om at dei kunne få eit straumstipend frå Lånekassen på 3 000 kroner, dersom dei betaler straum i tillegg til husleiga.
Match:
        230 300 studenter fikk i starten av februar e-post om at de kunne få et strømstipend fra Lånekassen på 3 000 kroner, hvis de betaler strøm i tillegg til husleia.
Likhet:
        0.9787850975990295

Indekser:
            Nynorsk/søketekst:  105
            Bokmål/treff:       365
_______________________________________________________________

Søketekst:
        3,018 prosent for ti års binding (opp frå 2,667 prosent)
Match:
        3,018 prosent for ti års binding (opp fra 2,667 prosent)
Likhet:
        0.998640775680542

Indekser:
            Nynorsk/søketekst:  121
            Bokmål/treff:       462
_______________________________________________________________

Søketekst:
        3,435 prosent for 3 års fastrente (stig med 0,661 prosentpoeng)
Match:
        3,435 prosent for 3 års fastrente (stiger med 0,661 prosentpoeng)
Likhet:
        0.9883652329444885

Indekser:
            Nynorsk/søketekst:  122
            Bokmål/treff:       464
_______________________________________________________________

## Del opp setninger/avsnitt som er lengre enn sBERT sin maxlengde

In [34]:
from utils import tokenize_and_split_text

nynorsk_maxlen_parts_flat = [tokenize_and_split_text(text, model.tokenizer, model.max_seq_length) for text in nynorsk_texts_flat]
bokmål_maxlen_parts_flat = [tokenize_and_split_text(text, model.tokenizer, model.max_seq_length) for text in bokmål_texts_flat]

## Naiv 2
Aggreger med Sententence_transformers hack (to første listene kuttes på 1/2 maxlen og konkateneres)

In [35]:
emb_path = Path("embeddings/labse/maxlen_parts_flat.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_embeddings = model.encode([e+[""] for e in nynorsk_maxlen_parts_flat])
    bokmål_embeddings = model.encode([e+[""] for e in bokmål_maxlen_parts_flat])
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
sent_alignment_results["naiv_cutoff_biter"] = {"threshold": threshold, "matches": len(matches), "percent of sents": round(len(matches)/len(nynorsk_maxlen_parts_flat)*100, 2)}

### Inspiser matches

In [36]:
print_matches(matches, nynorsk_texts_flat, bokmål_texts_flat, stop_printing_at=50)

Søketekst:
        ,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden og dokumentasjonen etter at du ha
Match:
        ,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og dokumentasjonen etter at du har fått
Likhet:
        0.9970637559890747

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       9
_______________________________________________________________

Søketekst:
        - Eg er stolt av arbeidsplassen min!
Match:
        - Jeg er stolt av arbeidsplassen min!
Likhet:
        0.9996833801269531

Indekser:
            Nynorsk/søketekst:  3
            Bokmål/treff:       10
_______________________________________________________________

Søketekst:
        - Studentar, spesielt i Sør-Noreg, har fått merke dei høge straumprisane i haust og vinter. Dette er eit målretta tiltak for dei som har fått høgare utgifter til oppvarming av bustad. Tilleggslånet med stipend skal vere tilgjengeleg gjennom Lånekassen i løpet av januar og pengane skal utbetalast ras
Match:
        – Studenter, spesielt i Sør-Norge, har fått merke de høye strømprisene i høst og vinter. Dette er et målrettet tiltak for de som har fått høyere utgifter til oppvarming av bolig. Tilleggslånet med stipend skal være tilgjengelig gjennom Lånekassen i løpet av januar og pengene skal utbetales raskt, si
Likhet:
        0.9771591424942017

Indekser:
            Nynorsk/søketekst:  4
            Bokmål/treff:       6061
_______________________________________________________________

Søketekst:
        0-300 kilometer - 1,92 kroner per kilometer
Match:
        0-300 kilometer - 1,94 kroner per kilometer
Likhet:
        0.9730671644210815

Indekser:
            Nynorsk/søketekst:  11
            Bokmål/treff:       47
_______________________________________________________________

Søketekst:
        01.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 01.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 01.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 01.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 01.06.2022 Haltdalen Sparebank Bolig
Match:
        06.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 06.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 06.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 06.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 06.04.2022 Landkreditt Bank
Likhet:
        0.9542255997657776

Indekser:
            Nynorsk/søketekst:  13
            Bokmål/treff:       91
_______________________________________________________________

Søketekst:
        02.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 02.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 02.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 02.06.2021 Sunndal Sparebank Bol
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9535163640975952

Indekser:
            Nynorsk/søketekst:  15
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spareba
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9529178142547607

Indekser:
            Nynorsk/søketekst:  19
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 04.05.2022 Din Bank (Spareb
Match:
        27.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 27.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 27.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2.07% 27.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 27.04.2022 Din Bank (Spareb
Likhet:
        0.9735581874847412

Indekser:
            Nynorsk/søketekst:  21
            Bokmål/treff:       428
_______________________________________________________________

Søketekst:
        08.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 08.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 08.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,17% 08.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 08.06.2022 Haltdalen Sparebank Bolig
Match:
        06.07.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 06.07.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 06.07.2022 Haltdalen Sparebank Boliglån 34+ 2,32% 06.07.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 06.07.2022 KLP Banken AS Boliglån ordinær - 75%
Likhet:
        0.9535624980926514

Indekser:
            Nynorsk/søketekst:  34
            Bokmål/treff:       96
_______________________________________________________________

Søketekst:
        08.07.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 08.07.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 08.07.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 08.07.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 08.07.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9513890743255615

Indekser:
            Nynorsk/søketekst:  35
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        1. juli stig fastrentene i Lånekassen. Det er elleve år sidan fastrentene var høgare.
Match:
        1. juli stiger fastrentene i Lånekassen. Det er elleve år siden fastrentene var høyere.
Likhet:
        0.9706512689590454

Indekser:
            Nynorsk/søketekst:  44
            Bokmål/treff:       141
_______________________________________________________________

Søketekst:
        10 år: 2,413 prosent (endring: ned frå 2,550 prosent)
Match:
        10 år: 2,413 prosent (endring: ned fra 2,550 prosent)
Likhet:
        0.9995502233505249

Indekser:
            Nynorsk/søketekst:  48
            Bokmål/treff:       152
_______________________________________________________________

Søketekst:
        11.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 11.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 11.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 11.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 11.05.2022 Din Bank (Spareb
Match:
        27.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 27.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 27.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2.07% 27.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 27.04.2022 Din Bank (Spareb
Likhet:
        0.9575574398040771

Indekser:
            Nynorsk/søketekst:  55
            Bokmål/treff:       428
_______________________________________________________________

Søketekst:
        120 400 studentar har så langt søkt om og fått straumstipend, og Lånekassen har til saman utbetalt 361 millionar kroner. Fristen for å søke er 15. juni.
Match:
        120 400 studenter har så langt søkt om og mottatt strømstipend, og Lånekassen har til sammen utbetalt 361 millioner kroner. Fristen for å søke er 15. juni.
Likhet:
        0.984418511390686

Indekser:
            Nynorsk/søketekst:  60
            Bokmål/treff:       189
_______________________________________________________________

Søketekst:
        15. november (haustsemesteret)
Match:
        15. november (høstsemesteret)
Likhet:
        0.9912917613983154

Indekser:
            Nynorsk/søketekst:  66
            Bokmål/treff:       229
_______________________________________________________________

Søketekst:
        15. november for heile året eller berre haustsemesteret
Match:
        15. november for hele året eller bare høstsemesteret
Likhet:
        0.992883563041687

Indekser:
            Nynorsk/søketekst:  67
            Bokmål/treff:       231
_______________________________________________________________

Søketekst:
        1500 kilometer eller meir – 0,39 kroner per kilometer
Match:
        1500 kilometer eller mer – 0,39 kroner per kilometer
Likhet:
        0.9993670582771301

Indekser:
            Nynorsk/søketekst:  71
            Bokmål/treff:       233
_______________________________________________________________

Søketekst:
        16.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 16.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 16.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 16.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 16.06.2021 Sunndal Sparebank Bol
Match:
        17.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 17.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 17.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 17.11.2021 OBOS-banken
Likhet:
        0.9505527019500732

Indekser:
            Nynorsk/søketekst:  73
            Bokmål/treff:       252
_______________________________________________________________

Søketekst:
        180 000 elevar kan søke
Match:
        180 000 elever kan søke
Likhet:
        0.9868432283401489

Indekser:
            Nynorsk/søketekst:  82
            Bokmål/treff:       265
_______________________________________________________________

Søketekst:
        180 000 elevar på vidaregåande har kvart år rett på utstyrsstipend. Av desse var det 20 000 som ikkje fekk stipend skoleåret 2021-2022. Om lag 15 000 elevar unnlet å søke, medan 5 000 let vere å signere for stipendet, og fekk derfor ikkje utbetalt pengane.
Match:
        180 000 elever på videregående har hvert år rett på utstyrsstipend. Av disse var det 20 000 som ikke mottok stipend skoleåret 2021-2022. Om lag 15 000 elever unnlot å søke, mens 5 000 lot være å signere for stipendet, og fikk derfor ikke utbetalt pengene.
Likhet:
        0.9927607178688049

Indekser:
            Nynorsk/søketekst:  83
            Bokmål/treff:       266
_______________________________________________________________

Søketekst:
        19 000 kundar har utsett alle innbetalingane til Lånekassen sidan pandemien starta. Det betyr at dei ikkje har betalt ned på studiegjelda si sidan mars 2020.
Match:
        19 000 kunder har utsatt alle innbetalingene til Lånekassen siden pandemiens start. Det betyr at de ikke har betalt ned på studiegjelden sin siden mars 2020.
Likhet:
        0.9794694185256958

Indekser:
            Nynorsk/søketekst:  84
            Bokmål/treff:       271
_______________________________________________________________

Søketekst:
        19 300 nordmenn får støtte frå Lånekassen til å studere i utlandet dette studieåret. Det er det lågaste talet sidan 2008–2009, sett bort frå koronaåret 2020–2021.
Match:
        19 300 nordmenn får støtte fra Lånekassen til å studere i utlandet dette studieåret. Det er det laveste tallet siden 2008–2009, sett bort fra koronaåret 2020–2021.
Likhet:
        0.9979233741760254

Indekser:
            Nynorsk/søketekst:  85
            Bokmål/treff:       272
_______________________________________________________________

Søketekst:
        2 heimreiser
Match:
        2 hjemreiser
Likhet:
        0.9890320897102356

Indekser:
            Nynorsk/søketekst:  90
            Bokmål/treff:       283
_______________________________________________________________

Søketekst:
        2,774 prosent for tre års binding (opp frå 2,403 prosent)
Match:
        2,774 prosent for tre års binding (opp fra 2,403 prosent)
Likhet:
        0.999334454536438

Indekser:
            Nynorsk/søketekst:  91
            Bokmål/treff:       286
_______________________________________________________________

Søketekst:
        2,901 prosent for fem års binding (opp frå 2,589 prosent)
Match:
        2,901 prosent for fem års binding (opp fra 2,589 prosent)
Likhet:
        0.9993455410003662

Indekser:
            Nynorsk/søketekst:  92
            Bokmål/treff:       288
_______________________________________________________________

Søketekst:
        20 000 studentar over 30 år fekk tilleggslån
Match:
        20 000 studenter over 30 år fikk tilleggslån
Likhet:
        0.9977113008499146

Indekser:
            Nynorsk/søketekst:  93
            Bokmål/treff:       294
_______________________________________________________________

Søketekst:
        22.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 22.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 22.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,17% 22.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 22.06.2022 Haltdalen Sparebank Bolig
Match:
        06.07.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 06.07.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 06.07.2022 Haltdalen Sparebank Boliglån 34+ 2,32% 06.07.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 06.07.2022 KLP Banken AS Boliglån ordinær - 75%
Likhet:
        0.9506555199623108

Indekser:
            Nynorsk/søketekst:  100
            Bokmål/treff:       96
_______________________________________________________________

Søketekst:
        23.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 23.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 23.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 23.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 23.06.2021 Sunndal Sparebank Bol
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9568943381309509

Indekser:
            Nynorsk/søketekst:  101
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        230 300 studentar fekk i starten av februar e-post om at dei kunne få eit straumstipend frå Lånekassen på 3 000 kroner, dersom dei betaler straum i tillegg til husleiga.
Match:
        230 300 studenter fikk i starten av februar e-post om at de kunne få et strømstipend fra Lånekassen på 3 000 kroner, hvis de betaler strøm i tillegg til husleia.
Likhet:
        0.9786779880523682

Indekser:
            Nynorsk/søketekst:  105
            Bokmål/treff:       365
_______________________________________________________________

Søketekst:
        3,018 prosent for ti års binding (opp frå 2,667 prosent)
Match:
        3,018 prosent for ti års binding (opp fra 2,667 prosent)
Likhet:
        0.9989550113677979

Indekser:
            Nynorsk/søketekst:  121
            Bokmål/treff:       462
_______________________________________________________________

Søketekst:
        3,435 prosent for 3 års fastrente (stig med 0,661 prosentpoeng)
Match:
        3,435 prosent for 3 års fastrente (stiger med 0,661 prosentpoeng)
Likhet:
        0.9829616546630859

Indekser:
            Nynorsk/søketekst:  122
            Bokmål/treff:       464
_______________________________________________________________

Søketekst:
        3,581 prosent for 5 års fastrente (stig med 0,680 prosentpoeng)
Match:
        3,581 prosent for 5 års fastrente (stiger med 0,680 prosentpoeng)
Likhet:
        0.9851008653640747

Indekser:
            Nynorsk/søketekst:  123
            Bokmål/treff:       467
_______________________________________________________________

Søketekst:
        3,687 prosent for 10 års fastrente (stig med 0,669 prosentpoeng)
Match:
        3,687 prosent for 10 års fastrente (stiger med 0,669 prosentpoeng)
Likhet:
        0.9827960729598999

Indekser:
            Nynorsk/søketekst:  124
            Bokmål/treff:       468
_______________________________________________________________

Søketekst:
        3,880 prosent for tre års binding (opp frå 3,435 prosent)
Match:
        3,880 prosent for tre års binding (opp fra 3,435 prosent)
Likhet:
        0.9993851184844971

Indekser:
            Nynorsk/søketekst:  125
            Bokmål/treff:       469
_______________________________________________________________

Søketekst:
        3,986 prosent for fem års binding (opp frå 3,581 prosent)
Match:
        3,986 prosent for fem års binding (opp fra 3,581 prosent)
Likhet:
        0.9994094371795654

Indekser:
            Nynorsk/søketekst:  126
            Bokmål/treff:       471
_______________________________________________________________

Søketekst:
        4,054 prosent for ti års binding (opp frå 3,687 prosent)
Match:
        4,054 prosent for ti års binding (opp fra 3,687 prosent)
Likhet:
        0.9989398717880249

Indekser:
            Nynorsk/søketekst:  137
            Bokmål/treff:       549
_______________________________________________________________

Søketekst:
        60 studiepoeng samisk eller kvensk språk dersom du tidlegare har fullført barnehagelærarutdanning
Match:
        60 studiepoeng samisk eller kvensk språk dersom du tidligere har fullført barnehagelærerutdanning
Likhet:
        0.9918293952941895

Indekser:
            Nynorsk/søketekst:  143
            Bokmål/treff:       643
_______________________________________________________________

Søketekst:
        680 000 av tilbakebetalarane i Lånekassen har flytande rente på studielånet sitt, medan 45 500 har fast rente.
Match:
        680 000 av tilbakebetalerne i Lånekassen har flytende rente på studielånet sitt, mens 45 500 har fast rente.
Likhet:
        0.9972315430641174

Indekser:
            Nynorsk/søketekst:  145
            Bokmål/treff:       673
_______________________________________________________________

Søketekst:
        680 800 av tilbakebetalarane i Lånekassen har flytande rente på studielånet sitt, medan 45 300 har fast rente.
Match:
        680 800 av tilbakebetalerne i Lånekassen har flytende rente på studielånet sitt, mens 45 300 har fast rente.
Likhet:
        0.9970636367797852

Indekser:
            Nynorsk/søketekst:  146
            Bokmål/treff:       674

## Mean pooling

In [37]:
emb_path = Path("embeddings/labse/maxlen_parts_flat_mean_pooling.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_embeddings = np.array([np.mean(model.encode(sent), axis=0) for sent in nynorsk_maxlen_parts_flat])
    bokmål_embeddings = np.array([np.mean(model.encode(sent), axis=0) for sent in bokmål_maxlen_parts_flat])
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
sent_alignment_results["mean_pooling_biter"] = {"threshold": threshold, "matches": len(matches), "percent of sents": round(len(matches)/len(nynorsk_maxlen_parts_flat)*100, 2)}

### Inspiser matches

In [38]:
print_matches(matches, nynorsk_texts_flat, bokmål_texts_flat, stop_printing_at=500)

Søketekst:
        ,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden og dokumentasjonen etter at du ha
Match:
        ,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og dokumentasjonen etter at du har fått
Likhet:
        0.9972662925720215

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       9
_______________________________________________________________

Søketekst:
        - Eg er stolt av arbeidsplassen min!
Match:
        - Jeg er stolt av arbeidsplassen min!
Likhet:
        0.9997572898864746

Indekser:
            Nynorsk/søketekst:  3
            Bokmål/treff:       10
_______________________________________________________________

Søketekst:
        - Studentar, spesielt i Sør-Noreg, har fått merke dei høge straumprisane i haust og vinter. Dette er eit målretta tiltak for dei som har fått høgare utgifter til oppvarming av bustad. Tilleggslånet med stipend skal vere tilgjengeleg gjennom Lånekassen i løpet av januar og pengane skal utbetalast ras
Match:
        – Studenter, spesielt i Sør-Norge, har fått merke de høye strømprisene i høst og vinter. Dette er et målrettet tiltak for de som har fått høyere utgifter til oppvarming av bolig. Tilleggslånet med stipend skal være tilgjengelig gjennom Lånekassen i løpet av januar og pengene skal utbetales raskt, si
Likhet:
        0.9760536551475525

Indekser:
            Nynorsk/søketekst:  4
            Bokmål/treff:       6061
_______________________________________________________________

Søketekst:
        0-300 kilometer - 1,92 kroner per kilometer
Match:
        0-300 kilometer - 1,94 kroner per kilometer
Likhet:
        0.9797797203063965

Indekser:
            Nynorsk/søketekst:  11
            Bokmål/treff:       47
_______________________________________________________________

Søketekst:
        01.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 01.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 01.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 01.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 01.06.2022 Haltdalen Sparebank Bolig
Match:
        06.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 06.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 06.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 06.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 06.04.2022 Landkreditt Bank
Likhet:
        0.9539698362350464

Indekser:
            Nynorsk/søketekst:  13
            Bokmål/treff:       91
_______________________________________________________________

Søketekst:
        02.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 02.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 02.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 02.06.2021 Sunndal Sparebank Bol
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9513347148895264

Indekser:
            Nynorsk/søketekst:  15
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spareba
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9523082971572876

Indekser:
            Nynorsk/søketekst:  19
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 04.05.2022 Din Bank (Spareb
Match:
        27.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 27.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 27.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2.07% 27.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 27.04.2022 Din Bank (Spareb
Likhet:
        0.971171498298645

Indekser:
            Nynorsk/søketekst:  21
            Bokmål/treff:       428
_______________________________________________________________

Søketekst:
        08.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 08.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 08.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,17% 08.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 08.06.2022 Haltdalen Sparebank Bolig
Match:
        06.07.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 06.07.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 06.07.2022 Haltdalen Sparebank Boliglån 34+ 2,32% 06.07.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 06.07.2022 KLP Banken AS Boliglån ordinær - 75%
Likhet:
        0.9536640644073486

Indekser:
            Nynorsk/søketekst:  34
            Bokmål/treff:       96
_______________________________________________________________

Søketekst:
        08.07.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 08.07.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 08.07.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 08.07.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 08.07.2020 Fana Spareba
Match:
        17.06.2020 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 17.06.2020 Sunndal Sparebank Boliglån 50 prosent 1,46 % 17.06.2020 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 17.06.2020 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 17.06.2020 Fana Spareba
Likhet:
        0.9642274975776672

Indekser:
            Nynorsk/søketekst:  35
            Bokmål/treff:       251
_______________________________________________________________

Søketekst:
        09.02.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79 % 09.02.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,81 % 09.02.2022 Haltdalen Sparebank Boliglån 60% 1,96 % 09.02.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97 % 09.02.2022 KLP Banken AS Bol
Match:
        02.03.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 02.03.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 02.03.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 02.03.2022 KLP Banken AS Boliglån - 75% ordinær 2.05% 02.03.2022 OBOS-banken AS Bo
Likhet:
        0.9638124704360962

Indekser:
            Nynorsk/søketekst:  36
            Bokmål/treff:       62
_______________________________________________________________

Søketekst:
        1. juli stig fastrentene i Lånekassen. Det er elleve år sidan fastrentene var høgare.
Match:
        1. juli stiger fastrentene i Lånekassen. Det er elleve år siden fastrentene var høyere.
Likhet:
        0.9756990671157837

Indekser:
            Nynorsk/søketekst:  44
            Bokmål/treff:       141
_______________________________________________________________

Søketekst:
        10 år: 2,413 prosent (endring: ned frå 2,550 prosent)
Match:
        10 år: 2,413 prosent (endring: ned fra 2,550 prosent)
Likhet:
        0.9995079040527344

Indekser:
            Nynorsk/søketekst:  48
            Bokmål/treff:       152
_______________________________________________________________

Søketekst:
        11.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 11.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 11.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 11.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 11.05.2022 Din Bank (Spareb
Match:
        27.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 27.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 27.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2.07% 27.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 27.04.2022 Din Bank (Spareb
Likhet:
        0.9548418521881104

Indekser:
            Nynorsk/søketekst:  55
            Bokmål/treff:       428
_______________________________________________________________

Søketekst:
        120 400 studentar har så langt søkt om og fått straumstipend, og Lånekassen har til saman utbetalt 361 millionar kroner. Fristen for å søke er 15. juni.
Match:
        120 400 studenter har så langt søkt om og mottatt strømstipend, og Lånekassen har til sammen utbetalt 361 millioner kroner. Fristen for å søke er 15. juni.
Likhet:
        0.981726348400116

Indekser:
            Nynorsk/søketekst:  60
            Bokmål/treff:       189
_______________________________________________________________

Søketekst:
        15. november (haustsemesteret)
Match:
        15. november (høstsemesteret)
Likhet:
        0.9909555912017822

Indekser:
            Nynorsk/søketekst:  66
            Bokmål/treff:       229
_______________________________________________________________

Søketekst:
        15. november for heile året eller berre haustsemesteret
Match:
        15. november for hele året eller bare høstsemesteret
Likhet:
        0.9928372502326965

Indekser:
            Nynorsk/søketekst:  67
            Bokmål/treff:       231
_______________________________________________________________

Søketekst:
        1500 kilometer eller meir – 0,39 kroner per kilometer
Match:
        1500 kilometer eller mer – 0,39 kroner per kilometer
Likhet:
        0.9993832111358643

Indekser:
            Nynorsk/søketekst:  71
            Bokmål/treff:       233
_______________________________________________________________

Søketekst:
        180 000 elevar kan søke
Match:
        180 000 elever kan søke
Likhet:
        0.987227201461792

Indekser:
            Nynorsk/søketekst:  82
            Bokmål/treff:       265
_______________________________________________________________

Søketekst:
        180 000 elevar på vidaregåande har kvart år rett på utstyrsstipend. Av desse var det 20 000 som ikkje fekk stipend skoleåret 2021-2022. Om lag 15 000 elevar unnlet å søke, medan 5 000 let vere å signere for stipendet, og fekk derfor ikkje utbetalt pengane.
Match:
        180 000 elever på videregående har hvert år rett på utstyrsstipend. Av disse var det 20 000 som ikke mottok stipend skoleåret 2021-2022. Om lag 15 000 elever unnlot å søke, mens 5 000 lot være å signere for stipendet, og fikk derfor ikke utbetalt pengene.
Likhet:
        0.9928890466690063

Indekser:
            Nynorsk/søketekst:  83
            Bokmål/treff:       266
_______________________________________________________________

Søketekst:
        19 000 kundar har utsett alle innbetalingane til Lånekassen sidan pandemien starta. Det betyr at dei ikkje har betalt ned på studiegjelda si sidan mars 2020.
Match:
        19 000 kunder har utsatt alle innbetalingene til Lånekassen siden pandemiens start. Det betyr at de ikke har betalt ned på studiegjelden sin siden mars 2020.
Likhet:
        0.9797945618629456

Indekser:
            Nynorsk/søketekst:  84
            Bokmål/treff:       271
_______________________________________________________________

Søketekst:
        19 300 nordmenn får støtte frå Lånekassen til å studere i utlandet dette studieåret. Det er det lågaste talet sidan 2008–2009, sett bort frå koronaåret 2020–2021.
Match:
        19 300 nordmenn får støtte fra Lånekassen til å studere i utlandet dette studieåret. Det er det laveste tallet siden 2008–2009, sett bort fra koronaåret 2020–2021.
Likhet:
        0.9977660179138184

Indekser:
            Nynorsk/søketekst:  85
            Bokmål/treff:       272
_______________________________________________________________

Søketekst:
        2 heimreiser
Match:
        2 hjemreiser
Likhet:
        0.9851894378662109

Indekser:
            Nynorsk/søketekst:  90
            Bokmål/treff:       283
_______________________________________________________________

Søketekst:
        2,774 prosent for tre års binding (opp frå 2,403 prosent)
Match:
        2,774 prosent for tre års binding (opp fra 2,403 prosent)
Likhet:
        0.9991000890731812

Indekser:
            Nynorsk/søketekst:  91
            Bokmål/treff:       286
_______________________________________________________________

Søketekst:
        2,901 prosent for fem års binding (opp frå 2,589 prosent)
Match:
        2,901 prosent for fem års binding (opp fra 2,589 prosent)
Likhet:
        0.9990864396095276

Indekser:
            Nynorsk/søketekst:  92
            Bokmål/treff:       288
_______________________________________________________________

Søketekst:
        20 000 studentar over 30 år fekk tilleggslån
Match:
        20 000 studenter over 30 år fikk tilleggslån
Likhet:
        0.9971656203269958

Indekser:
            Nynorsk/søketekst:  93
            Bokmål/treff:       294
_______________________________________________________________

Søketekst:
        22.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 22.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 22.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,17% 22.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 22.06.2022 Haltdalen Sparebank Bolig
Match:
        06.07.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 06.07.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 06.07.2022 Haltdalen Sparebank Boliglån 34+ 2,32% 06.07.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 06.07.2022 KLP Banken AS Boliglån ordinær - 75%
Likhet:
        0.9522782564163208

Indekser:
            Nynorsk/søketekst:  100
            Bokmål/treff:       96
_______________________________________________________________

Søketekst:
        23.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 23.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 23.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 23.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 23.06.2021 Sunndal Sparebank Bol
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.954301118850708

Indekser:
            Nynorsk/søketekst:  101
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        230 300 studentar fekk i starten av februar e-post om at dei kunne få eit straumstipend frå Lånekassen på 3 000 kroner, dersom dei betaler straum i tillegg til husleiga.
Match:
        230 300 studenter fikk i starten av februar e-post om at de kunne få et strømstipend fra Lånekassen på 3 000 kroner, hvis de betaler strøm i tillegg til husleia.
Likhet:
        0.9787852764129639

Indekser:
            Nynorsk/søketekst:  105
            Bokmål/treff:       365
_______________________________________________________________

Søketekst:
        3,018 prosent for ti års binding (opp frå 2,667 prosent)
Match:
        3,018 prosent for ti års binding (opp fra 2,667 prosent)
Likhet:
        0.9986408352851868

Indekser:
            Nynorsk/søketekst:  121
            Bokmål/treff:       462
_______________________________________________________________

Søketekst:
        3,435 prosent for 3 års fastrente (stig med 0,661 prosentpoeng)
Match:
        3,435 prosent for 3 års fastrente (stiger med 0,661 prosentpoeng)
Likhet:
        0.9883650541305542

Indekser:
            Nynorsk/søketekst:  122
            Bokmål/treff:       464
_______________________________________________________________

Søketekst:
        3,581 prosent for 5 års fastrente (stig med 0,680 prosentpoeng)
Match:
        3,581 prosent for 5 års fastrente (stiger med 0,680 prosentpoeng)
Likhet:
        0.9895715713500977

Indekser:
            Nynorsk/søketekst:  123
            Bokmål/treff:       467
_______________________________________________________________

Søketekst:
        3,687 prosent for 10 års fastrente (stig med 0,669 prosentpoeng)
Match:
        3,687 prosent for 10 års fastrente (stiger med 0,669 prosentpoeng)
Likhet:
        0.9878418445587158

Indekser:
            Nynorsk/søketekst:  124
            Bokmål/treff:       468
_______________________________________________________________

Søketekst:
        3,880 prosent for tre års binding (opp frå 3,435 prosent)
Match:
        3,880 prosent for tre års binding (opp fra 3,435 prosent)
Likhet:
        0.9991592168807983

Indekser:
            Nynorsk/søketekst:  125
            Bokmål/treff:       469
_______________________________________________________________

Søketekst:
        3,986 prosent for fem års binding (opp frå 3,581 prosent)
Match:
        3,986 prosent for fem års binding (opp fra 3,581 prosent)
Likhet:
        0.999190092086792

Indekser:
            Nynorsk/søketekst:  126
            Bokmål/treff:       471
_______________________________________________________________

Søketekst:
        4,054 prosent for ti års binding (opp frå 3,687 prosent)
Match:
        4,054 prosent for ti års binding (opp fra 3,687 prosent)
Likhet:
        0.9986886978149414

Indekser:
            Nynorsk/søketekst:  137
            Bokmål/treff:       549
_______________________________________________________________

Søketekst:
        60 studiepoeng samisk eller kvensk språk dersom du tidlegare har fullført barnehagelærarutdanning
Match:
        60 studiepoeng samisk eller kvensk språk dersom du tidligere har fullført barnehagelærerutdanning
Likhet:
        0.9936648607254028

Indekser:
            Nynorsk/søketekst:  143
            Bokmål/treff:       643
_______________________________________________________________

Søketekst:
        680 000 av tilbakebetalarane i Lånekassen har flytande rente på studielånet sitt, medan 45 500 har fast rente.
Match:
        680 000 av tilbakebetalerne i Lånekassen har flytende rente på studielånet sitt, mens 45 500 har fast rente.
Likhet:
        0.9975574016571045

Indekser:
            Nynorsk/søketekst:  145
            Bokmål/treff:       673
_______________________________________________________________

Søketekst:
        680 800 av tilbakebetalarane i Lånekassen har flytande rente på studielånet sitt, medan 45 300 har fast rente.
Match:
        680 800 av tilbakebetalerne i Lånekassen har flytende rente på studielånet sitt, mens 45 300 har fast rente.
Likhet:
        0.9973039031028748

Indekser:
            Nynorsk/søketekst:  146
            Bokmål/treff:       674

## Max pooling

In [39]:
emb_path = Path("embeddings/labse/maxlen_parts_flat_max_pooling.npz")
if emb_path.exists():
    loaded = np.load(emb_path)
    bokmål_embeddings = loaded["a"]
    nynorsk_embeddings = loaded["b"]
else:
    nynorsk_embeddings = np.array([np.max(model.encode(sent), axis=0) for sent in nynorsk_maxlen_parts_flat])
    bokmål_embeddings = np.array([np.max(model.encode(sent), axis=0) for sent in bokmål_maxlen_parts_flat])
    np.savez_compressed(emb_path, a=bokmål_embeddings, b=nynorsk_embeddings)

search_result = util.semantic_search(nynorsk_embeddings, bokmål_embeddings, top_k=1)
threshold = 0.95
matches = [(i, e[0]) for i, e in enumerate(search_result) if e[0]["score"] > threshold]
sent_alignment_results["max_pooling_biter"] = {"threshold": threshold, "matches": len(matches), "percent of sents": round(len(matches)/len(nynorsk_maxlen_parts_flat)*100, 2)}

### Inspiser matches

In [40]:
print_matches(matches, nynorsk_texts_flat, bokmål_texts_flat, stop_printing_at=50)

Søketekst:
        ,må du først ha sendt inn ein søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innan sju månader etter at du har fullført ein grad,sender du inn denne søknaden saman med dokumentasjon på graden du har fullført. Du sender inn denne søknaden og dokumentasjonen etter at du ha
Match:
        ,må du først ha sendt inn en søknad om lån og stipendfor det studieåret du får barn. , men har fått barn innen sju måneder etter at du har fullført en grad,sender du inn denne søknaden sammen med dokumentasjon på graden du har fullført. Du sender inn søknaden og dokumentasjonen etter at du har fått
Likhet:
        0.9972662925720215

Indekser:
            Nynorsk/søketekst:  2
            Bokmål/treff:       9
_______________________________________________________________

Søketekst:
        - Eg er stolt av arbeidsplassen min!
Match:
        - Jeg er stolt av arbeidsplassen min!
Likhet:
        0.9997572898864746

Indekser:
            Nynorsk/søketekst:  3
            Bokmål/treff:       10
_______________________________________________________________

Søketekst:
        - Studentar, spesielt i Sør-Noreg, har fått merke dei høge straumprisane i haust og vinter. Dette er eit målretta tiltak for dei som har fått høgare utgifter til oppvarming av bustad. Tilleggslånet med stipend skal vere tilgjengeleg gjennom Lånekassen i løpet av januar og pengane skal utbetalast ras
Match:
        – Studenter, spesielt i Sør-Norge, har fått merke de høye strømprisene i høst og vinter. Dette er et målrettet tiltak for de som har fått høyere utgifter til oppvarming av bolig. Tilleggslånet med stipend skal være tilgjengelig gjennom Lånekassen i løpet av januar og pengene skal utbetales raskt, si
Likhet:
        0.9760536551475525

Indekser:
            Nynorsk/søketekst:  4
            Bokmål/treff:       6061
_______________________________________________________________

Søketekst:
        0-300 kilometer - 1,92 kroner per kilometer
Match:
        0-300 kilometer - 1,94 kroner per kilometer
Likhet:
        0.9797797203063965

Indekser:
            Nynorsk/søketekst:  11
            Bokmål/treff:       47
_______________________________________________________________

Søketekst:
        01.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 01.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 01.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 01.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 01.06.2022 Haltdalen Sparebank Bolig
Match:
        06.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 06.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1.81% 06.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 06.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 06.04.2022 Landkreditt Bank
Likhet:
        0.9539698362350464

Indekser:
            Nynorsk/søketekst:  13
            Bokmål/treff:       91
_______________________________________________________________

Søketekst:
        02.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 02.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,39 % 02.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 02.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 02.06.2021 Sunndal Sparebank Bol
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9513347148895264

Indekser:
            Nynorsk/søketekst:  15
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        03.03.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,44 % 03.03.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.03.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 03.03.2021 Sunndal Sparebank Boliglån 50 prosent 1,61 % 03.03.2021 Fana Spareba
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.9523082971572876

Indekser:
            Nynorsk/søketekst:  19
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        04.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 04.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 04.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 04.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 04.05.2022 Din Bank (Spareb
Match:
        27.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 27.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 27.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2.07% 27.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 27.04.2022 Din Bank (Spareb
Likhet:
        0.971171498298645

Indekser:
            Nynorsk/søketekst:  21
            Bokmål/treff:       428
_______________________________________________________________

Søketekst:
        08.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 08.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 08.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,17% 08.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 08.06.2022 Haltdalen Sparebank Bolig
Match:
        06.07.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 06.07.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 06.07.2022 Haltdalen Sparebank Boliglån 34+ 2,32% 06.07.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 06.07.2022 KLP Banken AS Boliglån ordinær - 75%
Likhet:
        0.9536640644073486

Indekser:
            Nynorsk/søketekst:  34
            Bokmål/treff:       96
_______________________________________________________________

Søketekst:
        1. juli stig fastrentene i Lånekassen. Det er elleve år sidan fastrentene var høgare.
Match:
        1. juli stiger fastrentene i Lånekassen. Det er elleve år siden fastrentene var høyere.
Likhet:
        0.9756990671157837

Indekser:
            Nynorsk/søketekst:  44
            Bokmål/treff:       141
_______________________________________________________________

Søketekst:
        10 år: 2,413 prosent (endring: ned frå 2,550 prosent)
Match:
        10 år: 2,413 prosent (endring: ned fra 2,550 prosent)
Likhet:
        0.9995079040527344

Indekser:
            Nynorsk/søketekst:  48
            Bokmål/treff:       152
_______________________________________________________________

Søketekst:
        11.05.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,79% 11.05.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,97% 11.05.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 11.05.2022 Sunndal Sparebank Boliglån 50 prosent 2,13% 11.05.2022 Din Bank (Spareb
Match:
        27.04.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1.79% 27.04.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1.97% 27.04.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2.07% 27.04.2022 Sunndal Sparebank Boliglån 50 prosent 2.13% 27.04.2022 Din Bank (Spareb
Likhet:
        0.9548418521881104

Indekser:
            Nynorsk/søketekst:  55
            Bokmål/treff:       428
_______________________________________________________________

Søketekst:
        120 400 studentar har så langt søkt om og fått straumstipend, og Lånekassen har til saman utbetalt 361 millionar kroner. Fristen for å søke er 15. juni.
Match:
        120 400 studenter har så langt søkt om og mottatt strømstipend, og Lånekassen har til sammen utbetalt 361 millioner kroner. Fristen for å søke er 15. juni.
Likhet:
        0.981726348400116

Indekser:
            Nynorsk/søketekst:  60
            Bokmål/treff:       189
_______________________________________________________________

Søketekst:
        15. november (haustsemesteret)
Match:
        15. november (høstsemesteret)
Likhet:
        0.9909555912017822

Indekser:
            Nynorsk/søketekst:  66
            Bokmål/treff:       229
_______________________________________________________________

Søketekst:
        15. november for heile året eller berre haustsemesteret
Match:
        15. november for hele året eller bare høstsemesteret
Likhet:
        0.9928372502326965

Indekser:
            Nynorsk/søketekst:  67
            Bokmål/treff:       231
_______________________________________________________________

Søketekst:
        1500 kilometer eller meir – 0,39 kroner per kilometer
Match:
        1500 kilometer eller mer – 0,39 kroner per kilometer
Likhet:
        0.9993832111358643

Indekser:
            Nynorsk/søketekst:  71
            Bokmål/treff:       233
_______________________________________________________________

Søketekst:
        180 000 elevar kan søke
Match:
        180 000 elever kan søke
Likhet:
        0.987227201461792

Indekser:
            Nynorsk/søketekst:  82
            Bokmål/treff:       265
_______________________________________________________________

Søketekst:
        180 000 elevar på vidaregåande har kvart år rett på utstyrsstipend. Av desse var det 20 000 som ikkje fekk stipend skoleåret 2021-2022. Om lag 15 000 elevar unnlet å søke, medan 5 000 let vere å signere for stipendet, og fekk derfor ikkje utbetalt pengane.
Match:
        180 000 elever på videregående har hvert år rett på utstyrsstipend. Av disse var det 20 000 som ikke mottok stipend skoleåret 2021-2022. Om lag 15 000 elever unnlot å søke, mens 5 000 lot være å signere for stipendet, og fikk derfor ikke utbetalt pengene.
Likhet:
        0.9928890466690063

Indekser:
            Nynorsk/søketekst:  83
            Bokmål/treff:       266
_______________________________________________________________

Søketekst:
        19 000 kundar har utsett alle innbetalingane til Lånekassen sidan pandemien starta. Det betyr at dei ikkje har betalt ned på studiegjelda si sidan mars 2020.
Match:
        19 000 kunder har utsatt alle innbetalingene til Lånekassen siden pandemiens start. Det betyr at de ikke har betalt ned på studiegjelden sin siden mars 2020.
Likhet:
        0.9797945618629456

Indekser:
            Nynorsk/søketekst:  84
            Bokmål/treff:       271
_______________________________________________________________

Søketekst:
        19 300 nordmenn får støtte frå Lånekassen til å studere i utlandet dette studieåret. Det er det lågaste talet sidan 2008–2009, sett bort frå koronaåret 2020–2021.
Match:
        19 300 nordmenn får støtte fra Lånekassen til å studere i utlandet dette studieåret. Det er det laveste tallet siden 2008–2009, sett bort fra koronaåret 2020–2021.
Likhet:
        0.9977660179138184

Indekser:
            Nynorsk/søketekst:  85
            Bokmål/treff:       272
_______________________________________________________________

Søketekst:
        2 heimreiser
Match:
        2 hjemreiser
Likhet:
        0.9851894378662109

Indekser:
            Nynorsk/søketekst:  90
            Bokmål/treff:       283
_______________________________________________________________

Søketekst:
        2,774 prosent for tre års binding (opp frå 2,403 prosent)
Match:
        2,774 prosent for tre års binding (opp fra 2,403 prosent)
Likhet:
        0.9991000890731812

Indekser:
            Nynorsk/søketekst:  91
            Bokmål/treff:       286
_______________________________________________________________

Søketekst:
        2,901 prosent for fem års binding (opp frå 2,589 prosent)
Match:
        2,901 prosent for fem års binding (opp fra 2,589 prosent)
Likhet:
        0.9990864396095276

Indekser:
            Nynorsk/søketekst:  92
            Bokmål/treff:       288
_______________________________________________________________

Søketekst:
        20 000 studentar over 30 år fekk tilleggslån
Match:
        20 000 studenter over 30 år fikk tilleggslån
Likhet:
        0.9971656203269958

Indekser:
            Nynorsk/søketekst:  93
            Bokmål/treff:       294
_______________________________________________________________

Søketekst:
        22.06.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 22.06.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 22.06.2022 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 2,17% 22.06.2022 OBOS-banken AS Boliglån 50 % 2,31% 22.06.2022 Haltdalen Sparebank Bolig
Match:
        06.07.2022 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 2,05% 06.07.2022 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 2,07% 06.07.2022 Haltdalen Sparebank Boliglån 34+ 2,32% 06.07.2022 Sunndal Sparebank Boliglån 50 prosent 2,38% 06.07.2022 KLP Banken AS Boliglån ordinær - 75%
Likhet:
        0.9522782564163208

Indekser:
            Nynorsk/søketekst:  100
            Bokmål/treff:       96
_______________________________________________________________

Søketekst:
        23.06.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 23.06.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,33 % 23.06.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,57 % 23.06.2021 OBOS-banken AS Boliglån 50 % 1,57 % 23.06.2021 Sunndal Sparebank Bol
Match:
        03.11.2021 Bulder Bank (Sparebanken Vest) Boliglån innenfor 50 % 1,29 % 03.11.2021 NORDirekte (Skagerrak Sparebank) Boliglån inntil 50% 1,47 % 03.11.2021 Himla Banktjenester (Fana Sparebank) Boliglån innenfor 75 % 1,56 % 03.11.2021 Sunndal Sparebank Boliglån 50 prosent 1,62 % 03.11.2021 OBOS-banken
Likhet:
        0.954301118850708

Indekser:
            Nynorsk/søketekst:  101
            Bokmål/treff:       73
_______________________________________________________________

Søketekst:
        230 300 studentar fekk i starten av februar e-post om at dei kunne få eit straumstipend frå Lånekassen på 3 000 kroner, dersom dei betaler straum i tillegg til husleiga.
Match:
        230 300 studenter fikk i starten av februar e-post om at de kunne få et strømstipend fra Lånekassen på 3 000 kroner, hvis de betaler strøm i tillegg til husleia.
Likhet:
        0.9787852764129639

Indekser:
            Nynorsk/søketekst:  105
            Bokmål/treff:       365
_______________________________________________________________

Søketekst:
        3,018 prosent for ti års binding (opp frå 2,667 prosent)
Match:
        3,018 prosent for ti års binding (opp fra 2,667 prosent)
Likhet:
        0.9986408352851868

Indekser:
            Nynorsk/søketekst:  121
            Bokmål/treff:       462
_______________________________________________________________

Søketekst:
        3,435 prosent for 3 års fastrente (stig med 0,661 prosentpoeng)
Match:
        3,435 prosent for 3 års fastrente (stiger med 0,661 prosentpoeng)
Likhet:
        0.9883650541305542

Indekser:
            Nynorsk/søketekst:  122
            Bokmål/treff:       464
_______________________________________________________________

Søketekst:
        3,581 prosent for 5 års fastrente (stig med 0,680 prosentpoeng)
Match:
        3,581 prosent for 5 års fastrente (stiger med 0,680 prosentpoeng)
Likhet:
        0.9895715713500977

Indekser:
            Nynorsk/søketekst:  123
            Bokmål/treff:       467
_______________________________________________________________

Søketekst:
        3,687 prosent for 10 års fastrente (stig med 0,669 prosentpoeng)
Match:
        3,687 prosent for 10 års fastrente (stiger med 0,669 prosentpoeng)
Likhet:
        0.9878418445587158

Indekser:
            Nynorsk/søketekst:  124
            Bokmål/treff:       468
_______________________________________________________________

Søketekst:
        3,880 prosent for tre års binding (opp frå 3,435 prosent)
Match:
        3,880 prosent for tre års binding (opp fra 3,435 prosent)
Likhet:
        0.9991592168807983

Indekser:
            Nynorsk/søketekst:  125
            Bokmål/treff:       469
_______________________________________________________________

Søketekst:
        3,986 prosent for fem års binding (opp frå 3,581 prosent)
Match:
        3,986 prosent for fem års binding (opp fra 3,581 prosent)
Likhet:
        0.999190092086792

Indekser:
            Nynorsk/søketekst:  126
            Bokmål/treff:       471
_______________________________________________________________

Søketekst:
        4,054 prosent for ti års binding (opp frå 3,687 prosent)
Match:
        4,054 prosent for ti års binding (opp fra 3,687 prosent)
Likhet:
        0.9986886978149414

Indekser:
            Nynorsk/søketekst:  137
            Bokmål/treff:       549
_______________________________________________________________

Søketekst:
        60 studiepoeng samisk eller kvensk språk dersom du tidlegare har fullført barnehagelærarutdanning
Match:
        60 studiepoeng samisk eller kvensk språk dersom du tidligere har fullført barnehagelærerutdanning
Likhet:
        0.9936648607254028

Indekser:
            Nynorsk/søketekst:  143
            Bokmål/treff:       643
_______________________________________________________________

Søketekst:
        680 000 av tilbakebetalarane i Lånekassen har flytande rente på studielånet sitt, medan 45 500 har fast rente.
Match:
        680 000 av tilbakebetalerne i Lånekassen har flytende rente på studielånet sitt, mens 45 500 har fast rente.
Likhet:
        0.9975574016571045

Indekser:
            Nynorsk/søketekst:  145
            Bokmål/treff:       673
_______________________________________________________________

Søketekst:
        680 800 av tilbakebetalarane i Lånekassen har flytande rente på studielånet sitt, medan 45 300 har fast rente.
Match:
        680 800 av tilbakebetalerne i Lånekassen har flytende rente på studielånet sitt, mens 45 300 har fast rente.
Likhet:
        0.9973039031028748

Indekser:
            Nynorsk/søketekst:  146
            Bokmål/treff:       674
_______________________________________________________________

Søketekst:
        687 200 av tilbakebetalarar i Lånekassen har flytande rente på studielånet sitt, medan 44 500 har fast rente.
Match:
        687 200 av tilbakebetalerne i Lånekassen har flytende rente på studielånet sitt, mens 44 500 har fast rente.
Likhet:
        0.9981249570846558

Indekser:
            Nynorsk/søketekst:  147
            Bokmål/treff:       675
_______________________________________________________________

Søketekst:
        711 800 av Lånekassens tilbakebetalarar har per i dag flytande rente, medan 27 300 har fast rente på studielånet.
Match:
        711 800 av Lånekassens tilbakebetalere har per i dag flytende rente, mens 27 300 har fast rente på studielånet.
Likhet:
        0.9975841045379639

Indekser:
            Nynorsk/søketekst:  150
            Bokmål/treff:       689
_______________________________________________________________

Søketekst:
        72 000 studentar har søkt om straumstipend hittil
Match:
        72 000 studenter har søkt om strømstipend hittil
Likhet:
        0.9574227333068848

Indekser:
            Nynorsk/søketekst:  151
            Bokmål/treff:       691
_______________________________________________________________

Søketekst:
        740 900 av kundane i Lånekassen betaler no på studielånet sitt. 713 600 av dei har flytande rente på studielånet, medan 27 300 har fast rente.
Match:
        740 900 av Lånekassens kunder betaler nå på studielånet sitt. 713 600 av dem har flytende rente på studielånet, mens 27 300 har fast rente.
Likhet:
        0.9924622774124146

Indekser:

## Konklusjon
Vi får flest matches med naiv cutoff på biter (vi vet at over 93% av avsnittene er innenfor modellens makslengde)  
Vi har ikke gulldata å sammenlikne med, så det er ikke så godt å si helt sikkert om dette er den beste metoden.

In [41]:
pd.DataFrame(sent_alignment_results).T.sort_values("matches")

                    matches  percent of sents  threshold
string_comparison     341.0              0.08        NaN
max_pooling_biter    2362.0             63.99       0.95
mean_pooling_biter   2374.0             64.32       0.95
naiv_cutoff          2379.0             64.45       0.95
naiv_cutoff_biter    2389.0             64.73       0.95